### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.ReceivablesPayables."Application Method"
alId: ID 1381
namespace: Microsoft.Finance.ReceivablesPayables
baseKind: Enum
kind: Enum
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.ReceivablesPayables
langs:
- al
seeAlso:
- '[Enum](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
objectProperties:
- name: Extensible
  value: "True"
  promoted: true
- name: AssignmentCompatibility
  value: "True"
  promoted: false
enumValues:
- name: Manual
  uid: E:Enum::Microsoft#Finance#ReceivablesPayables#Application_Method.Manual
- name: '"Apply to Oldest"'
  uid: E:Enum::Microsoft#Finance#ReceivablesPayables#Application_Method.Apply_to_Oldest
commentId: O:Enum::Microsoft#Finance#ReceivablesPayables#Application Method
name: '"Application Method"'
uid: O:Enum::Microsoft#Finance#ReceivablesPayables#Application_Method
