### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.VAT.Reporting."VAT Report Configuration"
alId: ID 740
namespace: Microsoft.Finance.VAT.Reporting
baseKind: Enum
kind: Enum
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.VAT.Reporting
langs:
- al
seeAlso:
- '[Enum](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
objectProperties:
- name: Extensible
  value: "True"
  promoted: true
- name: AssignmentCompatibility
  value: "True"
  promoted: false
enumValues:
- name: '"EC Sales List"'
  uid: E:Enum::Microsoft#Finance#VAT#Reporting#VAT_Report_Configuration.EC_Sales_List
- name: '"VAT Return"'
  uid: E:Enum::Microsoft#Finance#VAT#Reporting#VAT_Report_Configuration.VAT_Return
- name: '"Intrastat Report"'
  uid: E:Enum::Microsoft#Finance#VAT#Reporting#VAT_Report_Configuration.Intrastat_Report
commentId: O:Enum::Microsoft#Finance#VAT#Reporting#VAT Report Configuration
name: '"VAT Report Configuration"'
uid: O:Enum::Microsoft#Finance#VAT#Reporting#VAT_Report_Configuration
