### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Template Line Type"
alId: ID 8619
namespace: System.IO
baseKind: Enum
kind: Enum
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Enum](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
objectProperties:
- name: Extensible
  value: "True"
  promoted: true
- name: AssignmentCompatibility
  value: "True"
  promoted: false
enumValues:
- name: Field
  uid: E:Enum::System#IO#Config#_Template_Line_Type.Field
- name: Template
  uid: E:Enum::System#IO#Config#_Template_Line_Type.Template
- name: '"Related Template"'
  uid: E:Enum::System#IO#Config#_Template_Line_Type.Related_Template
commentId: O:Enum::System#IO#Config# Template Line Type
name: '"Config. Template Line Type"'
uid: O:Enum::System#IO#Config#_Template_Line_Type
