### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Entry Type"
alId: ID 1511
namespace: System.Environment.Configuration
baseKind: Enum
kind: Enum
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Enum](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
objectProperties:
- name: Extensible
  value: "True"
  promoted: true
- name: AssignmentCompatibility
  value: "True"
  promoted: false
enumValues:
- name: '"New Record"'
  uid: E:Enum::System#Environment#Configuration#Notification_Entry_Type.New_Record
- name: Approval
  uid: E:Enum::System#Environment#Configuration#Notification_Entry_Type.Approval
- name: Overdue
  uid: E:Enum::System#Environment#Configuration#Notification_Entry_Type.Overdue
commentId: O:Enum::System#Environment#Configuration#Notification Entry Type
name: '"Notification Entry Type"'
uid: O:Enum::System#Environment#Configuration#Notification_Entry_Type
