### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Creation Type"
alId: ID 9197
namespace: System.Environment.Configuration
baseKind: Enum
kind: Enum
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Enum](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
objectProperties:
- name: Extensible
  value: "True"
  promoted: true
- name: AssignmentCompatibility
  value: "True"
  promoted: false
enumValues:
- name: Add
  uid: E:Enum::System#Environment#Configuration#Creation_Type.Add
- name: Replace
  uid: E:Enum::System#Environment#Configuration#Creation_Type.Replace
commentId: O:Enum::System#Environment#Configuration#Creation Type
name: '"Creation Type"'
uid: O:Enum::System#Environment#Configuration#Creation_Type
