### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Schedule Type"
alId: ID 1512
namespace: System.Environment.Configuration
baseKind: Enum
kind: Enum
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Enum](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
objectProperties:
- name: Extensible
  value: "True"
  promoted: true
- name: AssignmentCompatibility
  value: "True"
  promoted: false
enumValues:
- name: Instantly
  uid: E:Enum::System#Environment#Configuration#Notification_Schedule_Type.Instantly
- name: Daily
  uid: E:Enum::System#Environment#Configuration#Notification_Schedule_Type.Daily
- name: Weekly
  uid: E:Enum::System#Environment#Configuration#Notification_Schedule_Type.Weekly
- name: Monthly
  uid: E:Enum::System#Environment#Configuration#Notification_Schedule_Type.Monthly
commentId: O:Enum::System#Environment#Configuration#Notification Schedule Type
name: '"Notification Schedule Type"'
uid: O:Enum::System#Environment#Configuration#Notification_Schedule_Type
