### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Data Schema"
alId: ID 8610
namespace: System.IO
baseKind: XmlPort
kind: XmlPort
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[XmlPort](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-xmlport-object)'
objectProperties:
- name: Caption
  value: Config. Data Schema
  promoted: false
- name: DefaultNamespace
  value: http://www.w3.org/2001/XMLSchema
  promoted: false
- name: UseDefaultNamespace
  value: "True"
  promoted: false
- name: Caption
  value: Config. Data Schema
  promoted: false
- name: DefaultNamespace
  value: http://www.w3.org/2001/XMLSchema
  promoted: false
- name: UseDefaultNamespace
  value: "True"
  promoted: false
methods:
- syntax:
    content: 'procedure GetRootElementName(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetRootElementName
  uid: M:XmlPort::System#IO#Config#_Data_Schema.GetRootElementName:Text
commentId: O:XmlPort::System#IO#Config# Data Schema
name: '"Config. Data Schema"'
uid: O:XmlPort::System#IO#Config#_Data_Schema
