### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Extension Subscribers"
alId: ID 2510
namespace: System.Environment.Configuration
baseKind: Page
kind: PageExtension
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)'
commentId: O:PageExtension::System#Environment#Configuration#Extension Subscribers
name: '"Extension Subscribers"'
uid: O:PageExtension::System#Environment#Configuration#Extension_Subscribers
