### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Accessible Companies"
alId: ID 9177
namespace: System.Environment.Configuration
baseKind: Page
kind: PageExtension
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)'
commentId: O:PageExtension::System#Environment#Configuration#Accessible Companies
name: '"Accessible Companies"'
uid: O:PageExtension::System#Environment#Configuration#Accessible_Companies
