### YamlMime:BusinessCentralApplicationObject
fqName: System.Azure.Identity."Plan Configuration Card Ext."
alId: ID 9208
namespace: System.Azure.Identity
baseKind: Page
kind: PageExtension
parent: N:Module::Base_Application::Namespace::System.Azure.Identity
langs:
- al
seeAlso:
- '[Page Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)'
commentId: O:PageExtension::System#Azure#Identity#Plan Configuration Card Ext#
name: '"Plan Configuration Card Ext."'
uid: O:PageExtension::System#Azure#Identity#Plan_Configuration_Card_Ext#
