### YamlMime:BusinessCentralApplicationObject
fqName: System.Security.User."User Settings"
alId: ID 9204
namespace: System.Security.User
baseKind: Page
kind: PageExtension
parent: N:Module::Base_Application::Namespace::System.Security.User
langs:
- al
seeAlso:
- '[Page Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)'
commentId: O:PageExtension::System#Security#User#User Settings
name: '"User Settings"'
uid: O:PageExtension::System#Security#User#User_Settings
