### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Advanced Settings Ext."
alId: ID 9202
namespace: System.Environment.Configuration
baseKind: Page
kind: PageExtension
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-ext-object)'
commentId: O:PageExtension::System#Environment#Configuration#Advanced Settings Ext#
name: '"Advanced Settings Ext."'
uid: O:PageExtension::System#Environment#Configuration#Advanced_Settings_Ext#
