### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Feature To Update - BaseApp"
alId: ID 2611
namespace: System.Environment.Configuration
baseKind: Enum
kind: EnumExtension
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Enum Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
enumValues:
- name: SalesPrices
  obsoletion:
    state: pending
    reason: Feature SalesPrices will be enabled by default in version 22.0.
    version: "19.0"
  uid: E:EnumExtension::System#Environment#Configuration#Feature_To_Update_-_BaseApp.SalesPrices
- name: CurrencySymbolMapping
  obsoletion:
    state: pending
    reason: Feature CurrencySymbolMapping will be enabled by default in version 22.0.
    version: "22.0"
  uid: E:EnumExtension::System#Environment#Configuration#Feature_To_Update_-_BaseApp.CurrencySymbolMapping
- name: OptionMapping
  obsoletion:
    state: pending
    reason: Feature OptionMapping will be enabled by default in version 22.0.
    version: "22.0"
  uid: E:EnumExtension::System#Environment#Configuration#Feature_To_Update_-_BaseApp.OptionMapping
- name: EnablePlatformBasedReportSelection
  obsoletion:
    state: pending
    reason: Feature EnablePlatformBasedReportSelection will be enabled by default in version 24.0.
    version: "24.0"
  uid: E:EnumExtension::System#Environment#Configuration#Feature_To_Update_-_BaseApp.EnablePlatformBasedReportSelection
- name: PhysInvtOrderPackageTracking
  obsoletion:
    state: pending
    reason: Feature Phys. Invt. Orders Package Tracking will be enabled by default in version 27.0.
    version: "24.0"
  uid: E:EnumExtension::System#Environment#Configuration#Feature_To_Update_-_BaseApp.PhysInvtOrderPackageTracking
- name: GLCurrencyRevaluation
  obsoletion:
    state: pending
    reason: Feature G/L Currency REvaluation will be enabled by default in version 27.0.
    version: "24.0"
  uid: E:EnumExtension::System#Environment#Configuration#Feature_To_Update_-_BaseApp.GLCurrencyRevaluation
commentId: O:EnumExtension::System#Environment#Configuration#Feature To Update - BaseApp
name: '"Feature To Update - BaseApp"'
uid: O:EnumExtension::System#Environment#Configuration#Feature_To_Update_-_BaseApp
