### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Manual Setup Category Ext"
alId: ID 1876
namespace: System.Environment.Configuration
baseKind: Enum
kind: EnumExtension
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Enum Extension](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-extensible-enums)'
enumValues:
- name: General
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.General
- name: Finance
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Finance
- name: Sales
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Sales
- name: Jobs
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Jobs
- name: '"Fixed Assets"'
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Fixed_Assets
- name: Purchasing
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Purchasing
- name: '"Reference Data"'
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Reference_Data
- name: HR
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.HR
- name: Inventory
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Inventory
- name: Service
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Service
- name: System
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.System
- name: '"Relationship Mgt"'
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Relationship_Mgt
- name: Intercompany
  uid: E:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext.Intercompany
commentId: O:EnumExtension::System#Environment#Configuration#Manual Setup Category Ext
name: '"Manual Setup Category Ext"'
uid: O:EnumExtension::System#Environment#Configuration#Manual_Setup_Category_Ext
