### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Application Area Mgmt. Facade"
alId: ID 9179
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: SingleInstance
  value: "True"
  promoted: false
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
methods:
- syntax:
    content: 'procedure GetApplicationAreaSetupRecFromCompany(var ApplicationAreaSetup: Record "Application Area Setup", CompanyName: Text): Boolean'
    parameters:
    - id: ApplicationAreaSetup
      parameterType:
        name: Record "Application Area Setup"
        isExternal: true
    - id: CompanyName
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: GetApplicationAreaSetupRecFromCompany
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.GetApplicationAreaSetupRecFromCompany(Application_Area_Setup@,Text):Boolean
- syntax:
    content: 'procedure GetApplicationAreaSetup(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetApplicationAreaSetup
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.GetApplicationAreaSetup:Text
- syntax:
    content: procedure SetupApplicationArea()
  name: SetupApplicationArea
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.SetupApplicationArea
- syntax:
    content: 'procedure IsFoundationEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsFoundationEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsFoundationEnabled:Boolean
- syntax:
    content: 'procedure IsBasicOnlyEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsBasicOnlyEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsBasicOnlyEnabled:Boolean
- syntax:
    content: 'procedure IsAdvancedEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsAdvancedEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsAdvancedEnabled:Boolean
- syntax:
    content: 'procedure IsFixedAssetEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsFixedAssetEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsFixedAssetEnabled:Boolean
- syntax:
    content: 'procedure IsJobsEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsJobsEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsJobsEnabled:Boolean
- syntax:
    content: 'procedure IsBasicHREnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsBasicHREnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsBasicHREnabled:Boolean
- syntax:
    content: 'procedure IsDimensionEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsDimensionEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsDimensionEnabled:Boolean
- syntax:
    content: 'procedure IsLocationEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsLocationEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsLocationEnabled:Boolean
- syntax:
    content: 'procedure IsAssemblyEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsAssemblyEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsAssemblyEnabled:Boolean
- syntax:
    content: 'procedure IsItemChargesEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsItemChargesEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsItemChargesEnabled:Boolean
- syntax:
    content: 'procedure IsItemReferencesEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsItemReferencesEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsItemReferencesEnabled:Boolean
- syntax:
    content: 'procedure IsItemTrackingEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsItemTrackingEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsItemTrackingEnabled:Boolean
- syntax:
    content: 'procedure IsIntercompanyEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsIntercompanyEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsIntercompanyEnabled:Boolean
- syntax:
    content: 'procedure IsSalesReturnOrderEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsSalesReturnOrderEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsSalesReturnOrderEnabled:Boolean
- syntax:
    content: 'procedure IsPurchaseReturnOrderEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsPurchaseReturnOrderEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsPurchaseReturnOrderEnabled:Boolean
- syntax:
    content: 'procedure IsCostAccountingEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsCostAccountingEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsCostAccountingEnabled:Boolean
- syntax:
    content: 'procedure IsSalesBudgetEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsSalesBudgetEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsSalesBudgetEnabled:Boolean
- syntax:
    content: 'procedure IsPurchaseBudgetEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsPurchaseBudgetEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsPurchaseBudgetEnabled:Boolean
- syntax:
    content: 'procedure IsItemBudgetEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsItemBudgetEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsItemBudgetEnabled:Boolean
- syntax:
    content: 'procedure IsSalesAnalysisEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsSalesAnalysisEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsSalesAnalysisEnabled:Boolean
- syntax:
    content: 'procedure IsPurchaseAnalysisEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsPurchaseAnalysisEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsPurchaseAnalysisEnabled:Boolean
- syntax:
    content: 'procedure IsInventoryAnalysisEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsInventoryAnalysisEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsInventoryAnalysisEnabled:Boolean
- syntax:
    content: 'procedure IsManufacturingEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsManufacturingEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsManufacturingEnabled:Boolean
- syntax:
    content: 'procedure IsPlanningEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsPlanningEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsPlanningEnabled:Boolean
- syntax:
    content: 'procedure IsRelationshipMgmtEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsRelationshipMgmtEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsRelationshipMgmtEnabled:Boolean
- syntax:
    content: 'procedure IsServiceEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsServiceEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsServiceEnabled:Boolean
- syntax:
    content: 'procedure IsWarehouseEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsWarehouseEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsWarehouseEnabled:Boolean
- syntax:
    content: 'procedure IsReservationEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsReservationEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsReservationEnabled:Boolean
- syntax:
    content: 'procedure IsOrderPromisingEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsOrderPromisingEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsOrderPromisingEnabled:Boolean
- syntax:
    content: 'procedure IsCommentsEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsCommentsEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsCommentsEnabled:Boolean
- syntax:
    content: 'procedure IsRecordLinksEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsRecordLinksEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsRecordLinksEnabled:Boolean
- syntax:
    content: 'procedure IsNotesEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsNotesEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsNotesEnabled:Boolean
- syntax:
    content: 'procedure IsVATEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsVATEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsVATEnabled:Boolean
- syntax:
    content: 'procedure IsSalesTaxEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsSalesTaxEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsSalesTaxEnabled:Boolean
- syntax:
    content: 'procedure IsBasicCountryEnabled(CountryCode: Code[10]): Boolean'
    parameters:
    - id: CountryCode
      parameterType:
        name: Code[10]
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsBasicCountryEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsBasicCountryEnabled(Code[10]):Boolean
- syntax:
    content: 'procedure IsSuiteEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsSuiteEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsSuiteEnabled:Boolean
- syntax:
    content: 'procedure IsAllDisabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsAllDisabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsAllDisabled:Boolean
- syntax:
    content: 'procedure IsPremiumEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsPremiumEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsPremiumEnabled:Boolean
- syntax:
    content: procedure CheckAppAreaOnlyBasic()
  name: CheckAppAreaOnlyBasic
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.CheckAppAreaOnlyBasic
- syntax:
    content: 'procedure IsValidExperienceTierSelected(SelectedExperienceTier: Text): Boolean'
    parameters:
    - id: SelectedExperienceTier
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsValidExperienceTierSelected
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsValidExperienceTierSelected(Text):Boolean
- syntax:
    content: 'procedure LookupExperienceTier(var NewExperienceTier: Text): Boolean'
    parameters:
    - id: NewExperienceTier
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: LookupExperienceTier
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.LookupExperienceTier(Text@):Boolean
- syntax:
    content: 'procedure SaveExperienceTierCurrentCompany(NewExperienceTier: Text): Boolean'
    parameters:
    - id: NewExperienceTier
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: SaveExperienceTierCurrentCompany
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.SaveExperienceTierCurrentCompany(Text):Boolean
- syntax:
    content: 'procedure GetExperienceTierCurrentCompany(var ExperienceTier: Text): Boolean'
    parameters:
    - id: ExperienceTier
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: GetExperienceTierCurrentCompany
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.GetExperienceTierCurrentCompany(Text@):Boolean
- syntax:
    content: procedure RefreshExperienceTierCurrentCompany()
  name: RefreshExperienceTierCurrentCompany
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.RefreshExperienceTierCurrentCompany
- syntax:
    content: 'procedure IsBasicExperienceEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsBasicExperienceEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsBasicExperienceEnabled:Boolean
- syntax:
    content: 'procedure IsEssentialExperienceEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsEssentialExperienceEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsEssentialExperienceEnabled:Boolean
- syntax:
    content: 'procedure IsPremiumExperienceEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsPremiumExperienceEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsPremiumExperienceEnabled:Boolean
- syntax:
    content: 'procedure IsCustomExperienceEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsCustomExperienceEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsCustomExperienceEnabled:Boolean
- syntax:
    content: 'procedure IsAdvancedExperienceEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsAdvancedExperienceEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.IsAdvancedExperienceEnabled:Boolean
- syntax:
    content: 'procedure GetBasicApplicationAreas(var TempApplicationAreaSetup: Record "Application Area Setup" temporary)'
    parameters:
    - id: TempApplicationAreaSetup
      parameterType:
        name: Record "Application Area Setup" temporary
        isExternal: true
  name: GetBasicApplicationAreas
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.GetBasicApplicationAreas(Application_Area_Setup@)
- syntax:
    content: 'procedure GetEssentialExperienceAppAreas(var TempApplicationAreaSetup: Record "Application Area Setup" temporary)'
    parameters:
    - id: TempApplicationAreaSetup
      parameterType:
        name: Record "Application Area Setup" temporary
        isExternal: true
  name: GetEssentialExperienceAppAreas
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.GetEssentialExperienceAppAreas(Application_Area_Setup@)
- syntax:
    content: 'procedure GetPremiumExperienceAppAreas(var TempApplicationAreaSetup: Record "Application Area Setup" temporary)'
    parameters:
    - id: TempApplicationAreaSetup
      parameterType:
        name: Record "Application Area Setup" temporary
        isExternal: true
  name: GetPremiumExperienceAppAreas
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.GetPremiumExperienceAppAreas(Application_Area_Setup@)
- syntax:
    content: 'procedure SetHideApplicationAreaError(NewHideApplicationAreaError: Boolean)'
    parameters:
    - id: NewHideApplicationAreaError
      parameterType:
        name: Boolean
        isExternal: true
  name: SetHideApplicationAreaError
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade.SetHideApplicationAreaError(Boolean)
commentId: O:Codeunit::System#Environment#Configuration#Application Area Mgmt# Facade
name: '"Application Area Mgmt. Facade"'
uid: O:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#_Facade
