### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Progress Bar"
alId: ID 8615
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure Init(NewMaxCount: Integer, NewStepCount: Integer, WindowTitle: Text)'
    parameters:
    - id: NewMaxCount
      parameterType:
        name: Integer
        isExternal: true
    - id: NewStepCount
      parameterType:
        name: Integer
        isExternal: true
    - id: WindowTitle
      parameterType:
        name: Text
        isExternal: true
  name: Init
  uid: M:Codeunit::System#IO#Config#_Progress_Bar.Init(Integer,Integer,Text)
- syntax:
    content: 'procedure Update(WindowText: Text)'
    parameters:
    - id: WindowText
      parameterType:
        name: Text
        isExternal: true
  name: Update
  uid: M:Codeunit::System#IO#Config#_Progress_Bar.Update(Text)
- syntax:
    signatures:
    - '[TryFunction]'
    content: 'procedure UpdateCount(WindowText: Text, Count: Integer): Boolean'
    parameters:
    - id: WindowText
      parameterType:
        name: Text
        isExternal: true
    - id: Count
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: UpdateCount
  uid: M:Codeunit::System#IO#Config#_Progress_Bar.UpdateCount(Text,Integer):Boolean
- syntax:
    content: procedure Close()
  name: Close
  uid: M:Codeunit::System#IO#Config#_Progress_Bar.Close
commentId: O:Codeunit::System#IO#Config# Progress Bar
name: '"Config. Progress Bar"'
uid: O:Codeunit::System#IO#Config#_Progress_Bar
