### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Env. Info Proxy"
alId: ID 9995
namespace: System.Environment
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: ObsoleteReason
  value: Microsoft Invoicing is not supported on Business Central
  promoted: false
- name: ObsoleteState
  value: Pending
  promoted: false
- name: ObsoleteTag
  value: "15.0"
  promoted: false
methods:
- syntax:
    signatures:
    - '[Obsolete(Microsoft Invoicing is not supported on Business Central,15.0)]'
    content: 'procedure IsInvoicing(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsInvoicing
  obsoletion:
    state: pending
    reason: Microsoft Invoicing is not supported on Business Central
    version: "15.0"
  uid: M:Codeunit::System#Environment#Env#_Info_Proxy.IsInvoicing:Boolean
commentId: O:Codeunit::System#Environment#Env# Info Proxy
name: '"Env. Info Proxy"'
obsoletion:
  state: pending
  reason: Microsoft Invoicing is not supported on Business Central
  version: "15.0"
uid: O:Codeunit::System#Environment#Env#_Info_Proxy
