### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Guided Experience Subscribers"
alId: ID 1878
namespace: System.Environment
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure GetYourSalesWithinOutlookVideoLinkTxt(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetYourSalesWithinOutlookVideoLinkTxt
  uid: M:Codeunit::System#Environment#Guided_Experience_Subscribers.GetYourSalesWithinOutlookVideoLinkTxt:Text
commentId: O:Codeunit::System#Environment#Guided Experience Subscribers
name: '"Guided Experience Subscribers"'
uid: O:Codeunit::System#Environment#Guided_Experience_Subscribers
