### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Try Validate"
alId: ID 8613
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure SetValidateParameters(var SourceFieldRef: FieldRef, SourceValue: Variant)'
    parameters:
    - id: SourceFieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    - id: SourceValue
      parameterType:
        name: Variant
        isExternal: true
  name: SetValidateParameters
  uid: M:Codeunit::System#IO#Config#_Try_Validate.SetValidateParameters(FieldRef@,Variant)
commentId: O:Codeunit::System#IO#Config# Try Validate
name: '"Config. Try Validate"'
uid: O:Codeunit::System#IO#Config#_Try_Validate
