### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Feature - Report Selection"
alId: ID 5409
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: Permissions
  value: TableData "Feature Data Update Status" = rm
  promoted: false
- name: TableNo
  value: ""
  promoted: false
methods:
- syntax:
    content: 'procedure IsDataUpdateRequired(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsDataUpdateRequired
  uid: M:Codeunit::System#Environment#Configuration#Feature_-_Report_Selection.IsDataUpdateRequired:Boolean
- syntax:
    content: procedure ReviewData()
  name: ReviewData
  uid: M:Codeunit::System#Environment#Configuration#Feature_-_Report_Selection.ReviewData
- syntax:
    content: 'procedure AfterUpdate(FeatureDataUpdateStatus: __MissingTypeSymbol__)'
    parameters:
    - id: FeatureDataUpdateStatus
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: AfterUpdate
  uid: M:Codeunit::System#Environment#Configuration#Feature_-_Report_Selection.AfterUpdate(__MissingSymbol__)
- syntax:
    content: 'procedure UpdateData(FeatureDataUpdateStatus: __MissingTypeSymbol__)'
    parameters:
    - id: FeatureDataUpdateStatus
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: UpdateData
  uid: M:Codeunit::System#Environment#Configuration#Feature_-_Report_Selection.UpdateData(__MissingSymbol__)
- syntax:
    content: 'procedure GetTaskDescription(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetTaskDescription
  uid: M:Codeunit::System#Environment#Configuration#Feature_-_Report_Selection.GetTaskDescription:Text
implements:
- name: __MissingInterface__
  isExternal: true
commentId: O:Codeunit::System#Environment#Configuration#Feature - Report Selection
name: '"Feature - Report Selection"'
uid: O:Codeunit::System#Environment#Configuration#Feature_-_Report_Selection
