### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Data Upgrade Mgt."
alId: ID 9900
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure SetTableSyncSetup(TableId: Integer, UpgradeTableId: Integer, TableUpgradeMode: Option)'
    parameters:
    - id: TableId
      parameterType:
        name: Integer
        isExternal: true
    - id: UpgradeTableId
      parameterType:
        name: Integer
        isExternal: true
    - id: TableUpgradeMode
      parameterType:
        name: Option
        isExternal: true
  name: SetTableSyncSetup
  uid: M:Codeunit::System#Environment#Configuration#Data_Upgrade_Mgt#.SetTableSyncSetup(Integer,Integer,Option)
- syntax:
    content: procedure SetUpgradeInProgress()
  name: SetUpgradeInProgress
  uid: M:Codeunit::System#Environment#Configuration#Data_Upgrade_Mgt#.SetUpgradeInProgress
- syntax:
    content: 'procedure IsUpgradeInProgress(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsUpgradeInProgress
  uid: M:Codeunit::System#Environment#Configuration#Data_Upgrade_Mgt#.IsUpgradeInProgress:Boolean
commentId: O:Codeunit::System#Environment#Configuration#Data Upgrade Mgt#
name: '"Data Upgrade Mgt."'
uid: O:Codeunit::System#Environment#Configuration#Data_Upgrade_Mgt#
