### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. XML Exchange"
alId: ID 8614
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure ApplyPackageFilter(ConfigPackageTable: Record "Config. Package Table", var RecRef: RecordRef)'
    parameters:
    - id: ConfigPackageTable
      parameterType:
        name: Record "Config. Package Table"
        isExternal: true
    - id: RecRef
      parameterType:
        name: RecordRef
        isExternal: true
  name: ApplyPackageFilter
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.ApplyPackageFilter(Config#_Package_Table,RecordRef@)
- syntax:
    content: 'procedure ExportPackageXMLToStream(ConfigPackage: Record "Config. Package", PackageOutStream: OutStream)'
    parameters:
    - id: ConfigPackage
      description: Configuration package to export.
      parameterType:
        name: Record "Config. Package"
        isExternal: true
    - id: PackageOutStream
      description: OutStream object that the content of the package will be written to.
      parameterType:
        name: OutStream
        isExternal: true
  summary: Export the provided configuration package to an OutStream.
  name: ExportPackageXMLToStream
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.ExportPackageXMLToStream(Config#_Package,OutStream)
- syntax:
    content: 'procedure GetImportedPackageCode(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetImportedPackageCode
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.GetImportedPackageCode:Code[20]
- syntax:
    content: 'procedure ImportPackageXML(XMLDataFile: Text): Boolean'
    parameters:
    - id: XMLDataFile
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ImportPackageXML
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.ImportPackageXML(Text):Boolean
- syntax:
    content: 'procedure ImportPackageXMLFromStream(InStream: InStream): Boolean'
    parameters:
    - id: InStream
      parameterType:
        name: InStream
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ImportPackageXMLFromStream
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.ImportPackageXMLFromStream(InStream):Boolean
- syntax:
    content: 'procedure ImportPackageXMLWithCodeFromStream(InStream: InStream, PackageCode: Code[20]): Boolean'
    parameters:
    - id: InStream
      parameterType:
        name: InStream
        isExternal: true
    - id: PackageCode
      parameterType:
        name: Code[20]
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ImportPackageXMLWithCodeFromStream
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.ImportPackageXMLWithCodeFromStream(InStream,Code[20]):Boolean
- syntax:
    content: 'procedure GetElementName(NameIn: Text[250]): Text[250]'
    parameters:
    - id: NameIn
      parameterType:
        name: Text[250]
        isExternal: true
    return:
      returnType:
        name: Text[250]
        isExternal: true
  name: GetElementName
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.GetElementName(Text[250]):Text[250]
- syntax:
    content: 'procedure GetFieldElementName(NameIn: Text[250]): Text[250]'
    parameters:
    - id: NameIn
      parameterType:
        name: Text[250]
        isExternal: true
    return:
      returnType:
        name: Text[250]
        isExternal: true
  name: GetFieldElementName
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.GetFieldElementName(Text[250]):Text[250]
- syntax:
    content: 'procedure GetTableElementName(NameIn: Text[250]): Text[250]'
    parameters:
    - id: NameIn
      parameterType:
        name: Text[250]
        isExternal: true
    return:
      returnType:
        name: Text[250]
        isExternal: true
  name: GetTableElementName
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.GetTableElementName(Text[250]):Text[250]
- syntax:
    content: 'procedure GetMediaFolderName(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetMediaFolderName
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.GetMediaFolderName:Text
- syntax:
    content: 'procedure GetXSDType(TableID: Integer, FieldID: Integer): Text[30]'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    - id: FieldID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Text[30]
        isExternal: true
  name: GetXSDType
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.GetXSDType(Integer,Integer):Text[30]
- syntax:
    content: 'procedure SetAdvanced(NewAdvanced: Boolean)'
    parameters:
    - id: NewAdvanced
      parameterType:
        name: Boolean
        isExternal: true
  name: SetAdvanced
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.SetAdvanced(Boolean)
- syntax:
    content: 'procedure SetCalledFromCode(NewCalledFromCode: Boolean)'
    parameters:
    - id: NewCalledFromCode
      parameterType:
        name: Boolean
        isExternal: true
  name: SetCalledFromCode
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.SetCalledFromCode(Boolean)
- syntax:
    content: 'procedure SetExcelMode(NewExcelMode: Boolean)'
    parameters:
    - id: NewExcelMode
      parameterType:
        name: Boolean
        isExternal: true
  name: SetExcelMode
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.SetExcelMode(Boolean)
- syntax:
    content: 'procedure SetHideDialog(NewHideDialog: Boolean)'
    parameters:
    - id: NewHideDialog
      parameterType:
        name: Boolean
        isExternal: true
  name: SetHideDialog
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.SetHideDialog(Boolean)
- syntax:
    content: 'procedure SetExportFromWksht(NewExportFromWksht: Boolean)'
    parameters:
    - id: NewExportFromWksht
      parameterType:
        name: Boolean
        isExternal: true
  name: SetExportFromWksht
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.SetExportFromWksht(Boolean)
- syntax:
    content: 'procedure SetPrefixMode(PrefixMode: Boolean)'
    parameters:
    - id: PrefixMode
      parameterType:
        name: Boolean
        isExternal: true
  name: SetPrefixMode
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.SetPrefixMode(Boolean)
- syntax:
    content: 'procedure TableObjectExists(TableId: Integer): Boolean'
    parameters:
    - id: TableId
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: TableObjectExists
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.TableObjectExists(Integer):Boolean
- syntax:
    content: 'procedure DecompressPackageToBlob(TempBlob: __MissingTypeSymbol__, TempBlobUncompressed: __MissingTypeSymbol__)'
    parameters:
    - id: TempBlob
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    - id: TempBlobUncompressed
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: DecompressPackageToBlob
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.DecompressPackageToBlob(__MissingSymbol__@,__MissingSymbol__@)
- syntax:
    content: 'procedure GetFileDialogFilter(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetFileDialogFilter
  uid: M:Codeunit::System#IO#Config#_XML_Exchange.GetFileDialogFilter:Text
commentId: O:Codeunit::System#IO#Config# XML Exchange
name: '"Config. XML Exchange"'
uid: O:Codeunit::System#IO#Config#_XML_Exchange
