### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Validate Package"
alId: ID 8621
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: TableNo
  value: Config. Package Table
  promoted: false
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Table
    name: System.IO."Config. Package Table"
    isExternal: false
commentId: O:Codeunit::System#IO#Config# Validate Package
name: '"Config. Validate Package"'
uid: O:Codeunit::System#IO#Config#_Validate_Package
