### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Hyperlink Manifest"
alId: ID 1643
namespace: System.Environment
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure GetNoSeriesForPurchaseCrMemo(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPurchaseCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPurchaseCrMemo:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForPurchaseQuote(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPurchaseQuote
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPurchaseQuote:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForPurchaseInvoice(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPurchaseInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPurchaseInvoice:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForPurchaseOrder(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPurchaseOrder
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPurchaseOrder:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForSalesCrMemo(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForSalesCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForSalesCrMemo:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForSalesInvoice(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForSalesInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForSalesInvoice:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForSalesOrder(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForSalesOrder
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForSalesOrder:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForSalesQuote(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForSalesQuote
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForSalesQuote:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForPostedSalesInvoice(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPostedSalesInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPostedSalesInvoice:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForPostedSalesCrMemo(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPostedSalesCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPostedSalesCrMemo:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForPostedPurchInvoice(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPostedPurchInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPostedPurchInvoice:Code[20]
- syntax:
    content: 'procedure GetNoSeriesForPostedPurchCrMemo(): Code[20]'
    return:
      returnType:
        name: Code[20]
        isExternal: true
  name: GetNoSeriesForPostedPurchCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNoSeriesForPostedPurchCrMemo:Code[20]
- syntax:
    content: 'procedure GetNameForPurchaseCrMemo(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPurchaseCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPurchaseCrMemo:Text
- syntax:
    content: 'procedure GetNameForPurchaseInvoice(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPurchaseInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPurchaseInvoice:Text
- syntax:
    content: 'procedure GetNameForPurchaseOrder(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPurchaseOrder
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPurchaseOrder:Text
- syntax:
    content: 'procedure GetAcronymForPurchaseOrder(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetAcronymForPurchaseOrder
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetAcronymForPurchaseOrder:Text
- syntax:
    content: 'procedure GetNameForPurchaseQuote(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPurchaseQuote
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPurchaseQuote:Text
- syntax:
    content: 'procedure GetNameForSalesCrMemo(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForSalesCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForSalesCrMemo:Text
- syntax:
    content: 'procedure GetNameForSalesInvoice(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForSalesInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForSalesInvoice:Text
- syntax:
    content: 'procedure GetNameForSalesOrder(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForSalesOrder
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForSalesOrder:Text
- syntax:
    content: 'procedure GetNameForSalesQuote(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForSalesQuote
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForSalesQuote:Text
- syntax:
    content: 'procedure GetNameForPostedSalesInvoice(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPostedSalesInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPostedSalesInvoice:Text
- syntax:
    content: 'procedure GetNameForPostedSalesCrMemo(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPostedSalesCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPostedSalesCrMemo:Text
- syntax:
    content: 'procedure GetNameForPostedPurchInvoice(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPostedPurchInvoice
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPostedPurchInvoice:Text
- syntax:
    content: 'procedure GetNameForPostedPurchCrMemo(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNameForPostedPurchCrMemo
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNameForPostedPurchCrMemo:Text
- syntax:
    content: 'procedure GetNumberSeriesRegex(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNumberSeriesRegex
  uid: M:Codeunit::System#Environment#Hyperlink_Manifest.GetNumberSeriesRegex:Text
commentId: O:Codeunit::System#Environment#Hyperlink Manifest
name: '"Hyperlink Manifest"'
uid: O:Codeunit::System#Environment#Hyperlink_Manifest
