### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package - Import"
alId: ID 8620
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure ApplyRapidStartPackage(var TempConfigSetup: Record "Config. Setup" temporary)'
    parameters:
    - id: TempConfigSetup
      parameterType:
        name: Record "Config. Setup" temporary
        isExternal: true
  name: ApplyRapidStartPackage
  uid: M:Codeunit::System#IO#Config#_Package_-_Import.ApplyRapidStartPackage(Config#_Setup@)
- syntax:
    content: 'procedure ImportAndApplyRapidStartPackageStream(TempBlob: __MissingTypeSymbol__)'
    parameters:
    - id: TempBlob
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: ImportAndApplyRapidStartPackageStream
  uid: M:Codeunit::System#IO#Config#_Package_-_Import.ImportAndApplyRapidStartPackageStream(__MissingSymbol__@)
- syntax:
    content: 'procedure ImportRapidStartPackageStream(TempBlob: __MissingTypeSymbol__, var TempConfigSetup: Record "Config. Setup" temporary)'
    parameters:
    - id: TempBlob
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    - id: TempConfigSetup
      parameterType:
        name: Record "Config. Setup" temporary
        isExternal: true
  name: ImportRapidStartPackageStream
  uid: M:Codeunit::System#IO#Config#_Package_-_Import.ImportRapidStartPackageStream(__MissingSymbol__@,Config#_Setup@)
commentId: O:Codeunit::System#IO#Config# Package - Import
name: '"Config. Package - Import"'
uid: O:Codeunit::System#IO#Config#_Package_-_Import
