### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."AAD Application Interface"
alId: ID 8820
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure CreateAADApplication(ClientId: Guid, ClientDescription: Text[50], ContactInformation: Text[50])'
    parameters:
    - id: ClientId
      parameterType:
        name: Guid
        isExternal: true
    - id: ClientDescription
      parameterType:
        name: Text[50]
        isExternal: true
    - id: ContactInformation
      parameterType:
        name: Text[50]
        isExternal: true
  name: CreateAADApplication
  uid: M:Codeunit::System#Environment#Configuration#AAD_Application_Interface.CreateAADApplication(Guid,Text[50],Text[50])
- syntax:
    content: 'procedure CreateAADApplication(ClientId: Guid, ClientDescription: Text[50], ContactInformation: Text[50], EnableAADApplication: Boolean)'
    parameters:
    - id: ClientId
      parameterType:
        name: Guid
        isExternal: true
    - id: ClientDescription
      parameterType:
        name: Text[50]
        isExternal: true
    - id: ContactInformation
      parameterType:
        name: Text[50]
        isExternal: true
    - id: EnableAADApplication
      parameterType:
        name: Boolean
        isExternal: true
  name: CreateAADApplication
  uid: M:Codeunit::System#Environment#Configuration#AAD_Application_Interface.CreateAADApplication(Guid,Text[50],Text[50],Boolean)
- syntax:
    content: 'procedure ModifyAADApplicationDescription(ClientId: Guid, ClientDescription: Text[50])'
    parameters:
    - id: ClientId
      parameterType:
        name: Guid
        isExternal: true
    - id: ClientDescription
      parameterType:
        name: Text[50]
        isExternal: true
  name: ModifyAADApplicationDescription
  uid: M:Codeunit::System#Environment#Configuration#AAD_Application_Interface.ModifyAADApplicationDescription(Guid,Text[50])
commentId: O:Codeunit::System#Environment#Configuration#AAD Application Interface
name: '"AAD Application Interface"'
uid: O:Codeunit::System#Environment#Configuration#AAD_Application_Interface
