### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Management"
alId: ID 8616
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: EventSubscriberInstance
  value: Manual
  promoted: false
methods:
- syntax:
    content: 'procedure CopyDataDialog(NewCompanyName: Text[30], var ConfigLine: Record "Config. Line")'
    parameters:
    - id: NewCompanyName
      parameterType:
        name: Text[30]
        isExternal: true
    - id: ConfigLine
      parameterType:
        name: Record "Config. Line"
        isExternal: true
  name: CopyDataDialog
  uid: M:Codeunit::System#IO#Config#_Management.CopyDataDialog(Text[30],Config#_Line@)
- syntax:
    content: 'procedure TransferContents(TableID: Integer, NewCompanyName: Text[30], CopyTable: Boolean): Boolean'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    - id: NewCompanyName
      parameterType:
        name: Text[30]
        isExternal: true
    - id: CopyTable
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: TransferContents
  uid: M:Codeunit::System#IO#Config#_Management.TransferContents(Integer,Text[30],Boolean):Boolean
- syntax:
    content: 'procedure FindPage(TableID: Integer): Integer'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Integer
        isExternal: true
  name: FindPage
  uid: M:Codeunit::System#IO#Config#_Management.FindPage(Integer):Integer
- syntax:
    content: 'procedure GetConfigTables(AllObj: __MissingTypeSymbol__, IncludeWithDataOnly: Boolean, IncludeRelatedTables: Boolean, IncludeDimensionTables: Boolean, IncludeLicensedTablesOnly: Boolean, IncludeReferringTable: Boolean)'
    parameters:
    - id: AllObj
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    - id: IncludeWithDataOnly
      parameterType:
        name: Boolean
        isExternal: true
    - id: IncludeRelatedTables
      parameterType:
        name: Boolean
        isExternal: true
    - id: IncludeDimensionTables
      parameterType:
        name: Boolean
        isExternal: true
    - id: IncludeLicensedTablesOnly
      parameterType:
        name: Boolean
        isExternal: true
    - id: IncludeReferringTable
      parameterType:
        name: Boolean
        isExternal: true
  name: GetConfigTables
  uid: M:Codeunit::System#IO#Config#_Management.GetConfigTables(__MissingSymbol__@,Boolean,Boolean,Boolean,Boolean,Boolean)
- syntax:
    content: 'procedure IsDefaultDimTable(TableID: Integer): Boolean'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsDefaultDimTable
  uid: M:Codeunit::System#IO#Config#_Management.IsDefaultDimTable(Integer):Boolean
- syntax:
    content: 'procedure IsDimSetIDTable(TableID: Integer): Boolean'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsDimSetIDTable
  uid: M:Codeunit::System#IO#Config#_Management.IsDimSetIDTable(Integer):Boolean
- syntax:
    content: 'procedure IsSystemTable(TableID: Integer): Boolean'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsSystemTable
  uid: M:Codeunit::System#IO#Config#_Management.IsSystemTable(Integer):Boolean
- syntax:
    content: procedure AssignParentLineNos()
  name: AssignParentLineNos
  uid: M:Codeunit::System#IO#Config#_Management.AssignParentLineNos
- syntax:
    content: 'procedure MakeTableFilter(var ConfigLine: Record "Config. Line", Export: Boolean): Text'
    parameters:
    - id: ConfigLine
      parameterType:
        name: Record "Config. Line"
        isExternal: true
    - id: Export
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: MakeTableFilter
  uid: M:Codeunit::System#IO#Config#_Management.MakeTableFilter(Config#_Line@,Boolean):Text
- syntax:
    content: 'procedure SetHideDialog(NewHideDialog: Boolean)'
    parameters:
    - id: NewHideDialog
      parameterType:
        name: Boolean
        isExternal: true
  name: SetHideDialog
  uid: M:Codeunit::System#IO#Config#_Management.SetHideDialog(Boolean)
- syntax:
    content: 'procedure DimensionFieldID(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: DimensionFieldID
  uid: M:Codeunit::System#IO#Config#_Management.DimensionFieldID:Integer
commentId: O:Codeunit::System#IO#Config# Management
name: '"Config. Management"'
uid: O:Codeunit::System#IO#Config#_Management
