### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Lifecycle Handler"
alId: ID 1508
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
commentId: O:Codeunit::System#Environment#Configuration#Notification Lifecycle Handler
name: '"Notification Lifecycle Handler"'
uid: O:Codeunit::System#Environment#Configuration#Notification_Lifecycle_Handler
