### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Pckg. Compression Mgt."
alId: ID 8619
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
commentId: O:Codeunit::System#IO#Config# Pckg# Compression Mgt#
name: '"Config. Pckg. Compression Mgt."'
uid: O:Codeunit::System#IO#Config#_Pckg#_Compression_Mgt#
