### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Webservice Notification Mgt."
alId: ID 810
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
commentId: O:Codeunit::System#Environment#Configuration#Webservice Notification Mgt#
name: '"Webservice Notification Mgt."'
uid: O:Codeunit::System#Environment#Configuration#Webservice_Notification_Mgt#
