### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Import Table in Backgr"
alId: ID 8626
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: TableNo
  value: Parallel Session Entry
  promoted: false
  xrefType:
    internalReference: O:Table::System#Threading#Parallel_Session_Entry
    name: System.Threading."Parallel Session Entry"
    isExternal: false
commentId: O:Codeunit::System#IO#Config# Import Table in Backgr
name: '"Config. Import Table in Backgr"'
uid: O:Codeunit::System#IO#Config#_Import_Table_in_Backgr
