### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Application Area Mgmt."
alId: ID 9178
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
methods:
- syntax:
    content: 'procedure GetApplicationAreas(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetApplicationAreas
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#.GetApplicationAreas:Text
- syntax:
    content: 'procedure IsVATEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsVATEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#.IsVATEnabled:Boolean
- syntax:
    content: 'procedure IsSalesTaxEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsSalesTaxEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#.IsSalesTaxEnabled:Boolean
- syntax:
    content: 'procedure IsBasicCountryEnabled(CountryCode: Code[10]): Boolean'
    parameters:
    - id: CountryCode
      parameterType:
        name: Code[10]
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsBasicCountryEnabled
  uid: M:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#.IsBasicCountryEnabled(Code[10]):Boolean
commentId: O:Codeunit::System#Environment#Configuration#Application Area Mgmt#
name: '"Application Area Mgmt."'
uid: O:Codeunit::System#Environment#Configuration#Application_Area_Mgmt#
