### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Application System Constants"
alId: ID 9015
namespace: System.Environment
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure OriginalApplicationVersion(): Text[248]'
    return:
      returnType:
        name: Text[248]
        isExternal: true
  name: OriginalApplicationVersion
  uid: M:Codeunit::System#Environment#Application_System_Constants.OriginalApplicationVersion:Text[248]
- syntax:
    content: 'procedure ApplicationVersion(): Text[248]'
    return:
      returnType:
        name: Text[248]
        isExternal: true
  name: ApplicationVersion
  uid: M:Codeunit::System#Environment#Application_System_Constants.ApplicationVersion:Text[248]
- syntax:
    content: 'procedure BuildFileVersion(): Text[248]'
    return:
      returnType:
        name: Text[248]
        isExternal: true
  name: BuildFileVersion
  uid: M:Codeunit::System#Environment#Application_System_Constants.BuildFileVersion:Text[248]
- syntax:
    content: 'procedure ApplicationBuild(): Text[80]'
    return:
      returnType:
        name: Text[80]
        isExternal: true
  name: ApplicationBuild
  uid: M:Codeunit::System#Environment#Application_System_Constants.ApplicationBuild:Text[80]
- syntax:
    content: 'procedure BuildBranch(): Text[250]'
    return:
      returnType:
        name: Text[250]
        isExternal: true
  name: BuildBranch
  uid: M:Codeunit::System#Environment#Application_System_Constants.BuildBranch:Text[250]
- syntax:
    content: 'procedure PlatformProductVersion(): Text[80]'
    return:
      returnType:
        name: Text[80]
        isExternal: true
  name: PlatformProductVersion
  uid: M:Codeunit::System#Environment#Application_System_Constants.PlatformProductVersion:Text[80]
- syntax:
    content: 'procedure PlatformFileVersion(): Text[80]'
    return:
      returnType:
        name: Text[80]
        isExternal: true
  name: PlatformFileVersion
  uid: M:Codeunit::System#Environment#Application_System_Constants.PlatformFileVersion:Text[80]
commentId: O:Codeunit::System#Environment#Application System Constants
name: '"Application System Constants"'
uid: O:Codeunit::System#Environment#Application_System_Constants
