### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Validate Management"
alId: ID 8617
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure ValidateFieldValue(var RecRef: RecordRef, var FieldRef: FieldRef, Value: Text, SkipValidation: Boolean, LanguageID: Integer)'
    parameters:
    - id: RecRef
      parameterType:
        name: RecordRef
        isExternal: true
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    - id: Value
      parameterType:
        name: Text
        isExternal: true
    - id: SkipValidation
      parameterType:
        name: Boolean
        isExternal: true
    - id: LanguageID
      parameterType:
        name: Integer
        isExternal: true
  name: ValidateFieldValue
  uid: M:Codeunit::System#IO#Config#_Validate_Management.ValidateFieldValue(RecordRef@,FieldRef@,Text,Boolean,Integer)
- syntax:
    content: 'procedure OptionNoExists(var FieldRef: FieldRef, OptionValue: Text): Boolean'
    parameters:
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    - id: OptionValue
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: OptionNoExists
  uid: M:Codeunit::System#IO#Config#_Validate_Management.OptionNoExists(FieldRef@,Text):Boolean
- syntax:
    content: 'procedure GetOptionNo(Value: Text, FieldRef: FieldRef): Integer'
    parameters:
    - id: Value
      parameterType:
        name: Text
        isExternal: true
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetOptionNo
  uid: M:Codeunit::System#IO#Config#_Validate_Management.GetOptionNo(Text,FieldRef):Integer
- syntax:
    content: 'procedure GetRelationInfoByIDs(TableNo: Integer, FieldNo: Integer, var RelationTableNo: Integer, var RelationFieldNo: Integer): Boolean'
    parameters:
    - id: TableNo
      parameterType:
        name: Integer
        isExternal: true
    - id: FieldNo
      parameterType:
        name: Integer
        isExternal: true
    - id: RelationTableNo
      parameterType:
        name: Integer
        isExternal: true
    - id: RelationFieldNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: GetRelationInfoByIDs
  uid: M:Codeunit::System#IO#Config#_Validate_Management.GetRelationInfoByIDs(Integer,Integer,Integer@,Integer@):Boolean
- syntax:
    content: 'procedure GetRelationTableID(TableID: Integer, FieldID: Integer): Integer'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    - id: FieldID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetRelationTableID
  uid: M:Codeunit::System#IO#Config#_Validate_Management.GetRelationTableID(Integer,Integer):Integer
- syntax:
    content: 'procedure IsRelationInKeyFields(TableNo: Integer, FieldNo: Integer): Boolean'
    parameters:
    - id: TableNo
      parameterType:
        name: Integer
        isExternal: true
    - id: FieldNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsRelationInKeyFields
  uid: M:Codeunit::System#IO#Config#_Validate_Management.IsRelationInKeyFields(Integer,Integer):Boolean
- syntax:
    content: 'procedure ValidateFieldRefRelationAgainstCompanyData(FieldRef: FieldRef): Text'
    parameters:
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: ValidateFieldRefRelationAgainstCompanyData
  uid: M:Codeunit::System#IO#Config#_Validate_Management.ValidateFieldRefRelationAgainstCompanyData(FieldRef):Text
- syntax:
    content: 'procedure EvaluateValue(var FieldRef: FieldRef, Value: Text, XMLValue: Boolean): Text'
    parameters:
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    - id: Value
      parameterType:
        name: Text
        isExternal: true
    - id: XMLValue
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: EvaluateValue
  uid: M:Codeunit::System#IO#Config#_Validate_Management.EvaluateValue(FieldRef@,Text,Boolean):Text
- syntax:
    content: 'procedure EvaluateValueWithValidate(var FieldRef: FieldRef, Value: Text, XMLValue: Boolean): Text'
    parameters:
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    - id: Value
      parameterType:
        name: Text
        isExternal: true
    - id: XMLValue
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: EvaluateValueWithValidate
  uid: M:Codeunit::System#IO#Config#_Validate_Management.EvaluateValueWithValidate(FieldRef@,Text,Boolean):Text
- syntax:
    content: 'procedure XMLFormat(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: XMLFormat
  uid: M:Codeunit::System#IO#Config#_Validate_Management.XMLFormat:Integer
- syntax:
    content: 'procedure IsKeyField(TableID: Integer, FieldID: Integer): Boolean'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    - id: FieldID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsKeyField
  uid: M:Codeunit::System#IO#Config#_Validate_Management.IsKeyField(Integer,Integer):Boolean
- syntax:
    content: 'procedure EvaluateTextToFieldRef(InputText: Text, var FieldRef: FieldRef, ToValidate: Boolean): Boolean'
    parameters:
    - id: InputText
      parameterType:
        name: Text
        isExternal: true
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    - id: ToValidate
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: EvaluateTextToFieldRef
  uid: M:Codeunit::System#IO#Config#_Validate_Management.EvaluateTextToFieldRef(Text,FieldRef@,Boolean):Boolean
- syntax:
    content: 'procedure CheckName(FieldName: Text): Text'
    parameters:
    - id: FieldName
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: CheckName
  uid: M:Codeunit::System#IO#Config#_Validate_Management.CheckName(Text):Text
- syntax:
    content: 'procedure AddComment(var FieldRef: FieldRef): Text'
    parameters:
    - id: FieldRef
      parameterType:
        name: FieldRef
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: AddComment
  uid: M:Codeunit::System#IO#Config#_Validate_Management.AddComment(FieldRef@):Text
- syntax:
    content: 'procedure LookupTable(var ObjectID: Integer)'
    parameters:
    - id: ObjectID
      parameterType:
        name: Integer
        isExternal: true
  name: LookupTable
  uid: M:Codeunit::System#IO#Config#_Validate_Management.LookupTable(Integer@)
- syntax:
    content: 'procedure LookupPage(var ObjectID: Integer)'
    parameters:
    - id: ObjectID
      parameterType:
        name: Integer
        isExternal: true
  name: LookupPage
  uid: M:Codeunit::System#IO#Config#_Validate_Management.LookupPage(Integer@)
- syntax:
    content: 'procedure TransferRecordDefaultValues(DataTemplateCode: Code[10], var RecRef: RecordRef, CurFieldNo: Integer, CurDefaultValue: Text)'
    parameters:
    - id: DataTemplateCode
      parameterType:
        name: Code[10]
        isExternal: true
    - id: RecRef
      parameterType:
        name: RecordRef
        isExternal: true
    - id: CurFieldNo
      parameterType:
        name: Integer
        isExternal: true
    - id: CurDefaultValue
      parameterType:
        name: Text
        isExternal: true
  name: TransferRecordDefaultValues
  uid: M:Codeunit::System#IO#Config#_Validate_Management.TransferRecordDefaultValues(Code[10],RecordRef@,Integer,Text)
commentId: O:Codeunit::System#IO#Config# Validate Management
name: '"Config. Validate Management"'
uid: O:Codeunit::System#IO#Config#_Validate_Management
