### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Excel Exchange"
alId: ID 8618
namespace: System.IO
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
methods:
- syntax:
    content: 'procedure ExportExcelFromConfig(var ConfigLine: Record "Config. Line"): Text'
    parameters:
    - id: ConfigLine
      parameterType:
        name: Record "Config. Line"
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: ExportExcelFromConfig
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ExportExcelFromConfig(Config#_Line@):Text
- syntax:
    content: 'procedure ExportExcelFromPackage(ConfigPackage: Record "Config. Package"): Boolean'
    parameters:
    - id: ConfigPackage
      parameterType:
        name: Record "Config. Package"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ExportExcelFromPackage
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ExportExcelFromPackage(Config#_Package):Boolean
- syntax:
    content: 'procedure ExportExcelFromTables(var ConfigPackageTable: Record "Config. Package Table"): Boolean'
    parameters:
    - id: ConfigPackageTable
      parameterType:
        name: Record "Config. Package Table"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ExportExcelFromTables
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ExportExcelFromTables(Config#_Package_Table@):Boolean
- syntax:
    content: 'procedure ExportExcelTemplateFromTables(var ConfigPackageTable: Record "Config. Package Table"): Boolean'
    parameters:
    - id: ConfigPackageTable
      parameterType:
        name: Record "Config. Package Table"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ExportExcelTemplateFromTables
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ExportExcelTemplateFromTables(Config#_Package_Table@):Boolean
- syntax:
    content: 'procedure ExportExcel(var FileName: Text, var ConfigPackageTable: Record "Config. Package Table", ExportFromWksht: Boolean, SkipData: Boolean): Boolean'
    parameters:
    - id: FileName
      parameterType:
        name: Text
        isExternal: true
    - id: ConfigPackageTable
      parameterType:
        name: Record "Config. Package Table"
        isExternal: true
    - id: ExportFromWksht
      parameterType:
        name: Boolean
        isExternal: true
    - id: SkipData
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ExportExcel
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ExportExcel(Text@,Config#_Package_Table@,Boolean,Boolean):Boolean
- syntax:
    content: 'procedure ImportExcelFromConfig(ConfigLine: Record "Config. Line")'
    parameters:
    - id: ConfigLine
      parameterType:
        name: Record "Config. Line"
        isExternal: true
  name: ImportExcelFromConfig
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ImportExcelFromConfig(Config#_Line)
- syntax:
    content: 'procedure ImportExcelFromPackage(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ImportExcelFromPackage
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ImportExcelFromPackage:Boolean
- syntax:
    content: 'procedure ImportExcelFromSelectedPackage(PackageCode: Code[20]): Boolean'
    parameters:
    - id: PackageCode
      parameterType:
        name: Code[20]
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ImportExcelFromSelectedPackage
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ImportExcelFromSelectedPackage(Code[20]):Boolean
- syntax:
    content: 'procedure SetSelectedTables(var ConfigPackageTable: Record "Config. Package Table")'
    parameters:
    - id: ConfigPackageTable
      parameterType:
        name: Record "Config. Package Table"
        isExternal: true
  name: SetSelectedTables
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.SetSelectedTables(Config#_Package_Table@)
- syntax:
    content: 'procedure ImportExcel(TempBlob: __MissingTypeSymbol__): Boolean'
    parameters:
    - id: TempBlob
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ImportExcel
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ImportExcel(__MissingSymbol__@):Boolean
- syntax:
    content: procedure ClearOpenXmlVariables()
  name: ClearOpenXmlVariables
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.ClearOpenXmlVariables
- syntax:
    content: 'procedure CreateBook(TempBlob: __MissingTypeSymbol__)'
    parameters:
    - id: TempBlob
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: CreateBook
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.CreateBook(__MissingSymbol__@)
- syntax:
    content: 'procedure SetHideDialog(NewHideDialog: Boolean)'
    parameters:
    - id: NewHideDialog
      parameterType:
        name: Boolean
        isExternal: true
  name: SetHideDialog
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.SetHideDialog(Boolean)
- syntax:
    content: 'procedure SetFileOnServer(NewFileOnServer: Boolean)'
    parameters:
    - id: NewFileOnServer
      parameterType:
        name: Boolean
        isExternal: true
  name: SetFileOnServer
  uid: M:Codeunit::System#IO#Config#_Excel_Exchange.SetFileOnServer(Boolean)
commentId: O:Codeunit::System#IO#Config# Excel Exchange
name: '"Config. Excel Exchange"'
uid: O:Codeunit::System#IO#Config#_Excel_Exchange
