### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."SaaS Log In Management"
alId: ID 50
namespace: System.Environment
baseKind: Codeunit
kind: Codeunit
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
commentId: O:Codeunit::System#Environment#SaaS Log In Management
name: '"SaaS Log In Management"'
uid: O:Codeunit::System#Environment#SaaS_Log_In_Management
