### YamlMime:BusinessCentralApplicationObject
fqName: System.Security.AccessControl."D365 AUTOMATION"
alId: ID 5117
namespace: System.Security.AccessControl
baseKind: PermissionSet
kind: PermissionSet
parent: N:Module::Base_Application::Namespace::System.Security.AccessControl
langs:
- al
seeAlso:
- '[Permission Set](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: Assignable
  value: "True"
  promoted: false
- name: Caption
  value: Dynamics 365 Automation
  promoted: false
- name: IncludedPermissionSets
  value: '#63ca2fa44f034f2ba480172fef340d3f#"System App - Basic",#63ca2fa44f034f2ba480172fef340d3f#"Company - Edit",#63ca2fa44f034f2ba480172fef340d3f#"Permissions & Licenses - Edit",#63ca2fa44f034f2ba480172fef340d3f#"Session - Edit",#63ca2fa44f034f2ba480172fef340d3f#LOGIN'
  promoted: false
commentId: O:PermissionSet::System#Security#AccessControl#D365 AUTOMATION
name: '"D365 AUTOMATION"'
uid: O:PermissionSet::System#Security#AccessControl#D365_AUTOMATION
