### YamlMime:BusinessCentralApplicationObject
fqName: System.Security.AccessControl."Role Configuration - Edit"
alId: ID 6607
namespace: System.Security.AccessControl
baseKind: PermissionSet
kind: PermissionSet
parent: N:Module::Base_Application::Namespace::System.Security.AccessControl
langs:
- al
seeAlso:
- '[Permission Set](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-permissionset-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: Assignable
  value: "False"
  promoted: false
- name: Caption
  value: Role Configuration
  promoted: false
- name: IncludedPermissionSets
  value: '#63ca2fa44f034f2ba480172fef340d3f#"Metadata - Read",#63ca2fa44f034f2ba480172fef340d3f#"User Personalization - Edit"'
  promoted: false
commentId: O:PermissionSet::System#Security#AccessControl#Role Configuration - Edit
name: '"Role Configuration - Edit"'
uid: O:PermissionSet::System#Security#AccessControl#Role_Configuration_-_Edit
