### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."User IDs by Notification Type"
alId: ID 1511
namespace: System.Environment.Configuration
baseKind: Query
kind: Query
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Query](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-query-object)'
objectProperties:
- name: Caption
  value: User IDs by Notification Type
  promoted: false
queryColumns:
- dataItem: Notification_Entry
  columnType:
    name: Code[50]
    isExternal: true
  name: Recipient_User_ID
  uid: C:Query::System#Environment#Configuration#User_IDs_by_Notification_Type.Notification_Entry.Recipient_User_ID
- dataItem: Notification_Entry
  columnType:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
    name: System.Environment.Configuration."Notification Entry Type"
    isExternal: false
  name: Type
  uid: C:Query::System#Environment#Configuration#User_IDs_by_Notification_Type.Notification_Entry.Type
- dataItem: Notification_Entry
  columnType:
    name: Integer
    isExternal: true
  name: Count_
  uid: C:Query::System#Environment#Configuration#User_IDs_by_Notification_Type.Notification_Entry.Count_
commentId: O:Query::System#Environment#Configuration#User IDs by Notification Type
name: '"User IDs by Notification Type"'
uid: O:Query::System#Environment#Configuration#User_IDs_by_Notification_Type
