### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Inventory.Ledger."Item Application FactBox"
alId: ID 9125
namespace: Microsoft.Inventory.Ledger
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Inventory.Ledger
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Inventory#Ledger#Item_Ledger_Entry
  name: Microsoft.Inventory.Ledger."Item Ledger Entry"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Item Application
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: CardPart
  promoted: true
- name: SourceTable
  value: "32"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Inventory#Ledger#Item_Ledger_Entry
    name: Microsoft.Inventory.Ledger."Item Ledger Entry"
    isExternal: false
commentId: O:Page::Microsoft#Inventory#Ledger#Item Application FactBox
name: '"Item Application FactBox"'
uid: O:Page::Microsoft#Inventory#Ledger#Item_Application_FactBox
