### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Bank.Reconciliation."Payment Application"
alId: ID 1292
namespace: Microsoft.Bank.Reconciliation
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Bank.Reconciliation
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Bank#Reconciliation#Payment_Application_Proposal
  name: Microsoft.Bank.Reconciliation."Payment Application Proposal"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Payment Application
  promoted: false
- name: DelayedInsert
  value: "True"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Worksheet
  promoted: true
- name: SourceTable
  value: "1293"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Bank#Reconciliation#Payment_Application_Proposal
    name: Microsoft.Bank.Reconciliation."Payment Application Proposal"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: SourceTableView
  value: >-
    sorting("Sorting Order")
                          order(ascending)
  promoted: false
methods:
- syntax:
    content: 'procedure SetBankAccReconcLine(NewBankAccReconLine: Record "Bank Acc. Reconciliation Line")'
    parameters:
    - id: NewBankAccReconLine
      parameterType:
        name: Record "Bank Acc. Reconciliation Line"
        isExternal: true
  name: SetBankAccReconcLine
  uid: M:Page::Microsoft#Bank#Reconciliation#Payment_Application.SetBankAccReconcLine(Bank_Acc#_Reconciliation_Line)
commentId: O:Page::Microsoft#Bank#Reconciliation#Payment Application
name: '"Payment Application"'
uid: O:Page::Microsoft#Bank#Reconciliation#Payment_Application
