### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Inventory.Transfer."Transfer Routes"
alId: ID 5747
namespace: Microsoft.Inventory.Transfer
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Inventory.Transfer
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Inventory#Location#Location
  name: Microsoft.Inventory.Location.Location
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: transit route,in-transit
  promoted: false
- name: ApplicationArea
  value: '#Location'
  promoted: false
- name: Caption
  value: Transfer Routes
  promoted: false
- name: DataCaptionExpression
  value: "''"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: SaveValues
  value: "True"
  promoted: false
- name: SourceTable
  value: "14"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Inventory#Location#Location
    name: Microsoft.Inventory.Location.Location
    isExternal: false
- name: SourceTableView
  value: where("Use As In-Transit" = const(false))
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
commentId: O:Page::Microsoft#Inventory#Transfer#Transfer Routes
name: '"Transfer Routes"'
uid: O:Page::Microsoft#Inventory#Transfer#Transfer_Routes
