### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Integration.D365Sales."CRM BC Virtual Table Config."
alId: ID 7213
namespace: Microsoft.Integration.D365Sales
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Integration.D365Sales
langs:
- al
sourceTableType:
  name: Microsoft.Integration.D365Sales."CRM BC Virtual Table Config."
  isExternal: true
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Editable
  value: "False"
  promoted: false
- name: Caption
  value: Virtual Table Configuration - Dataverse
  promoted: false
- name: DataCaptionExpression
  value: Rec.msdyn_name
  promoted: false
- name: SourceTable
  value: "7207"
  promoted: true
- name: SourceTableTemporary
  value: "True"
  promoted: false
commentId: O:Page::Microsoft#Integration#D365Sales#CRM BC Virtual Table Config#
name: '"CRM BC Virtual Table Config."'
uid: O:Page::Microsoft#Integration#D365Sales#CRM_BC_Virtual_Table_Config#
