### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.API.Webhooks."API Routes"
alId: ID 5462
namespace: Microsoft.API.Webhooks
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.API.Webhooks
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Utilities#Name/Value_Buffer
  name: Microsoft.Utilities."Name/Value Buffer"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: APIGroup
  value: runtime
  promoted: false
- name: APIPublisher
  value: microsoft
  promoted: false
- name: DelayedInsert
  value: "True"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: EntityName
  value: apiRoutes
  promoted: false
- name: EntitySetName
  value: apiRoutes
  promoted: false
- name: Extensible
  value: "False"
  promoted: true
- name: ODataKeyFields
  value: "5"
  promoted: false
- name: PageType
  value: API
  promoted: true
- name: SourceTable
  value: "823"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Utilities#Name/Value_Buffer
    name: Microsoft.Utilities."Name/Value Buffer"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
commentId: O:Page::Microsoft#API#Webhooks#API Routes
name: '"API Routes"'
uid: O:Page::Microsoft#API#Webhooks#API_Routes
