### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Integration.Dataverse."CDS Environments"
alId: ID 7207
namespace: Microsoft.Integration.Dataverse
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Integration.Dataverse
langs:
- al
sourceTableType:
  name: Microsoft.Integration.Dataverse."CDS Environment"
  isExternal: true
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Extensible
  value: "False"
  promoted: true
- name: Caption
  value: Dataverse User Environments
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "7202"
  promoted: true
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: SourceTableView
  value: sorting("Environment Name")
  promoted: false
commentId: O:Page::Microsoft#Integration#Dataverse#CDS Environments
name: '"CDS Environments"'
uid: O:Page::Microsoft#Integration#Dataverse#CDS_Environments
