### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.VAT.Reporting."VAT Reports Configuration"
alId: ID 746
namespace: Microsoft.Finance.VAT.Reporting
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.VAT.Reporting
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration
  name: Microsoft.Finance.VAT.Reporting."VAT Reports Configuration"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#VAT'
  promoted: false
- name: Caption
  value: VAT Reports Configuration
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "746"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration
    name: Microsoft.Finance.VAT.Reporting."VAT Reports Configuration"
    isExternal: false
- name: UsageCategory
  value: Administration
  promoted: false
commentId: O:Page::Microsoft#Finance#VAT#Reporting#VAT Reports Configuration
name: '"VAT Reports Configuration"'
uid: O:Page::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration
