### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.ReceivablesPayables."Post Application"
alId: ID 579
namespace: Microsoft.Finance.ReceivablesPayables
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.ReceivablesPayables
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Post Application
  promoted: false
- name: PageType
  value: StandardDialog
  promoted: true
methods:
- syntax:
    content: 'procedure SetParameters(NewApplyUnapplyParameters: Record "Apply Unapply Parameters" temporary)'
    parameters:
    - id: NewApplyUnapplyParameters
      parameterType:
        name: Record "Apply Unapply Parameters" temporary
        isExternal: true
  name: SetParameters
  uid: M:Page::Microsoft#Finance#ReceivablesPayables#Post_Application.SetParameters(Apply_Unapply_Parameters)
- syntax:
    content: 'procedure GetParameters(var NewApplyUnapplyParameters: Record "Apply Unapply Parameters" temporary)'
    parameters:
    - id: NewApplyUnapplyParameters
      parameterType:
        name: Record "Apply Unapply Parameters" temporary
        isExternal: true
  name: GetParameters
  uid: M:Page::Microsoft#Finance#ReceivablesPayables#Post_Application.GetParameters(Apply_Unapply_Parameters@)
commentId: O:Page::Microsoft#Finance#ReceivablesPayables#Post Application
name: '"Post Application"'
uid: O:Page::Microsoft#Finance#ReceivablesPayables#Post_Application
