### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Sales.Reminder."Select Rem. Terms Automation"
alId: ID 6754
namespace: Microsoft.Sales.Reminder
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Sales.Reminder
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Sales#Reminder#Reminder_Terms
  name: Microsoft.Sales.Reminder."Reminder Terms"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: StandardDialog
  promoted: true
- name: SourceTable
  value: "292"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Sales#Reminder#Reminder_Terms
    name: Microsoft.Sales.Reminder."Reminder Terms"
    isExternal: false
- name: Caption
  value: Select reminder terms
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
commentId: O:Page::Microsoft#Sales#Reminder#Select Rem# Terms Automation
name: '"Select Rem. Terms Automation"'
uid: O:Page::Microsoft#Sales#Reminder#Select_Rem#_Terms_Automation
