### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.Dimension."Dim. Values per Account"
alId: ID 545
namespace: Microsoft.Finance.Dimension
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.Dimension
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Finance#Dimension#Default_Dimension
  name: Microsoft.Finance.Dimension."Default Dimension"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Dimension Values per Account
  promoted: false
- name: DataCaptionFields
  value: "3"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "352"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Finance#Dimension#Default_Dimension
    name: Microsoft.Finance.Dimension."Default Dimension"
    isExternal: false
- name: SourceTableView
  value: where("Value Posting" = const("Code Mandatory"))
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
commentId: O:Page::Microsoft#Finance#Dimension#Dim# Values per Account
name: '"Dim. Values per Account"'
uid: O:Page::Microsoft#Finance#Dimension#Dim#_Values_per_Account
