### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Inventory.Item.Attribute."Item Attribute Values"
alId: ID 7501
namespace: Microsoft.Inventory.Item.Attribute
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Inventory.Item.Attribute
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Inventory#Item#Attribute#Item_Attribute_Value
  name: Microsoft.Inventory.Item.Attribute."Item Attribute Value"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Item Attribute Values
  promoted: false
- name: DataCaptionFields
  value: "1"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "7501"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Inventory#Item#Attribute#Item_Attribute_Value
    name: Microsoft.Inventory.Item.Attribute."Item Attribute Value"
    isExternal: false
commentId: O:Page::Microsoft#Inventory#Item#Attribute#Item Attribute Values
name: '"Item Attribute Values"'
uid: O:Page::Microsoft#Inventory#Item#Attribute#Item_Attribute_Values
