### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Service.Resources."Resource Capacity Settings"
alId: ID 6013
namespace: Microsoft.Service.Resources
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Service.Resources
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Projects#Resources#Resource#Resource
  name: Microsoft.Projects.Resources.Resource.Resource
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Resource Capacity Settings
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: SourceTable
  value: "156"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Projects#Resources#Resource#Resource
    name: Microsoft.Projects.Resources.Resource.Resource
    isExternal: false
commentId: O:Page::Microsoft#Service#Resources#Resource Capacity Settings
name: '"Resource Capacity Settings"'
uid: O:Page::Microsoft#Service#Resources#Resource_Capacity_Settings
