### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Bank.Reconciliation."Payment Application Review"
alId: ID 1287
namespace: Microsoft.Bank.Reconciliation
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Bank.Reconciliation
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Bank#Reconciliation#Bank_Acc#_Reconciliation_Line
  name: Microsoft.Bank.Reconciliation."Bank Acc. Reconciliation Line"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: Card
  promoted: true
- name: SourceTable
  value: "274"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Bank#Reconciliation#Bank_Acc#_Reconciliation_Line
    name: Microsoft.Bank.Reconciliation."Bank Acc. Reconciliation Line"
    isExternal: false
- name: RefreshOnActivate
  value: "True"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: DataCaptionExpression
  value: "''"
  promoted: false
commentId: O:Page::Microsoft#Bank#Reconciliation#Payment Application Review
name: '"Payment Application Review"'
uid: O:Page::Microsoft#Bank#Reconciliation#Payment_Application_Review
