### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Inventory.Ledger."Item Application Entries"
alId: ID 506
namespace: Microsoft.Inventory.Ledger
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Inventory.Ledger
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Inventory#Ledger#Item_Application_Entry
  name: Microsoft.Inventory.Ledger."Item Application Entry"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Item Application Entries
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "339"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Inventory#Ledger#Item_Application_Entry
    name: Microsoft.Inventory.Ledger."Item Application Entry"
    isExternal: false
commentId: O:Page::Microsoft#Inventory#Ledger#Item Application Entries
name: '"Item Application Entries"'
uid: O:Page::Microsoft#Inventory#Ledger#Item_Application_Entries
