### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.VAT.Registration."VAT Registration Config"
alId: ID 248
namespace: Microsoft.Finance.VAT.Registration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.VAT.Registration
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config
  name: Microsoft.Finance.VAT.Registration."VAT Reg. No. Srv Config"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: EU VAT Registration No. Validation Service Setup
  promoted: false
- name: DataCaptionExpression
  value: "''"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: PopulateAllFields
  value: "False"
  promoted: false
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: "248"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config
    name: Microsoft.Finance.VAT.Registration."VAT Reg. No. Srv Config"
    isExternal: false
- name: UsageCategory
  value: Administration
  promoted: false
commentId: O:Page::Microsoft#Finance#VAT#Registration#VAT Registration Config
name: '"VAT Registration Config"'
uid: O:Page::Microsoft#Finance#VAT#Registration#VAT_Registration_Config
