### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.Dimension.Correction."Dim Correction Settings"
alId: ID 2582
namespace: Microsoft.Finance.Dimension.Correction
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.Dimension.Correction
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: ListPlus
  promoted: true
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: Caption
  value: Dimension Correction Settings
  promoted: false
- name: AdditionalSearchTerms
  value: dimension correction setup
  promoted: false
commentId: O:Page::Microsoft#Finance#Dimension#Correction#Dim Correction Settings
name: '"Dim Correction Settings"'
uid: O:Page::Microsoft#Finance#Dimension#Correction#Dim_Correction_Settings
