### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Bank.Reconciliation."Payment Application Rules"
alId: ID 1252
namespace: Microsoft.Bank.Reconciliation
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Bank.Reconciliation
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Rule
  name: Microsoft.Bank.Reconciliation."Bank Pmt. Appl. Rule"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: payment matching rules,automatic payment application
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Payment Application Rules
  promoted: false
- name: DelayedInsert
  value: "True"
  promoted: false
- name: PageType
  value: Worksheet
  promoted: true
- name: SourceTable
  value: "1252"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Rule
    name: Microsoft.Bank.Reconciliation."Bank Pmt. Appl. Rule"
    isExternal: false
- name: UsageCategory
  value: Tasks
  promoted: false
commentId: O:Page::Microsoft#Bank#Reconciliation#Payment Application Rules
name: '"Payment Application Rules"'
uid: O:Page::Microsoft#Bank#Reconciliation#Payment_Application_Rules
