### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Inventory.Ledger."Application Worksheet"
alId: ID 521
namespace: Microsoft.Inventory.Ledger
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::Microsoft.Inventory.Ledger
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Inventory#Ledger#Item_Ledger_Entry
  name: Microsoft.Inventory.Ledger."Item Ledger Entry"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: undo application
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Application Worksheet
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "True"
  promoted: false
- name: PageType
  value: Worksheet
  promoted: true
- name: SaveValues
  value: "True"
  promoted: false
- name: SourceTable
  value: "32"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Inventory#Ledger#Item_Ledger_Entry
    name: Microsoft.Inventory.Ledger."Item Ledger Entry"
    isExternal: false
- name: UsageCategory
  value: Tasks
  promoted: false
methods:
- syntax:
    content: 'procedure SetRecordToShow(RecordToSet: Record "Item Ledger Entry")'
    parameters:
    - id: RecordToSet
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
  name: SetRecordToShow
  uid: M:Page::Microsoft#Inventory#Ledger#Application_Worksheet.SetRecordToShow(Item_Ledger_Entry)
commentId: O:Page::Microsoft#Inventory#Ledger#Application Worksheet
name: '"Application Worksheet"'
uid: O:Page::Microsoft#Inventory#Ledger#Application_Worksheet
