### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Data Sync Status"
alId: ID 6250
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: Caption
  value: Data Sync Status
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Document
  promoted: true
- name: UsageCategory
  value: Administration
  promoted: false
methods:
- syntax:
    content: procedure ParsePosting()
  name: ParsePosting
  uid: M:Page::System#Environment#Configuration#Data_Sync_Status.ParsePosting
- syntax:
    content: 'procedure SetMigrationVisibility(IsMigration: Boolean)'
    parameters:
    - id: IsMigration
      parameterType:
        name: Boolean
        isExternal: true
  name: SetMigrationVisibility
  uid: M:Page::System#Environment#Configuration#Data_Sync_Status.SetMigrationVisibility(Boolean)
commentId: O:Page::System#Environment#Configuration#Data Sync Status
name: '"Data Sync Status"'
uid: O:Page::System#Environment#Configuration#Data_Sync_Status
