### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Sent Notification Entries"
alId: ID 1514
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Sent_Notification_Entry
  name: System.Environment.Configuration."Sent Notification Entry"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Suite'
  promoted: false
- name: Caption
  value: Sent Notification Entries
  promoted: false
- name: DeleteAllowed
  value: "True"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "1514"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Sent_Notification_Entry
    name: System.Environment.Configuration."Sent Notification Entry"
    isExternal: false
- name: UsageCategory
  value: Lists
  promoted: false
commentId: O:Page::System#Environment#Configuration#Sent Notification Entries
name: '"Sent Notification Entries"'
uid: O:Page::System#Environment#Configuration#Sent_Notification_Entries
