### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config Templates"
alId: ID 1340
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Template_Header
  name: System.IO."Config. Template Header"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Templates
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8618"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Template_Header
    name: System.IO."Config. Template Header"
    isExternal: false
- name: UsageCategory
  value: Lists
  promoted: false
methods:
- syntax:
    content: procedure SetNewMode()
  name: SetNewMode
  uid: M:Page::System#IO#Config_Templates.SetNewMode
commentId: O:Page::System#IO#Config Templates
name: '"Config Templates"'
uid: O:Page::System#IO#Config_Templates
