### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Personalized Pages"
alId: ID 9200
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Personalized Pages
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: ""
  promoted: true
- name: UsageCategory
  value: Lists
  promoted: false
- name: AdditionalSearchTerms
  value: delete user personalization,User Page Personalizations,User Page Personalization List
  promoted: false
methods:
- syntax:
    content: 'procedure SetUserID(UserID: Guid)'
    parameters:
    - id: UserID
      parameterType:
        name: Guid
        isExternal: true
  name: SetUserID
  uid: M:Page::System#Environment#Configuration#Personalized_Pages.SetUserID(Guid)
commentId: O:Page::System#Environment#Configuration#Personalized Pages
name: '"Personalized Pages"'
uid: O:Page::System#Environment#Configuration#Personalized_Pages
