### YamlMime:BusinessCentralApplicationObject
fqName: System.Integration."Data Migration Settings"
alId: ID 1807
namespace: System.Integration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Integration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Integration#Data_Migration_Setup
  name: System.Integration."Data Migration Setup"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AccessByPermission
  value: TableData "Data Migration Setup" = R
  promoted: false
- name: AdditionalSearchTerms
  value: implementation settings,data setup settings,quickbooks settings
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Data Migration Settings
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: SourceTable
  value: "1806"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Integration#Data_Migration_Setup
    name: System.Integration."Data Migration Setup"
    isExternal: false
- name: UsageCategory
  value: Administration
  promoted: false
commentId: O:Page::System#Integration#Data Migration Settings
name: '"Data Migration Settings"'
uid: O:Page::System#Integration#Data_Migration_Settings
