### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Control Add-ins"
alId: ID 9820
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Control Add-ins
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: ""
  promoted: true
- name: UsageCategory
  value: Lists
  promoted: false
commentId: O:Page::System#Environment#Configuration#Control Add-ins
name: '"Control Add-ins"'
uid: O:Page::System#Environment#Configuration#Control_Add-ins
