### YamlMime:BusinessCentralApplicationObject
fqName: System.Automation."Flow Service Configuration"
alId: ID 6415
namespace: System.Automation
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Automation
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Automation#Flow_Service_Configuration
  name: System.Automation."Flow Service Configuration"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Power Automate Service Configuration
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: PageType
  value: NavigatePage
  promoted: true
- name: Permissions
  value: TableData "Flow Service Configuration" = rimd
  promoted: false
- name: SourceTable
  value: "1543"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Automation#Flow_Service_Configuration
    name: System.Automation."Flow Service Configuration"
    isExternal: false
commentId: O:Page::System#Automation#Flow Service Configuration
name: '"Flow Service Configuration"'
uid: O:Page::System#Automation#Flow_Service_Configuration
