### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Tables"
alId: ID 8630
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Line
  name: System.IO."Config. Line"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Tables
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8622"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Line
    name: System.IO."Config. Line"
    isExternal: false
- name: SourceTableView
  value: >-
    sorting("Line Type", "Parent Line No.")
                          where("Line Type" = const(Table))
  promoted: false
commentId: O:Page::System#IO#Config# Tables
name: '"Config. Tables"'
uid: O:Page::System#IO#Config#_Tables
