### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Setup"
alId: ID 1512
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Notification_Setup
  name: System.Environment.Configuration."Notification Setup"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Suite'
  promoted: false
- name: Caption
  value: Workflow Notification Setup
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: RefreshOnActivate
  value: "True"
  promoted: false
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: "1512"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Notification_Setup
    name: System.Environment.Configuration."Notification Setup"
    isExternal: false
- name: UsageCategory
  value: Administration
  promoted: false
commentId: O:Page::System#Environment#Configuration#Notification Setup
name: '"Notification Setup"'
uid: O:Page::System#Environment#Configuration#Notification_Setup
