### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Help And Chart Wrapper"
alId: ID 1392
namespace: System.Environment
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Business Performance
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: PageType
  value: CardPart
  promoted: true
commentId: O:Page::System#Environment#Help And Chart Wrapper
name: '"Help And Chart Wrapper"'
uid: O:Page::System#Environment#Help_And_Chart_Wrapper
