### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."MS 365 License Setup Wizard"
alId: ID 1978
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Set up access with Microsoft 365 licenses
  promoted: false
- name: Extensible
  value: "False"
  promoted: true
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: PageType
  value: NavigatePage
  promoted: true
- name: ShowFilter
  value: "False"
  promoted: false
- name: Permissions
  value: >-
    tabledata Company = r,
                      tabledata "Media Resources" = r,
                      tabledata "Media Repository" = r,
                      tabledata "Permission Set In Plan Buffer" = r,
                      tabledata Item = r
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: AdditionalSearchTerms
  value: Teams, tabs, M365, Microsoft, collaboration, Office, channel, free, access, free access, freemium, Teams setup, teams access
  promoted: false
- name: AccessByPermission
  value: tabledata "All Profile" = IMD
  promoted: false
commentId: O:Page::System#Environment#Configuration#MS 365 License Setup Wizard
name: '"MS 365 License Setup Wizard"'
uid: O:Page::System#Environment#Configuration#MS_365_License_Setup_Wizard
