### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Card"
alId: ID 9170
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Profile (Role)
  promoted: false
- name: DataCaptionExpression
  value: Rec.Caption
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: SourceTable
  value: ""
  promoted: true
- name: DelayedInsert
  value: "True"
  promoted: false
commentId: O:Page::System#Environment#Configuration#Profile Card
name: '"Profile Card"'
uid: O:Page::System#Environment#Configuration#Profile_Card
