### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Data Upgrade Overview"
alId: ID 2845
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Foundation#Navigate#Document_Entry
  name: Microsoft.Foundation.Navigate."Document Entry"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Data Update Overview
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "265"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Foundation#Navigate#Document_Entry
    name: Microsoft.Foundation.Navigate."Document Entry"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
methods:
- syntax:
    content: 'procedure Set(var TempDocumentEntry: Record "Document Entry" temporary)'
    parameters:
    - id: TempDocumentEntry
      parameterType:
        name: Record "Document Entry" temporary
        isExternal: true
  name: Set
  uid: M:Page::System#Environment#Configuration#Data_Upgrade_Overview.Set(Document_Entry@)
commentId: O:Page::System#Environment#Configuration#Data Upgrade Overview
name: '"Data Upgrade Overview"'
uid: O:Page::System#Environment#Configuration#Data_Upgrade_Overview
