### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Database Access Intent List"
alId: ID 9880
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: List
  promoted: true
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: AdditionalSearchTerms
  value: Replicated database,Read Only access
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: Permissions
  value: TableData "Object Access Intent Override" = rimd
  promoted: false
- name: SourceTable
  value: ""
  promoted: true
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
commentId: O:Page::System#Environment#Configuration#Database Access Intent List
name: '"Database Access Intent List"'
uid: O:Page::System#Environment#Configuration#Database_Access_Intent_List
