### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile List"
alId: ID 9171
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: users,roles,role centers,personalization,customization
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Profiles (Roles)
  promoted: false
- name: CardPageID
  value: Profile Card
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Profile_Card
    name: System.Environment.Configuration."Profile Card"
    isExternal: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: RefreshOnActivate
  value: "True"
  promoted: false
- name: SourceTable
  value: ""
  promoted: true
- name: UsageCategory
  value: Lists
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: SourceTableView
  value: sorting(Caption)
  promoted: false
commentId: O:Page::System#Environment#Configuration#Profile List
name: '"Profile List"'
uid: O:Page::System#Environment#Configuration#Profile_List
