### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Questions FactBox"
alId: ID 8633
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Question
  name: System.IO."Config. Question"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Configuration Questions
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: ListPart
  promoted: true
- name: SourceTable
  value: "8612"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Question
    name: System.IO."Config. Question"
    isExternal: false
commentId: O:Page::System#IO#Config# Questions FactBox
name: '"Config. Questions FactBox"'
uid: O:Page::System#IO#Config#_Questions_FactBox
