### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Entries"
alId: ID 1511
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Notification_Entry
  name: System.Environment.Configuration."Notification Entry"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Suite'
  promoted: false
- name: Caption
  value: Notification Entries
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "1511"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Notification_Entry
    name: System.Environment.Configuration."Notification Entry"
    isExternal: false
- name: SourceTableView
  value: >-
    sorting("Created Date-Time")
                          order(ascending)
  promoted: false
- name: UsageCategory
  value: Lists
  promoted: false
commentId: O:Page::System#Environment#Configuration#Notification Entries
name: '"Notification Entries"'
uid: O:Page::System#Environment#Configuration#Notification_Entries
