### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Related Fields"
alId: ID 8622
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Related_Field
  name: System.IO."Config. Related Field"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Related Fields
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8624"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Related_Field
    name: System.IO."Config. Related Field"
    isExternal: false
commentId: O:Page::System#IO#Config# Related Fields
name: '"Config. Related Fields"'
uid: O:Page::System#IO#Config#_Related_Fields
