### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Customization List"
alId: ID 9190
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Customized Pages
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: UsageCategory
  value: Lists
  promoted: false
- name: SourceTable
  value: ""
  promoted: true
- name: AdditionalSearchTerms
  value: Page customizations,Profile configurations,Profile customizations,Role customizations
  promoted: false
commentId: O:Page::System#Environment#Configuration#Profile Customization List
name: '"Profile Customization List"'
uid: O:Page::System#Environment#Configuration#Profile_Customization_List
