### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Related Tables FactBox"
alId: ID 8635
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Related_Table
  name: System.IO."Config. Related Table"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Related Tables
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: ListPart
  promoted: true
- name: SourceTable
  value: "8625"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Related_Table
    name: System.IO."Config. Related Table"
    isExternal: false
commentId: O:Page::System#IO#Config# Related Tables FactBox
name: '"Config. Related Tables FactBox"'
uid: O:Page::System#IO#Config#_Related_Tables_FactBox
