### YamlMime:BusinessCentralApplicationObject
fqName: System.Apps."Teams Individual Deployment"
alId: ID 1834
namespace: System.Apps
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Apps
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Get the Business Central App for Teams
  promoted: false
- name: PageType
  value: NavigatePage
  promoted: true
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: UsageCategory
  value: Tasks
  promoted: false
- name: AdditionalSearchTerms
  value: Add-in, AddIn, M365, Microsoft 365, Addon, Install Teams, Set up Teams
  promoted: false
commentId: O:Page::System#Apps#Teams Individual Deployment
name: '"Teams Individual Deployment"'
uid: O:Page::System#Apps#Teams_Individual_Deployment
