### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Template Subform"
alId: ID 8619
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Template_Line
  name: System.IO."Config. Template Line"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AutoSplitKey
  value: "True"
  promoted: false
- name: Caption
  value: Lines
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: PageType
  value: ListPart
  promoted: true
- name: SourceTable
  value: "8619"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Template_Line
    name: System.IO."Config. Template Line"
    isExternal: false
commentId: O:Page::System#IO#Config# Template Subform
name: '"Config. Template Subform"'
uid: O:Page::System#IO#Config#_Template_Subform
