### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."EE Notification List"
alId: ID 3301
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: Caption
  value: Business Event Notifications
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: PopulateAllFields
  value: "True"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: SourceTable
  value: ""
  promoted: true
commentId: O:Page::System#Environment#Configuration#EE Notification List
name: '"EE Notification List"'
uid: O:Page::System#Environment#Configuration#EE_Notification_List
