### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Copy Profile"
alId: ID 9175
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Copy Profile
  promoted: false
- name: Editable
  value: "True"
  promoted: false
- name: PageType
  value: StandardDialog
  promoted: true
methods:
- syntax:
    content: 'procedure SetSourceAllProfile(AllProfile: __MissingTypeSymbol__)'
    parameters:
    - id: AllProfile
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: SetSourceAllProfile
  uid: M:Page::System#Environment#Configuration#Copy_Profile.SetSourceAllProfile(__MissingSymbol__)
- syntax:
    content: 'procedure GetDestinationAllProfile(AllProfile: __MissingTypeSymbol__)'
    parameters:
    - id: AllProfile
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: GetDestinationAllProfile
  uid: M:Page::System#Environment#Configuration#Copy_Profile.GetDestinationAllProfile(__MissingSymbol__@)
commentId: O:Page::System#Environment#Configuration#Copy Profile
name: '"Copy Profile"'
uid: O:Page::System#Environment#Configuration#Copy_Profile
