### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Report Res. Govern. Settings"
alId: ID 9882
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Report Limits and Settings
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: AdditionalSearchTerms
  value: Report Timeout, timeout, format region
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: Permissions
  value: Tabledata "Report Settings Override" = rimd
  promoted: false
- name: SourceTable
  value: ""
  promoted: true
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "True"
  promoted: false
commentId: O:Page::System#Environment#Configuration#Report Res# Govern# Settings
name: '"Report Res. Govern. Settings"'
uid: O:Page::System#Environment#Configuration#Report_Res#_Govern#_Settings
