### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."AAD Application Card"
alId: ID 9861
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#AAD_Application
  name: System.Environment.Configuration."AAD Application"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Microsoft Entra Application Card
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: RefreshOnActivate
  value: "True"
  promoted: false
- name: SourceTable
  value: "9012"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#AAD_Application
    name: System.Environment.Configuration."AAD Application"
    isExternal: false
commentId: O:Page::System#Environment#Configuration#AAD Application Card
name: '"AAD Application Card"'
uid: O:Page::System#Environment#Configuration#AAD_Application_Card
