### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Packages"
alId: ID 8615
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package
  name: System.IO."Config. Package"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: rapidstart rapid start implementation migrate setup packages
  promoted: false
- name: ApplicationArea
  value: '#Suite'
  promoted: false
- name: Caption
  value: Configuration Packages
  promoted: false
- name: CardPageID
  value: Config. Package Card
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Package_Card
    name: System.IO."Config. Package Card"
    isExternal: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8623"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package
    name: System.IO."Config. Package"
    isExternal: false
- name: UsageCategory
  value: Lists
  promoted: false
commentId: O:Page::System#IO#Config# Packages
name: '"Config. Packages"'
uid: O:Page::System#IO#Config#_Packages
