### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Fields"
alId: ID 8624
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Field
  name: System.IO."Config. Package Field"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Package Fields
  promoted: false
- name: DataCaptionExpression
  value: FormCaption()
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8616"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Field
    name: System.IO."Config. Package Field"
    isExternal: false
- name: SourceTableView
  value: sorting("Package Code", "Table ID", "Processing Order")
  promoted: false
commentId: O:Page::System#IO#Config# Package Fields
name: '"Config. Package Fields"'
uid: O:Page::System#IO#Config#_Package_Fields
