### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Import Wizard"
alId: ID 9199
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Profile_Import
  name: System.Environment.Configuration."Profile Import"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Import profiles
  promoted: false
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: PageType
  value: NavigatePage
  promoted: true
- name: SourceTable
  value: "9171"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Profile_Import
    name: System.Environment.Configuration."Profile Import"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: AccessByPermission
  value: TableData "Profile Designer Diagnostic" = I
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
methods:
- syntax:
    content: 'procedure SetRecords(var TempProfileImport: Record "Profile Import" temporary)'
    parameters:
    - id: TempProfileImport
      parameterType:
        name: Record "Profile Import" temporary
        isExternal: true
  name: SetRecords
  uid: M:Page::System#Environment#Configuration#Profile_Import_Wizard.SetRecords(Profile_Import@)
commentId: O:Page::System#Environment#Configuration#Profile Import Wizard
name: '"Profile Import Wizard"'
uid: O:Page::System#Environment#Configuration#Profile_Import_Wizard
