### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Configuration Package Files"
alId: ID 1800
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Configuration Package Files
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: ""
  promoted: true
commentId: O:Page::System#IO#Configuration Package Files
name: '"Configuration Package Files"'
uid: O:Page::System#IO#Configuration_Package_Files
