### YamlMime:BusinessCentralApplicationObject
fqName: System.Automation."Automate Environment Picker"
alId: ID 1837
namespace: System.Automation
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Automation
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Automation#Flow_User_Environment_Buffer
  name: System.Automation."Flow User Environment Buffer"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Power Automate Environment
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: Extensible
  value: "False"
  promoted: true
- name: PageType
  value: NavigatePage
  promoted: true
- name: ShowFilter
  value: "False"
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: SourceTable
  value: "1544"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Automation#Flow_User_Environment_Buffer
    name: System.Automation."Flow User Environment Buffer"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: AdditionalSearchTerms
  value: Power Automate, install automate, environment, change environment, pick environment
  promoted: false
commentId: O:Page::System#Automation#Automate Environment Picker
name: '"Automate Environment Picker"'
uid: O:Page::System#Automation#Automate_Environment_Picker
