### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Subform"
alId: ID 8625
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Table
  name: System.IO."Config. Package Table"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Tables
  promoted: false
- name: DelayedInsert
  value: "True"
  promoted: false
- name: PageType
  value: ListPart
  promoted: true
- name: SourceTable
  value: "8613"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Table
    name: System.IO."Config. Package Table"
    isExternal: false
commentId: O:Page::System#IO#Config# Package Subform
name: '"Config. Package Subform"'
uid: O:Page::System#IO#Config#_Package_Subform
