### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Experience Tiers"
alId: ID 9195
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Experience_Tier_Buffer
  name: System.Environment.Configuration."Experience Tier Buffer"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Experience Tiers
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "9177"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Experience_Tier_Buffer
    name: System.Environment.Configuration."Experience Tier Buffer"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
commentId: O:Page::System#Environment#Configuration#Experience Tiers
name: '"Experience Tiers"'
uid: O:Page::System#Environment#Configuration#Experience_Tiers
