### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Extension List"
alId: ID 9169
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Profile Extensions
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: ""
  promoted: true
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
commentId: O:Page::System#Environment#Configuration#Profile Extension List
name: '"Profile Extension List"'
uid: O:Page::System#Environment#Configuration#Profile_Extension_List
