### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Field Mapping"
alId: ID 8636
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Field_Map
  name: System.IO."Config. Field Map"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Field Mapping
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8629"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Field_Map
    name: System.IO."Config. Field Map"
    isExternal: false
commentId: O:Page::System#IO#Config# Field Mapping
name: '"Config. Field Mapping"'
uid: O:Page::System#IO#Config#_Field_Mapping
