### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Designer Diagnostics"
alId: ID 9197
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Profile_Designer_Diagnostic
  name: System.Environment.Configuration."Profile Designer Diagnostic"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: ListPart
  promoted: true
- name: Caption
  value: Profile Designer Diagnostics
  promoted: false
- name: SourceTable
  value: "9197"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Profile_Designer_Diagnostic
    name: System.Environment.Configuration."Profile Designer Diagnostic"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
methods:
- syntax:
    content: 'procedure SetRecords(ImportID: Guid)'
    parameters:
    - id: ImportID
      parameterType:
        name: Guid
        isExternal: true
  name: SetRecords
  uid: M:Page::System#Environment#Configuration#Profile_Designer_Diagnostics.SetRecords(Guid)
commentId: O:Page::System#Environment#Configuration#Profile Designer Diagnostics
name: '"Profile Designer Diagnostics"'
uid: O:Page::System#Environment#Configuration#Profile_Designer_Diagnostics
