### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Import Preview"
alId: ID 8617
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Table
  name: System.IO."Config. Package Table"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Package Import Preview
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: "8613"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Table
    name: System.IO."Config. Package Table"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
methods:
- syntax:
    content: 'procedure SetData(NewSelectedPackageCode: Code[20], var TempConfigPackageTable: Record "Config. Package Table" temporary)'
    parameters:
    - id: NewSelectedPackageCode
      parameterType:
        name: Code[20]
        isExternal: true
    - id: TempConfigPackageTable
      parameterType:
        name: Record "Config. Package Table" temporary
        isExternal: true
  name: SetData
  uid: M:Page::System#IO#Config#_Package_Import_Preview.SetData(Code[20],Config#_Package_Table@)
- syntax:
    content: 'procedure IsImportConfirmed(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsImportConfirmed
  uid: M:Page::System#IO#Config#_Package_Import_Preview.IsImportConfirmed:Boolean
commentId: O:Page::System#IO#Config# Package Import Preview
name: '"Config. Package Import Preview"'
uid: O:Page::System#IO#Config#_Package_Import_Preview
