### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Filters"
alId: ID 8623
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Filter
  name: System.IO."Config. Package Filter"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Package Filters
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8626"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Filter
    name: System.IO."Config. Package Filter"
    isExternal: false
commentId: O:Page::System#IO#Config# Package Filters
name: '"Config. Package Filters"'
uid: O:Page::System#IO#Config#_Package_Filters
