### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Records"
alId: ID 8626
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Record
  name: System.IO."Config. Package Record"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Package Records
  promoted: false
- name: DataCaptionExpression
  value: FormCaption
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Worksheet
  promoted: true
- name: SourceTable
  value: "8614"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Record
    name: System.IO."Config. Package Record"
    isExternal: false
methods:
- syntax:
    content: 'procedure Load(NewMatrixColumnCaptions: array[1000] of Text[100], FormCaptionIn: Text[1024], PackageCode1: Code[20], TableNo1: Integer, ShowDim1: Boolean)'
    parameters:
    - id: NewMatrixColumnCaptions
      parameterType:
        name: array[1000] of Text[100]
        isExternal: true
    - id: FormCaptionIn
      parameterType:
        name: Text[1024]
        isExternal: true
    - id: PackageCode1
      parameterType:
        name: Code[20]
        isExternal: true
    - id: TableNo1
      parameterType:
        name: Integer
        isExternal: true
    - id: ShowDim1
      parameterType:
        name: Boolean
        isExternal: true
  name: Load
  uid: M:Page::System#IO#Config#_Package_Records.Load(Text[100][],Text[1024],Code[20],Integer,Boolean)
- syntax:
    content: 'procedure SetErrorFieldNo(FieldNo: Integer)'
    parameters:
    - id: FieldNo
      parameterType:
        name: Integer
        isExternal: true
  name: SetErrorFieldNo
  uid: M:Page::System#IO#Config#_Package_Records.SetErrorFieldNo(Integer)
commentId: O:Page::System#IO#Config# Package Records
name: '"Config. Package Records"'
uid: O:Page::System#IO#Config#_Package_Records
