### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Selection"
alId: ID 8628
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Selection
  name: System.IO."Config. Selection"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Selection
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8621"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Selection
    name: System.IO."Config. Selection"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: SourceTableView
  value: sorting("Vertical Sorting")
  promoted: false
methods:
- syntax:
    content: 'procedure Set(var TempConfigSelection: Record "Config. Selection" temporary)'
    parameters:
    - id: TempConfigSelection
      parameterType:
        name: Record "Config. Selection" temporary
        isExternal: true
  name: Set
  uid: M:Page::System#IO#Config#_Selection.Set(Config#_Selection@)
- syntax:
    content: 'procedure Get(var TempConfigSelection: Record "Config. Selection" temporary): Integer'
    parameters:
    - id: TempConfigSelection
      parameterType:
        name: Record "Config. Selection" temporary
        isExternal: true
    return:
      returnType:
        name: Integer
        isExternal: true
  name: Get
  uid: M:Page::System#IO#Config#_Selection.Get(Config#_Selection@):Integer
commentId: O:Page::System#IO#Config# Selection
name: '"Config. Selection"'
uid: O:Page::System#IO#Config#_Selection
