### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Import Diagnostics"
alId: ID 9196
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Tooling#Designer_Diagnostic
  name: System.Tooling."Designer Diagnostic"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "9175"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Tooling#Designer_Diagnostic
    name: System.Tooling."Designer Diagnostic"
    isExternal: false
- name: SourceTableView
  value: where(Severity = filter(<> Hidden))
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: Caption
  value: Diagnostics
  promoted: false
commentId: O:Page::System#Environment#Configuration#Profile Import Diagnostics
name: '"Profile Import Diagnostics"'
uid: O:Page::System#Environment#Configuration#Profile_Import_Diagnostics
