### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Card"
alId: ID 8614
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package
  name: System.IO."Config. Package"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Package Card
  promoted: false
- name: PageType
  value: Document
  promoted: true
- name: SourceTable
  value: "8623"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package
    name: System.IO."Config. Package"
    isExternal: false
commentId: O:Page::System#IO#Config# Package Card
name: '"Config. Package Card"'
uid: O:Page::System#IO#Config#_Package_Card
