### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Table FactBox"
alId: ID 8634
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Table
  name: System.IO."Config. Package Table"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Package Table
  promoted: false
- name: PageType
  value: CardPart
  promoted: true
- name: SourceTable
  value: "8613"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Table
    name: System.IO."Config. Package Table"
    isExternal: false
commentId: O:Page::System#IO#Config# Package Table FactBox
name: '"Config. Package Table FactBox"'
uid: O:Page::System#IO#Config#_Package_Table_FactBox
