### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Areas"
alId: ID 8631
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Line
  name: System.IO."Config. Line"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Areas
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: ListPart
  promoted: true
- name: SourceTable
  value: "8622"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Line
    name: System.IO."Config. Line"
    isExternal: false
- name: SourceTableView
  value: where("Line Type" = filter(<> Table))
  promoted: false
commentId: O:Page::System#IO#Config# Areas
name: '"Config. Areas"'
uid: O:Page::System#IO#Config#_Areas
