### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Import Data"
alId: ID 9900
namespace: System.Environment
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Import from a Data File
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: Editable
  value: "True"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: StandardDialog
  promoted: true
- name: SourceTable
  value: ""
  promoted: true
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: UsageCategory
  value: Tasks
  promoted: false
commentId: O:Page::System#Environment#Import Data
name: '"Import Data"'
uid: O:Page::System#Environment#Import_Data
