### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Template Header"
alId: ID 8618
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Template_Header
  name: System.IO."Config. Template Header"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Template Header
  promoted: false
- name: PageType
  value: ListPlus
  promoted: true
- name: PopulateAllFields
  value: "True"
  promoted: false
- name: SourceTable
  value: "8618"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Template_Header
    name: System.IO."Config. Template Header"
    isExternal: false
commentId: O:Page::System#IO#Config# Template Header
name: '"Config. Template Header"'
uid: O:Page::System#IO#Config#_Template_Header
