### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Schedule"
alId: ID 1513
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Notification_Schedule
  name: System.Environment.Configuration."Notification Schedule"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Notification Schedule
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: "1513"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Notification_Schedule
    name: System.Environment.Configuration."Notification Schedule"
    isExternal: false
commentId: O:Page::System#Environment#Configuration#Notification Schedule
name: '"Notification Schedule"'
uid: O:Page::System#Environment#Configuration#Notification_Schedule
