### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Configuration Completion"
alId: ID 8638
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Setup
  name: System.IO."Config. Setup"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Configuration Completion
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: PageType
  value: Card
  promoted: true
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: "8627"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Setup
    name: System.IO."Config. Setup"
    isExternal: false
commentId: O:Page::System#IO#Configuration Completion
name: '"Configuration Completion"'
uid: O:Page::System#IO#Configuration_Completion
