### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Warning"
alId: ID 8637
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: " "
  promoted: false
- name: PageType
  value: NavigatePage
  promoted: true
- name: Extensible
  value: "False"
  promoted: true
commentId: O:Page::System#IO#Config# Package Warning
summary: This page is meant to inform users that importing and applying Configuration packages may affect the system's performance.
remarks: This page is not meant to be used by extensions.
name: '"Config. Package Warning"'
uid: O:Page::System#IO#Config#_Package_Warning
