### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Global Admin Message"
alId: ID 1459
namespace: System.Environment
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: PageType
  value: NavigatePage
  promoted: true
- name: Extensible
  value: "False"
  promoted: true
- name: Caption
  value: " "
  promoted: false
commentId: O:Page::System#Environment#Global Admin Message
summary: The page displays a warning message to users with the Global Administrator or Dynamics 365 Administrator role but without a Business Central license.
remarks: This page is not supposed to be referenced in extensions.
name: '"Global Admin Message"'
uid: O:Page::System#Environment#Global_Admin_Message
