### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Template List"
alId: ID 8620
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Template_Header
  name: System.IO."Config. Template Header"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: rapid start implementation migrate setup templates
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Configuration Templates
  promoted: false
- name: CardPageID
  value: Config. Template Header
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Template_Header
    name: System.IO."Config. Template Header"
    isExternal: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8618"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Template_Header
    name: System.IO."Config. Template Header"
    isExternal: false
- name: UsageCategory
  value: Lists
  promoted: false
commentId: O:Page::System#IO#Config# Template List
name: '"Config. Template List"'
uid: O:Page::System#IO#Config#_Template_List
