### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Question Areas"
alId: ID 8613
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Question_Area
  name: System.IO."Config. Question Area"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Question Areas
  promoted: false
- name: CardPageID
  value: Config. Question Area
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Question_Area
    name: System.IO."Config. Question Area"
    isExternal: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8611"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Question_Area
    name: System.IO."Config. Question Area"
    isExternal: false
commentId: O:Page::System#IO#Config# Question Areas
name: '"Config. Question Areas"'
uid: O:Page::System#IO#Config#_Question_Areas
