### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Worksheet"
alId: ID 8632
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Line
  name: System.IO."Config. Line"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: rapid start implementation migrate setup worksheet
  promoted: false
- name: ApplicationArea
  value: '#Suite'
  promoted: false
- name: Caption
  value: Configuration Worksheet
  promoted: false
- name: DelayedInsert
  value: "True"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8622"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Line
    name: System.IO."Config. Line"
    isExternal: false
- name: SourceTableView
  value: sorting("Vertical Sorting")
  promoted: false
- name: UsageCategory
  value: Tasks
  promoted: false
commentId: O:Page::System#IO#Config# Worksheet
name: '"Config. Worksheet"'
uid: O:Page::System#IO#Config#_Worksheet
