### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Errors"
alId: ID 8616
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Error
  name: System.IO."Config. Package Error"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Package Errors
  promoted: false
- name: DataCaptionExpression
  value: Rec."Table Caption"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8617"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Error
    name: System.IO."Config. Package Error"
    isExternal: false
commentId: O:Page::System#IO#Config# Package Errors
name: '"Config. Package Errors"'
uid: O:Page::System#IO#Config#_Package_Errors
