### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Application Area"
alId: ID 9179
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#Application_Area_Buffer
  name: System.Environment.Configuration."Application Area Buffer"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: Caption
  value: Application Area
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "9179"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#Application_Area_Buffer
    name: System.Environment.Configuration."Application Area Buffer"
    isExternal: false
- name: SourceTableTemporary
  value: "True"
  promoted: false
- name: UsageCategory
  value: Tasks
  promoted: false
commentId: O:Page::System#Environment#Configuration#Application Area
name: '"Application Area"'
uid: O:Page::System#Environment#Configuration#Application_Area
