### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."AAD Application List"
alId: ID 9860
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#AAD_Application
  name: System.Environment.Configuration."AAD Application"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: UsageCategory
  value: Administration
  promoted: false
- name: Caption
  value: Microsoft Entra Applications
  promoted: false
- name: CardPageId
  value: AAD Application Card
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#AAD_Application_Card
    name: System.Environment.Configuration."AAD Application Card"
    isExternal: false
- name: PageType
  value: List
  promoted: true
- name: PopulateAllFields
  value: "True"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: SourceTable
  value: "9012"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#AAD_Application
    name: System.Environment.Configuration."AAD Application"
    isExternal: false
commentId: O:Page::System#Environment#Configuration#AAD Application List
name: '"AAD Application List"'
uid: O:Page::System#Environment#Configuration#AAD_Application_List
