### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Table Processing Rules"
alId: ID 8640
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Table_Processing_Rule
  name: System.IO."Config. Table Processing Rule"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AutoSplitKey
  value: "True"
  promoted: false
- name: Caption
  value: Config. Table Processing Rules
  promoted: false
- name: DataCaptionFields
  value: 2,1
  promoted: false
- name: DelayedInsert
  value: "True"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: PopulateAllFields
  value: "True"
  promoted: false
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: "8631"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Table_Processing_Rule
    name: System.IO."Config. Table Processing Rule"
    isExternal: false
commentId: O:Page::System#IO#Config# Table Processing Rules
name: '"Config. Table Processing Rules"'
uid: O:Page::System#IO#Config#_Table_Processing_Rules
