### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Report Settings"
alId: ID 1560
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AccessByPermission
  value: TableData "Object Options" = IMD
  promoted: false
- name: ApplicationArea
  value: '#Basic,#Suite'
  promoted: false
- name: Caption
  value: Report Settings
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: ""
  promoted: true
- name: UsageCategory
  value: Administration
  promoted: false
commentId: O:Page::System#Environment#Configuration#Report Settings
name: '"Report Settings"'
uid: O:Page::System#Environment#Configuration#Report_Settings
