### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."My Notifications"
alId: ID 1518
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::System#Environment#Configuration#My_Notifications
  name: System.Environment.Configuration."My Notifications"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: ApplicationArea
  value: '#All'
  promoted: false
- name: Caption
  value: My Notifications
  promoted: false
- name: DataCaptionExpression
  value: "''"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: Permissions
  value: TableData "My Notifications" = rimd
  promoted: false
- name: SourceTable
  value: "1518"
  promoted: true
  xrefType:
    internalReference: O:Table::System#Environment#Configuration#My_Notifications
    name: System.Environment.Configuration."My Notifications"
    isExternal: false
- name: UsageCategory
  value: Administration
  promoted: false
methods:
- syntax:
    content: procedure InitializeNotificationsWithDefaultState()
  name: InitializeNotificationsWithDefaultState
  uid: M:Page::System#Environment#Configuration#My_Notifications.InitializeNotificationsWithDefaultState
commentId: O:Page::System#Environment#Configuration#My Notifications
name: '"My Notifications"'
uid: O:Page::System#Environment#Configuration#My_Notifications
