### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment."Concurrent Session List"
alId: ID 670
namespace: System.Environment
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment
langs:
- al
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Concurrent Session List
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: ShowFilter
  value: "False"
  promoted: false
- name: SourceTable
  value: ""
  promoted: true
- name: SourceTableView
  value: where("Client Type" = filter(<> "Web Service" & <> "Management Client" & <> NAS & <> "Client Service"))
  promoted: false
commentId: O:Page::System#Environment#Concurrent Session List
name: '"Concurrent Session List"'
uid: O:Page::System#Environment#Concurrent_Session_List
