### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Data"
alId: ID 8627
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Package_Data
  name: System.IO."Config. Package Data"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Package Data
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8615"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Package_Data
    name: System.IO."Config. Package Data"
    isExternal: false
commentId: O:Page::System#IO#Config# Package Data
name: '"Config. Package Data"'
uid: O:Page::System#IO#Config#_Package_Data
