### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Questionnaire"
alId: ID 8610
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Questionnaire
  name: System.IO."Config. Questionnaire"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: AdditionalSearchTerms
  value: rapid start implementation migrate setup questionnaire
  promoted: false
- name: ApplicationArea
  value: '#Suite'
  promoted: false
- name: Caption
  value: Configuration Questionnaire
  promoted: false
- name: PageType
  value: List
  promoted: true
- name: SourceTable
  value: "8610"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Questionnaire
    name: System.IO."Config. Questionnaire"
    isExternal: false
- name: UsageCategory
  value: Lists
  promoted: false
commentId: O:Page::System#IO#Config# Questionnaire
name: '"Config. Questionnaire"'
uid: O:Page::System#IO#Config#_Questionnaire
