### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Question Area"
alId: ID 8611
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::System#IO#Config#_Question_Area
  name: System.IO."Config. Question Area"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Config. Question Area
  promoted: false
- name: PageType
  value: ListPlus
  promoted: true
- name: PopulateAllFields
  value: "True"
  promoted: false
- name: SourceTable
  value: "8611"
  promoted: true
  xrefType:
    internalReference: O:Table::System#IO#Config#_Question_Area
    name: System.IO."Config. Question Area"
    isExternal: false
commentId: O:Page::System#IO#Config# Question Area
name: '"Config. Question Area"'
uid: O:Page::System#IO#Config#_Question_Area
