### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Credit Limit Notification"
alId: ID 1870
namespace: System.Environment.Configuration
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Sales#Customer#Customer
  name: Microsoft.Sales.Customer.Customer
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Credit Limit Notification
  promoted: false
- name: DelayedInsert
  value: "False"
  promoted: false
- name: DeleteAllowed
  value: "False"
  promoted: false
- name: Editable
  value: "False"
  promoted: false
- name: InsertAllowed
  value: "False"
  promoted: false
- name: LinksAllowed
  value: "False"
  promoted: false
- name: ModifyAllowed
  value: "False"
  promoted: false
- name: SourceTable
  value: "18"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Sales#Customer#Customer
    name: Microsoft.Sales.Customer.Customer
    isExternal: false
methods:
- syntax:
    content: 'procedure SetHeading(Value: Text[250])'
    parameters:
    - id: Value
      parameterType:
        name: Text[250]
        isExternal: true
  name: SetHeading
  uid: M:Page::System#Environment#Configuration#Credit_Limit_Notification.SetHeading(Text[250])
- syntax:
    content: 'procedure InitializeFromNotificationVar(CreditLimitNotification: Notification)'
    parameters:
    - id: CreditLimitNotification
      parameterType:
        name: Notification
        isExternal: true
  name: InitializeFromNotificationVar
  uid: M:Page::System#Environment#Configuration#Credit_Limit_Notification.InitializeFromNotificationVar(Notification)
commentId: O:Page::System#Environment#Configuration#Credit Limit Notification
name: '"Credit Limit Notification"'
uid: O:Page::System#Environment#Configuration#Credit_Limit_Notification
