### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Costing Method Configuration"
alId: ID 8645
namespace: System.IO
baseKind: Page
kind: Page
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
sourceTableType:
  internalReference: O:Table::Microsoft#Inventory#Setup#Inventory_Setup
  name: Microsoft.Inventory.Setup."Inventory Setup"
  isExternal: false
seeAlso:
- '[Page](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-page-object)'
objectProperties:
- name: Caption
  value: Costing Method Configuration
  promoted: false
- name: SourceTable
  value: "313"
  promoted: true
  xrefType:
    internalReference: O:Table::Microsoft#Inventory#Setup#Inventory_Setup
    name: Microsoft.Inventory.Setup."Inventory Setup"
    isExternal: false
- name: PageType
  value: Card
  promoted: true
commentId: O:Page::System#IO#Costing Method Configuration
name: '"Costing Method Configuration"'
uid: O:Page::System#IO#Costing_Method_Configuration
