### YamlMime:BusinessCentralApplicationObject
fqName: Base Application by Microsoft (24.0.16410.19107)
baseKind: Module
kind: Module
objectProperties:
- name: Version
  value: 24.0.16410.19107
  promoted: false
- name: Publisher
  value: Microsoft
  promoted: false
- name: Brief
  value: Base Application (W1)
  promoted: false
summary: Provides business processes that are typical for small and mid-sized companies, such as sales and purchasing, and customer and vendor management, plus complex processes, such as assembly, manufacturing, service, and directed warehouse management. https://go.microsoft.com/fwlink/?LinkId=2205496
name: Base Application
uid: N:Module::Base_Application
