### YamlMime:BusinessCentralApplicationObject
fqName: '"Calendar Event User Config."'
alId: ID 2161
baseKind: Table
kind: Table
parent: 'N:Module::Base_Application::Namespace::'
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Calendar Event User Config.
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[50]
    isExternal: true
  name: User
  uid: F:Table::Calendar_Event_User_Config#.User[50]
- type:
    name: Time
    isExternal: true
  name: '"Default Execute Time"'
  uid: F:Table::Calendar_Event_User_Config#.Default_Execute_Time
- type:
    name: Guid
    isExternal: true
  name: '"Current Job Queue Entry"'
  uid: F:Table::Calendar_Event_User_Config#.Current_Job_Queue_Entry
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Calendar_Event_User_Config#.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Calendar_Event_User_Config#.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Calendar_Event_User_Config#.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Calendar_Event_User_Config#.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Calendar_Event_User_Config#.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Calendar_Event_User_Config#.SystemRowVersion
commentId: O:Table::Calendar Event User Config#
name: '"Calendar Event User Config."'
uid: O:Table::Calendar_Event_User_Config#
