### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Integration.D365Sales."CRM Post Configuration"
alId: ID 5388
namespace: Microsoft.Integration.D365Sales
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Integration.D365Sales
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Post Configuration
  promoted: false
- name: Description
  value: Enable or disable entities for Activity Feeds and Yammer collaboration.
  promoted: false
- name: ExternalName
  value: msdyn_postconfig
  promoted: false
- name: TableType
  value: CRM
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: msdyn_PostConfigId
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_PostConfigId
- type:
    name: DateTime
    isExternal: true
  name: CreatedOn
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.CreatedOn
- type:
    name: DateTime
    isExternal: true
  name: ModifiedOn
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.ModifiedOn
- type:
    name: Option
    isExternal: true
  name: statecode
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.statecode
- type:
    name: Option
    isExternal: true
  name: statuscode
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.statuscode
- type:
    name: BigInteger
    isExternal: true
  name: VersionNumber
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.VersionNumber
- type:
    name: Integer
    isExternal: true
  name: ImportSequenceNumber
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.ImportSequenceNumber
- type:
    name: DateTime
    isExternal: true
  name: OverriddenCreatedOn
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.OverriddenCreatedOn
- type:
    name: Integer
    isExternal: true
  name: TimeZoneRuleVersionNumber
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.TimeZoneRuleVersionNumber
- type:
    name: Integer
    isExternal: true
  name: UTCConversionTimeZoneCode
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.UTCConversionTimeZoneCode
- type:
    name: Text[100]
    isExternal: true
  name: msdyn_EntityDisplayName
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_EntityDisplayName[100]
- type:
    name: Boolean
    isExternal: true
  name: msdyn_ConfigureWall
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_ConfigureWall
- type:
    name: Text[100]
    isExternal: true
  name: msdyn_EntityName
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_EntityName[100]
- type:
    name: Text[100]
    isExternal: true
  name: msdyn_FollowingViewId
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_FollowingViewId[100]
- type:
    name: Text[100]
    isExternal: true
  name: msdyn_FollowingViewId2
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_FollowingViewId2[100]
- type:
    name: Integer
    isExternal: true
  name: msdyn_Otc
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_Otc
- type:
    name: Blob
    isExternal: true
  name: msdyn_Status
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.msdyn_Status
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.SystemId
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration.SystemRowVersion
commentId: O:Table::Microsoft#Integration#D365Sales#CRM Post Configuration
name: '"CRM Post Configuration"'
uid: O:Table::Microsoft#Integration#D365Sales#CRM_Post_Configuration
