### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Foundation.Period."Date Compr. Settings Buffer"
alId: ID 9040
namespace: Microsoft.Foundation.Period
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Foundation.Period
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: TableType
  value: Temporary
  promoted: false
- name: Access
  value: Public
  promoted: false
- name: Extensible
  value: "True"
  promoted: true
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Primary Key"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Primary_Key[10]
- type:
    name: Boolean
    isExternal: true
  name: '"Compress G/L Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compress_G/L_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compress VAT Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compress_VAT_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compr. Bank Acc. Ledg Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compr#_Bank_Acc#_Ledg_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compress G/L Budget Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compress_G/L_Budget_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compr. Customer Ledger Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compr#_Customer_Ledger_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compress Vendor Ledger Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compress_Vendor_Ledger_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compr. Resource Ledger Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compr#_Resource_Ledger_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compress FA Ledger Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compress_FA_Ledger_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compr. Maintenance Ledg. Entr."'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compr#_Maintenance_Ledg#_Entr#
- type:
    name: Boolean
    isExternal: true
  name: '"Compr. Insurance Ledg. Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compr#_Insurance_Ledg#_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compress Warehouse Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compress_Warehouse_Entries
- type:
    name: Boolean
    isExternal: true
  name: '"Compress Item Budget Entries"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Compress_Item_Budget_Entries
- type:
    name: Date
    isExternal: true
  name: '"Starting Date"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Starting_Date
- type:
    name: Date
    isExternal: true
  name: '"Ending Date"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Ending_Date
- type:
    internalReference: O:Enum::Microsoft#Foundation#Period#Date_Compression_Period_Length
    name: Microsoft.Foundation.Period."Date Compression Period Length"
    isExternal: false
  name: '"Period Length"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Period_Length
- type:
    name: Text[100]
    isExternal: true
  name: Description
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Description[100]
- type:
    name: Text[250]
    isExternal: true
  name: '"Retain Dimensions"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Retain_Dimensions[250]
- type:
    name: Boolean
    isExternal: true
  name: '"Delete Empty Registers"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Delete_Empty_Registers
- type:
    name: Integer
    isExternal: true
  name: '"No. of Records Removed"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.No#_of_Records_Removed
- type:
    name: Decimal
    isExternal: true
  name: '"Saved Space (MB)"'
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.Saved_Space_(MB)
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer.SystemRowVersion
commentId: O:Table::Microsoft#Foundation#Period#Date Compr# Settings Buffer
name: '"Date Compr. Settings Buffer"'
uid: O:Table::Microsoft#Foundation#Period#Date_Compr#_Settings_Buffer
