### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Inventory.Ledger."Item Application Entry History"
alId: ID 343
namespace: Microsoft.Inventory.Ledger
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Inventory.Ledger
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Item Application Entry History
  promoted: false
- name: DrillDownPageID
  value: Item Application Entry History
  promoted: false
  xrefType:
    internalReference: O:Page::Microsoft#Inventory#Ledger#Item_Application_Entry_History
    name: Microsoft.Inventory.Ledger."Item Application Entry History"
    isExternal: false
- name: LookupPageID
  value: Item Application Entry History
  promoted: false
  xrefType:
    internalReference: O:Page::Microsoft#Inventory#Ledger#Item_Application_Entry_History
    name: Microsoft.Inventory.Ledger."Item Application Entry History"
    isExternal: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure GetLastEntryNo(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetLastEntryNo
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.GetLastEntryNo:Integer
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Entry_No#
- type:
    name: Integer
    isExternal: true
  name: '"Item Ledger Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Item_Ledger_Entry_No#
- type:
    name: Integer
    isExternal: true
  name: '"Inbound Item Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Inbound_Item_Entry_No#
- type:
    name: Integer
    isExternal: true
  name: '"Outbound Item Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Outbound_Item_Entry_No#
- type:
    name: Integer
    isExternal: true
  name: '"Primary Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Primary_Entry_No#
- type:
    name: Decimal
    isExternal: true
  name: Quantity
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Quantity
- type:
    name: Date
    isExternal: true
  name: '"Posting Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Posting_Date
- type:
    name: Integer
    isExternal: true
  name: '"Transferred-from Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Transferred-from_Entry_No#
- type:
    name: DateTime
    isExternal: true
  name: '"Creation Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Creation_Date
- type:
    name: Code[50]
    isExternal: true
  name: '"Created By User"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Created_By_User[50]
- type:
    name: DateTime
    isExternal: true
  name: '"Last Modified Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Last_Modified_Date
- type:
    name: Code[50]
    isExternal: true
  name: '"Last Modified By User"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Last_Modified_By_User[50]
- type:
    name: DateTime
    isExternal: true
  name: '"Deleted Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Deleted_Date
- type:
    name: Code[50]
    isExternal: true
  name: '"Deleted By User"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Deleted_By_User[50]
- type:
    name: Boolean
    isExternal: true
  name: '"Cost Application"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Cost_Application
- type:
    name: Date
    isExternal: true
  name: '"Output Completely Invd. Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.Output_Completely_Invd#_Date
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History.SystemRowVersion
commentId: O:Table::Microsoft#Inventory#Ledger#Item Application Entry History
name: '"Item Application Entry History"'
uid: O:Table::Microsoft#Inventory#Ledger#Item_Application_Entry_History
