### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.VAT.Registration."VAT Reg. No. Srv Config"
alId: ID 248
namespace: Microsoft.Finance.VAT.Registration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.VAT.Registration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: VAT Reg. No. Srv Config
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure VATRegNoSrvIsEnabled(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: VATRegNoSrvIsEnabled
  uid: M:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.VATRegNoSrvIsEnabled:Boolean
- syntax:
    content: 'procedure GetVATRegNoURL(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetVATRegNoURL
  uid: M:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.GetVATRegNoURL:Text
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Entry No."'
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.Entry_No#
- type:
    name: Boolean
    isExternal: true
  name: Enabled
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.Enabled
- type:
    name: Text[250]
    isExternal: true
  name: '"Service Endpoint"'
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.Service_Endpoint[250]
- type:
    name: Code[20]
    isExternal: true
  name: '"Default Template Code"'
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.Default_Template_Code[20]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config.SystemRowVersion
commentId: O:Table::Microsoft#Finance#VAT#Registration#VAT Reg# No# Srv Config
name: '"VAT Reg. No. Srv Config"'
uid: O:Table::Microsoft#Finance#VAT#Registration#VAT_Reg#_No#_Srv_Config
