### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Bank.Reconciliation."Bank Pmt. Appl. Settings"
alId: ID 1253
namespace: Microsoft.Bank.Reconciliation
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Bank.Reconciliation
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Bank Payment Application Settings
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: procedure GetOrInsert()
  name: GetOrInsert
  uid: M:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.GetOrInsert
fields:
- type:
    name: Code[20]
    isExternal: true
  name: PrimaryKey
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.PrimaryKey[20]
- type:
    name: Boolean
    isExternal: true
  name: '"Vendor Ledger Entries Matching"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Vendor_Ledger_Entries_Matching
- type:
    name: Boolean
    isExternal: true
  name: '"Cust. Ledger Entries Matching"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Cust#_Ledger_Entries_Matching
- type:
    name: Boolean
    isExternal: true
  name: '"Bank Ledger Entries Matching"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Bank_Ledger_Entries_Matching
- type:
    internalReference: O:Enum::Microsoft#Bank#Reconciliation#Pmt#_Appl#_Related_Party_Name_Matching
    name: Microsoft.Bank.Reconciliation."Pmt. Appl. Related Party Name Matching"
    isExternal: false
  name: '"RelatedParty Name Matching"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.RelatedParty_Name_Matching
- type:
    name: Boolean
    isExternal: true
  name: '"Bank Ledg Closing Doc No Match"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Bank_Ledg_Closing_Doc_No_Match
- type:
    name: Boolean
    isExternal: true
  name: '"Apply Man. Disable Suggestions"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Apply_Man#_Disable_Suggestions
- type:
    name: Boolean
    isExternal: true
  name: '"Enable Apply Immediatelly"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Enable_Apply_Immediatelly
- type:
    name: Boolean
    isExternal: true
  name: '"Empl. Ledger Entries Matching"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Empl#_Ledger_Entries_Matching
- type:
    name: Boolean
    isExternal: true
  name: '"Vend Ledg Hidden In Apply Man"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Vend_Ledg_Hidden_In_Apply_Man
- type:
    name: Boolean
    isExternal: true
  name: '"Cust Ledg Hidden In Apply Man"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Cust_Ledg_Hidden_In_Apply_Man
- type:
    name: Boolean
    isExternal: true
  name: '"Bank Ledg Hidden In Apply Man"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Bank_Ledg_Hidden_In_Apply_Man
- type:
    name: Boolean
    isExternal: true
  name: '"Empl Ledg Hidden In Apply Man"'
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.Empl_Ledg_Hidden_In_Apply_Man
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings.SystemRowVersion
commentId: O:Table::Microsoft#Bank#Reconciliation#Bank Pmt# Appl# Settings
name: '"Bank Pmt. Appl. Settings"'
uid: O:Table::Microsoft#Bank#Reconciliation#Bank_Pmt#_Appl#_Settings
