### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Finance.VAT.Reporting."VAT Reports Configuration"
alId: ID 746
namespace: Microsoft.Finance.VAT.Reporting
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Finance.VAT.Reporting
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: VAT Reports Configuration
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    internalReference: O:Enum::Microsoft#Finance#VAT#Reporting#VAT_Report_Configuration
    name: Microsoft.Finance.VAT.Reporting."VAT Report Configuration"
    isExternal: false
  name: '"VAT Report Type"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.VAT_Report_Type
- type:
    name: Code[10]
    isExternal: true
  name: '"VAT Report Version"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.VAT_Report_Version[10]
- type:
    name: Integer
    isExternal: true
  name: '"Suggest Lines Codeunit ID"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Suggest_Lines_Codeunit_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Suggest Lines Codeunit Caption"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Suggest_Lines_Codeunit_Caption[250]
- type:
    name: Integer
    isExternal: true
  name: '"Content Codeunit ID"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Content_Codeunit_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Content Codeunit Caption"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Content_Codeunit_Caption[250]
- type:
    name: Integer
    isExternal: true
  name: '"Submission Codeunit ID"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Submission_Codeunit_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Submission Codeunit Caption"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Submission_Codeunit_Caption[250]
- type:
    name: Integer
    isExternal: true
  name: '"Response Handler Codeunit ID"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Response_Handler_Codeunit_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Resp. Handler Codeunit Caption"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Resp#_Handler_Codeunit_Caption[250]
- type:
    name: Integer
    isExternal: true
  name: '"Validate Codeunit ID"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Validate_Codeunit_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Validate Codeunit Caption"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.Validate_Codeunit_Caption[250]
- type:
    name: Code[10]
    isExternal: true
  name: '"VAT Statement Template"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.VAT_Statement_Template[10]
- type:
    name: Code[10]
    isExternal: true
  name: '"VAT Statement Name"'
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.VAT_Statement_Name[10]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration.SystemRowVersion
commentId: O:Table::Microsoft#Finance#VAT#Reporting#VAT Reports Configuration
name: '"VAT Reports Configuration"'
uid: O:Table::Microsoft#Finance#VAT#Reporting#VAT_Reports_Configuration
