### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Inventory.Ledger."Item Application Entry"
alId: ID 339
namespace: Microsoft.Inventory.Ledger
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Inventory.Ledger
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Item Application Entry
  promoted: false
- name: DrillDownPageID
  value: Item Application Entries
  promoted: false
  xrefType:
    internalReference: O:Page::Microsoft#Inventory#Ledger#Item_Application_Entries
    name: Microsoft.Inventory.Ledger."Item Application Entries"
    isExternal: false
- name: LookupPageID
  value: Item Application Entries
  promoted: false
  xrefType:
    internalReference: O:Page::Microsoft#Inventory#Ledger#Item_Application_Entries
    name: Microsoft.Inventory.Ledger."Item Application Entries"
    isExternal: false
- name: Permissions
  value: >-
    TableData "Item Application Entry" = rm,
                      TableData "Item Application Entry History" = ri
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure AppliedOutbndEntryExists(InbndItemLedgEntryNo: Integer, IsCostApplication: Boolean, FilterOnOnlyCostNotAdjusted: Boolean): Boolean'
    parameters:
    - id: InbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    - id: IsCostApplication
      parameterType:
        name: Boolean
        isExternal: true
    - id: FilterOnOnlyCostNotAdjusted
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: AppliedOutbndEntryExists
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.AppliedOutbndEntryExists(Integer,Boolean,Boolean):Boolean
- syntax:
    content: 'procedure AppliedInbndTransEntryExists(InbndItemLedgEntryNo: Integer, IsCostApplication: Boolean): Boolean'
    parameters:
    - id: InbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    - id: IsCostApplication
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: AppliedInbndTransEntryExists
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.AppliedInbndTransEntryExists(Integer,Boolean):Boolean
- syntax:
    content: 'procedure AppliedInbndEntryExists(OutbndItemLedgEntryNo: Integer, IsCostApplication: Boolean): Boolean'
    parameters:
    - id: OutbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    - id: IsCostApplication
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: AppliedInbndEntryExists
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.AppliedInbndEntryExists(Integer,Boolean):Boolean
- syntax:
    content: 'procedure AppliedFromEntryExists(InbndItemLedgEntryNo: Integer): Boolean'
    parameters:
    - id: InbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: AppliedFromEntryExists
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.AppliedFromEntryExists(Integer):Boolean
- syntax:
    content: 'procedure GetInboundEntriesTheOutbndEntryAppliedTo(OutbndItemLedgEntryNo: Integer): Boolean'
    parameters:
    - id: OutbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: GetInboundEntriesTheOutbndEntryAppliedTo
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.GetInboundEntriesTheOutbndEntryAppliedTo(Integer):Boolean
- syntax:
    content: 'procedure GetOutboundEntriesAppliedToTheInboundEntry(InbndItemLedgEntryNo: Integer): Boolean'
    parameters:
    - id: InbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: GetOutboundEntriesAppliedToTheInboundEntry
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.GetOutboundEntriesAppliedToTheInboundEntry(Integer):Boolean
- syntax:
    content: 'procedure CheckAppliedFromEntryToAdjust(InbndItemLedgEntryNo: Integer)'
    parameters:
    - id: InbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
  name: CheckAppliedFromEntryToAdjust
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.CheckAppliedFromEntryToAdjust(Integer)
- syntax:
    content: 'procedure CostReceiver(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: CostReceiver
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.CostReceiver:Integer
- syntax:
    content: 'procedure Fixed(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: Fixed
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Fixed:Boolean
- syntax:
    content: 'procedure InsertHistory(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: InsertHistory
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.InsertHistory:Integer
- syntax:
    content: 'procedure CostApplication(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: CostApplication
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.CostApplication:Boolean
- syntax:
    content: 'procedure CheckIsCyclicalLoop(CheckItemLedgEntry: Record "Item Ledger Entry", FromItemLedgEntry: Record "Item Ledger Entry"): Boolean'
    parameters:
    - id: CheckItemLedgEntry
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
    - id: FromItemLedgEntry
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: CheckIsCyclicalLoop
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.CheckIsCyclicalLoop(Item_Ledger_Entry,Item_Ledger_Entry):Boolean
- syntax:
    content: 'procedure GetLastEntryNo(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetLastEntryNo
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.GetLastEntryNo:Integer
- syntax:
    content: 'procedure GetVisitedEntries(FromItemLedgEntry: Record "Item Ledger Entry", var ItemLedgEntryInChain: Record "Item Ledger Entry", WithinValuationDate: Boolean)'
    parameters:
    - id: FromItemLedgEntry
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
    - id: ItemLedgEntryInChain
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
    - id: WithinValuationDate
      parameterType:
        name: Boolean
        isExternal: true
  name: GetVisitedEntries
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.GetVisitedEntries(Item_Ledger_Entry,Item_Ledger_Entry@,Boolean)
- syntax:
    content: 'procedure OutboundApplied(EntryNo: Integer, SameType: Boolean): Decimal'
    parameters:
    - id: EntryNo
      parameterType:
        name: Integer
        isExternal: true
    - id: SameType
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Decimal
        isExternal: true
  name: OutboundApplied
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.OutboundApplied(Integer,Boolean):Decimal
- syntax:
    content: 'procedure InboundApplied(EntryNo: Integer, SameType: Boolean): Decimal'
    parameters:
    - id: EntryNo
      parameterType:
        name: Integer
        isExternal: true
    - id: SameType
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Decimal
        isExternal: true
  name: InboundApplied
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.InboundApplied(Integer,Boolean):Decimal
- syntax:
    content: 'procedure Returned(EntryNo: Integer): Decimal'
    parameters:
    - id: EntryNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Decimal
        isExternal: true
  name: Returned
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Returned(Integer):Decimal
- syntax:
    content: 'procedure ExistsBetween(ILE1: Integer, ILE2: Integer): Boolean'
    parameters:
    - id: ILE1
      parameterType:
        name: Integer
        isExternal: true
    - id: ILE2
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: ExistsBetween
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.ExistsBetween(Integer,Integer):Boolean
- syntax:
    content: 'procedure SetOutboundsNotUpdated(ItemLedgEntry: Record "Item Ledger Entry")'
    parameters:
    - id: ItemLedgEntry
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
  name: SetOutboundsNotUpdated
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SetOutboundsNotUpdated(Item_Ledger_Entry)
- syntax:
    content: 'procedure SetInboundToUpdated(ItemLedgEntry: Record "Item Ledger Entry")'
    parameters:
    - id: ItemLedgEntry
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
  name: SetInboundToUpdated
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SetInboundToUpdated(Item_Ledger_Entry)
- syntax:
    content: 'procedure IsAppliedFromIncrease(InbndItemLedgEntryNo: Integer): Boolean'
    parameters:
    - id: InbndItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsAppliedFromIncrease
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.IsAppliedFromIncrease(Integer):Boolean
- syntax:
    content: 'procedure IsOutbndItemApplEntryCostApplication(OutboundItemLedgEntryNo: Integer): Boolean'
    parameters:
    - id: OutboundItemLedgEntryNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsOutbndItemApplEntryCostApplication
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.IsOutbndItemApplEntryCostApplication(Integer):Boolean
- syntax:
    content: 'procedure SetSearchedItemLedgerEntry(var ItemLedgerEntry: Record "Item Ledger Entry")'
    parameters:
    - id: ItemLedgerEntry
      parameterType:
        name: Record "Item Ledger Entry"
        isExternal: true
  name: SetSearchedItemLedgerEntry
  uid: M:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SetSearchedItemLedgerEntry(Item_Ledger_Entry@)
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Entry_No#
- type:
    name: Integer
    isExternal: true
  name: '"Item Ledger Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Item_Ledger_Entry_No#
- type:
    name: Integer
    isExternal: true
  name: '"Inbound Item Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Inbound_Item_Entry_No#
- type:
    name: Integer
    isExternal: true
  name: '"Outbound Item Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Outbound_Item_Entry_No#
- type:
    name: Decimal
    isExternal: true
  name: Quantity
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Quantity
- type:
    name: Date
    isExternal: true
  name: '"Posting Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Posting_Date
- type:
    name: Integer
    isExternal: true
  name: '"Transferred-from Entry No."'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Transferred-from_Entry_No#
- type:
    name: DateTime
    isExternal: true
  name: '"Creation Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Creation_Date
- type:
    name: Code[50]
    isExternal: true
  name: '"Created By User"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Created_By_User[50]
- type:
    name: DateTime
    isExternal: true
  name: '"Last Modified Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Last_Modified_Date
- type:
    name: Code[50]
    isExternal: true
  name: '"Last Modified By User"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Last_Modified_By_User[50]
- type:
    name: Boolean
    isExternal: true
  name: '"Cost Application"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Cost_Application
- type:
    name: Date
    isExternal: true
  name: '"Output Completely Invd. Date"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Output_Completely_Invd#_Date
- type:
    name: Boolean
    isExternal: true
  name: '"Outbound Entry is Updated"'
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.Outbound_Entry_is_Updated
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Inventory#Ledger#Item_Application_Entry.SystemRowVersion
commentId: O:Table::Microsoft#Inventory#Ledger#Item Application Entry
name: '"Item Application Entry"'
uid: O:Table::Microsoft#Inventory#Ledger#Item_Application_Entry
