### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Foundation.Address."Postcode Service Config"
alId: ID 9091
namespace: Microsoft.Foundation.Address
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Foundation.Address
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Postcode Service Config
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure SaveServiceKey(ServiceKeyText: Text)'
    parameters:
    - id: ServiceKeyText
      parameterType:
        name: Text
        isExternal: true
  name: SaveServiceKey
  uid: M:Table::Microsoft#Foundation#Address#Postcode_Service_Config.SaveServiceKey(Text)
- syntax:
    content: 'procedure GetServiceKey(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetServiceKey
  uid: M:Table::Microsoft#Foundation#Address#Postcode_Service_Config.GetServiceKey:Text
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Primary Key"'
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.Primary_Key[10]
- type:
    name: Text[250]
    isExternal: true
  name: ServiceKey
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.ServiceKey[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Foundation#Address#Postcode_Service_Config.SystemRowVersion
commentId: O:Table::Microsoft#Foundation#Address#Postcode Service Config
name: '"Postcode Service Config"'
uid: O:Table::Microsoft#Foundation#Address#Postcode_Service_Config
