### YamlMime:BusinessCentralApplicationObject
fqName: Microsoft.Integration.Graph."O365 C2Graph Event Settings"
alId: ID 2162
namespace: Microsoft.Integration.Graph
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::Microsoft.Integration.Graph
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: O365 C2Graph Event Settings
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteReason
  value: Microsoft Invoicing has been discontinued.
  promoted: false
- name: ObsoleteState
  value: Removed
  promoted: false
- name: ObsoleteTag
  value: "24.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[10]
    isExternal: true
  name: Code
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Code[10]
- type:
    name: Boolean
    isExternal: true
  name: '"Inv. Sent Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Sent_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Sent Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Sent_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Inv. Paid Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Paid_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Paid Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Paid_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Inv. Draft Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Draft_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Draft Duration (Day)"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Draft_Duration_(Day)
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Draft Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Draft_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Inv. Overdue Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Overdue_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Overdue Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Overdue_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Inv. Inactivity Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Inactivity_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Inactivity Duration (Day)"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Inactivity_Duration_(Day)
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Inactivity Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Inactivity_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Est. Sent Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Est#_Sent_Enabled
- type:
    name: Boolean
    isExternal: true
  name: '"Est. Accepted Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Est#_Accepted_Enabled
- type:
    name: Boolean
    isExternal: true
  name: '"Est. Expiring Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Est#_Expiring_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Est. Expiring Week Start (WD)"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Est#_Expiring_Week_Start_(WD)
- type:
    name: Integer
    isExternal: true
  name: '"Est. Expiring Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Est#_Expiring_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Inv. Email Failed Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Email_Failed_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Inv. Email Failed Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Inv#_Email_Failed_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Est. Email Failed Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Est#_Email_Failed_Enabled
- type:
    name: Integer
    isExternal: true
  name: '"Est. Email Failed Event"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Est#_Email_Failed_Event
- type:
    name: Boolean
    isExternal: true
  name: '"Kpi Update Enabled"'
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.Kpi_Update_Enabled
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings.SystemRowVersion
commentId: O:Table::Microsoft#Integration#Graph#O365 C2Graph Event Settings
name: '"O365 C2Graph Event Settings"'
obsoletion:
  state: removed
  reason: Microsoft Invoicing has been discontinued.
  version: "24.0"
uid: O:Table::Microsoft#Integration#Graph#O365_C2Graph_Event_Settings
