### YamlMime:BusinessCentralApplicationObject
fqName: '"Native - Gen. Settings Buffer"'
alId: ID 2840
baseKind: Table
kind: Table
parent: 'N:Module::Base_Application::Namespace::'
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Native - Gen. Settings Buffer
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteState
  value: Removed
  promoted: false
- name: ObsoleteTag
  value: "23.0"
  promoted: false
- name: ObsoleteReason
  value: These objects will be removed
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Primary Key"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Primary_Key[10]
- type:
    name: Text[10]
    isExternal: true
  name: '"Currency Symbol"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Currency_Symbol[10]
- type:
    name: Text[250]
    isExternal: true
  name: '"Paypal Email Address"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Paypal_Email_Address[250]
- type:
    name: Code[10]
    isExternal: true
  name: '"Country/Region Code"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Country/Region_Code[10]
- type:
    name: Integer
    isExternal: true
  name: '"Language Locale ID"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Language_Locale_ID
- type:
    name: Text[50]
    isExternal: true
  name: '"Language Code"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Language_Code[50]
- type:
    name: Text[80]
    isExternal: true
  name: '"Language Display Name"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Language_Display_Name[80]
- type:
    name: Guid
    isExternal: true
  name: '"Default Tax ID"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Default_Tax_ID
- type:
    name: Text[100]
    isExternal: true
  name: '"Defauilt Tax Description"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Defauilt_Tax_Description[100]
- type:
    name: Guid
    isExternal: true
  name: '"Default Payment Terms ID"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Default_Payment_Terms_ID
- type:
    name: Text[50]
    isExternal: true
  name: '"Def. Pmt. Term Description"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Def#_Pmt#_Term_Description[50]
- type:
    name: Guid
    isExternal: true
  name: '"Default Payment Method ID"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Default_Payment_Method_ID
- type:
    name: Text[50]
    isExternal: true
  name: '"Def. Pmt. Method Description"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Def#_Pmt#_Method_Description[50]
- type:
    name: Decimal
    isExternal: true
  name: '"Amount Rounding Precision"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Amount_Rounding_Precision
- type:
    name: Decimal
    isExternal: true
  name: '"Unit-Amount Rounding Precision"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Unit-Amount_Rounding_Precision
- type:
    name: Decimal
    isExternal: true
  name: '"VAT/Tax Rounding Precision"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.VAT/Tax_Rounding_Precision
- type:
    name: Decimal
    isExternal: true
  name: '"Quantity Rounding Precision"'
  uid: F:Table::Native_-_Gen#_Settings_Buffer.Quantity_Rounding_Precision
- type:
    name: Boolean
    isExternal: true
  name: EnableSync
  uid: F:Table::Native_-_Gen#_Settings_Buffer.EnableSync
- type:
    name: Boolean
    isExternal: true
  name: EnableSyncCoupons
  uid: F:Table::Native_-_Gen#_Settings_Buffer.EnableSyncCoupons
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Native_-_Gen#_Settings_Buffer.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Native_-_Gen#_Settings_Buffer.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Native_-_Gen#_Settings_Buffer.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Native_-_Gen#_Settings_Buffer.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Native_-_Gen#_Settings_Buffer.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Native_-_Gen#_Settings_Buffer.SystemRowVersion
commentId: O:Table::Native - Gen# Settings Buffer
name: '"Native - Gen. Settings Buffer"'
obsoletion:
  state: removed
  reason: These objects will be removed
  version: "23.0"
uid: O:Table::Native_-_Gen#_Settings_Buffer
