### YamlMime:BusinessCentralApplicationObject
fqName: '"O365 Settings Menu"'
alId: ID 2132
baseKind: Table
kind: Table
parent: 'N:Module::Base_Application::Namespace::'
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: O365 Settings Menu
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteReason
  value: Microsoft Invoicing has been discontinued.
  promoted: false
- name: ObsoleteState
  value: Removed
  promoted: false
- name: ObsoleteTag
  value: "24.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Key"'
  uid: F:Table::O365_Settings_Menu.Key
- type:
    name: Integer
    isExternal: true
  name: '"Page ID"'
  uid: F:Table::O365_Settings_Menu.Page_ID
- type:
    name: Text[30]
    isExternal: true
  name: Title
  uid: F:Table::O365_Settings_Menu.Title[30]
- type:
    name: Text[80]
    isExternal: true
  name: Description
  uid: F:Table::O365_Settings_Menu.Description[80]
- type:
    name: Text[250]
    isExternal: true
  name: Link
  uid: F:Table::O365_Settings_Menu.Link[250]
- type:
    name: Option
    isExternal: true
  name: '"On Open Action"'
  uid: F:Table::O365_Settings_Menu.On_Open_Action
- type:
    name: Text[250]
    isExternal: true
  name: Parameter
  uid: F:Table::O365_Settings_Menu.Parameter[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::O365_Settings_Menu.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::O365_Settings_Menu.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::O365_Settings_Menu.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::O365_Settings_Menu.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::O365_Settings_Menu.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::O365_Settings_Menu.SystemRowVersion
commentId: O:Table::O365 Settings Menu
name: '"O365 Settings Menu"'
obsoletion:
  state: removed
  reason: Microsoft Invoicing has been discontinued.
  version: "24.0"
uid: O:Table::O365_Settings_Menu
