### YamlMime:BusinessCentralApplicationObject
fqName: '"Product Group"'
alId: ID 5723
baseKind: Table
kind: Table
parent: 'N:Module::Base_Application::Namespace::'
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Product Group
  promoted: false
- name: ObsoleteReason
  value: Product Groups became first level children of Item Categories.
  promoted: false
- name: ObsoleteState
  value: Removed
  promoted: false
- name: ObsoleteTag
  value: "15.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Item Category Code"'
  uid: F:Table::Product_Group.Item_Category_Code[20]
- type:
    name: Code[10]
    isExternal: true
  name: Code
  uid: F:Table::Product_Group.Code[10]
- type:
    name: Text[100]
    isExternal: true
  name: Description
  uid: F:Table::Product_Group.Description[100]
- type:
    name: Code[10]
    isExternal: true
  name: '"Warehouse Class Code"'
  uid: F:Table::Product_Group.Warehouse_Class_Code[10]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::Product_Group.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::Product_Group.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::Product_Group.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::Product_Group.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::Product_Group.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::Product_Group.SystemRowVersion
commentId: O:Table::Product Group
name: '"Product Group"'
obsoletion:
  state: removed
  reason: Product Groups became first level children of Item Categories.
  version: "15.0"
uid: O:Table::Product_Group
