### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Tenant Config. Package File"
alId: ID 5433
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Tenant Config. Package File
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure SetContentFromBlob(TempBlob: __MissingTypeSymbol__)'
    parameters:
    - id: TempBlob
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: SetContentFromBlob
  uid: M:Table::System#IO#Tenant_Config#_Package_File.SetContentFromBlob(__MissingSymbol__)
fields:
- type:
    name: Code[20]
    isExternal: true
  name: Code
  uid: F:Table::System#IO#Tenant_Config#_Package_File.Code[20]
- type:
    name: Blob
    isExternal: true
  name: Content
  uid: F:Table::System#IO#Tenant_Config#_Package_File.Content
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Tenant_Config#_Package_File.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Tenant_Config#_Package_File.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Tenant_Config#_Package_File.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Tenant_Config#_Package_File.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Tenant_Config#_Package_File.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Tenant_Config#_Package_File.SystemRowVersion
commentId: O:Table::System#IO#Tenant Config# Package File
name: '"Tenant Config. Package File"'
uid: O:Table::System#IO#Tenant_Config#_Package_File
