### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."AAD Application"
alId: ID 9012
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: AAD Application
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataCaptionFields
  value: "10"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"Client Id"'
  uid: F:Table::System#Environment#Configuration#AAD_Application.Client_Id
- type:
    name: Option
    isExternal: true
  name: State
  uid: F:Table::System#Environment#Configuration#AAD_Application.State
- type:
    name: Guid
    isExternal: true
  name: '"App ID"'
  uid: F:Table::System#Environment#Configuration#AAD_Application.App_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"App Name"'
  uid: F:Table::System#Environment#Configuration#AAD_Application.App_Name[250]
- type:
    name: Text[50]
    isExternal: true
  name: Description
  uid: F:Table::System#Environment#Configuration#AAD_Application.Description[50]
- type:
    name: Text[50]
    isExternal: true
  name: '"Contact Information"'
  uid: F:Table::System#Environment#Configuration#AAD_Application.Contact_Information[50]
- type:
    name: Boolean
    isExternal: true
  name: '"Permission Granted"'
  uid: F:Table::System#Environment#Configuration#AAD_Application.Permission_Granted
- type:
    name: Guid
    isExternal: true
  name: '"User ID"'
  uid: F:Table::System#Environment#Configuration#AAD_Application.User_ID
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#AAD_Application.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#AAD_Application.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#AAD_Application.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#AAD_Application.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#AAD_Application.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#AAD_Application.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#AAD Application
name: '"AAD Application"'
uid: O:Table::System#Environment#Configuration#AAD_Application
