### YamlMime:BusinessCentralApplicationObject
fqName: System.Automation."Flow Service Configuration"
alId: ID 1543
namespace: System.Automation
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Automation
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Power Automate Service Configuration
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: InherentEntitlements
  value: r
  promoted: false
- name: InherentPermissions
  value: r
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Primary Key"'
  uid: F:Table::System#Automation#Flow_Service_Configuration.Primary_Key[10]
- type:
    name: Option
    isExternal: true
  name: '"Flow Service"'
  uid: F:Table::System#Automation#Flow_Service_Configuration.Flow_Service
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Automation#Flow_Service_Configuration.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Automation#Flow_Service_Configuration.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Automation#Flow_Service_Configuration.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Automation#Flow_Service_Configuration.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Automation#Flow_Service_Configuration.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Automation#Flow_Service_Configuration.SystemRowVersion
commentId: O:Table::System#Automation#Flow Service Configuration
name: '"Flow Service Configuration"'
uid: O:Table::System#Automation#Flow_Service_Configuration
