### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Questionnaire"
alId: ID 8610
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Questionnaire
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[10]
    isExternal: true
  name: Code
  uid: F:Table::System#IO#Config#_Questionnaire.Code[10]
- type:
    name: Text[100]
    isExternal: true
  name: Description
  uid: F:Table::System#IO#Config#_Questionnaire.Description[100]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Questionnaire.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Questionnaire.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Questionnaire.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Questionnaire.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Questionnaire.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Questionnaire.SystemRowVersion
commentId: O:Table::System#IO#Config# Questionnaire
name: '"Config. Questionnaire"'
uid: O:Table::System#IO#Config#_Questionnaire
