### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Experience Tier Setup"
alId: ID 9176
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Experience Tier Setup
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Text[30]
    isExternal: true
  name: '"Company Name"'
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Company_Name[30]
- type:
    name: Boolean
    isExternal: true
  name: Invoicing
  obsoletion:
    state: removed
    reason: Microsoft Invoicing is not supported on Business Central
    version: "18.0"
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Invoicing
- type:
    name: Boolean
    isExternal: true
  name: Basic
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Basic
- type:
    name: Boolean
    isExternal: true
  name: Essential
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Essential
- type:
    name: Boolean
    isExternal: true
  name: Premium
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Premium
- type:
    name: Boolean
    isExternal: true
  name: Preview
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Preview
- type:
    name: Boolean
    isExternal: true
  name: Advanced
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Advanced
- type:
    name: Boolean
    isExternal: true
  name: Custom
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.Custom
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Setup.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Experience Tier Setup
name: '"Experience Tier Setup"'
uid: O:Table::System#Environment#Configuration#Experience_Tier_Setup
