### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Line"
alId: ID 8622
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Line
  promoted: false
- name: DataCaptionFields
  value: "4"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: procedure CheckBlocked()
  name: CheckBlocked
  uid: M:Table::System#IO#Config#_Line.CheckBlocked
- syntax:
    content: procedure ShowTableData()
  name: ShowTableData
  uid: M:Table::System#IO#Config#_Line.ShowTableData
- syntax:
    content: procedure ShowQuestions()
  name: ShowQuestions
  uid: M:Table::System#IO#Config#_Line.ShowQuestions
- syntax:
    content: 'procedure GetProgress(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetProgress
  uid: M:Table::System#IO#Config#_Line.GetProgress:Integer
- syntax:
    content: 'procedure GetNoOfDirectChildrenTables(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetNoOfDirectChildrenTables
  uid: M:Table::System#IO#Config#_Line.GetNoOfDirectChildrenTables:Integer
- syntax:
    content: 'procedure GetDirectChildrenTablesStatusWeight(): Decimal'
    return:
      returnType:
        name: Decimal
        isExternal: true
  name: GetDirectChildrenTablesStatusWeight
  uid: M:Table::System#IO#Config#_Line.GetDirectChildrenTablesStatusWeight:Decimal
- syntax:
    content: 'procedure GetNoTables(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetNoTables
  uid: M:Table::System#IO#Config#_Line.GetNoTables:Integer
- syntax:
    content: 'procedure GetLineStatusWeight(): Decimal'
    return:
      returnType:
        name: Decimal
        isExternal: true
  name: GetLineStatusWeight
  uid: M:Table::System#IO#Config#_Line.GetLineStatusWeight:Decimal
- syntax:
    content: 'procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)'
    parameters:
    - id: NewHideValidationDialog
      parameterType:
        name: Boolean
        isExternal: true
  name: SetHideValidationDialog
  uid: M:Table::System#IO#Config#_Line.SetHideValidationDialog(Boolean)
- syntax:
    content: 'procedure GetNoOfRecords(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetNoOfRecords
  uid: M:Table::System#IO#Config#_Line.GetNoOfRecords:Integer
- syntax:
    content: 'procedure GetNoOfRecordsSourceTable(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetNoOfRecordsSourceTable
  uid: M:Table::System#IO#Config#_Line.GetNoOfRecordsSourceTable:Integer
- syntax:
    content: 'procedure GetNoOfRecordsText(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNoOfRecordsText
  uid: M:Table::System#IO#Config#_Line.GetNoOfRecordsText:Text
- syntax:
    content: procedure DeleteDuplicateLines()
  name: DeleteDuplicateLines
  uid: M:Table::System#IO#Config#_Line.DeleteDuplicateLines
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Line No."'
  uid: F:Table::System#IO#Config#_Line.Line_No#
- type:
    name: Option
    isExternal: true
  name: '"Line Type"'
  uid: F:Table::System#IO#Config#_Line.Line_Type
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Line.Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: Name
  uid: F:Table::System#IO#Config#_Line.Name[250]
- type:
    name: Text[30]
    isExternal: true
  name: '"Company Filter"'
  uid: F:Table::System#IO#Config#_Line.Company_Filter[30]
- type:
    name: Text[30]
    isExternal: true
  name: '"Company Filter (Source Table)"'
  uid: F:Table::System#IO#Config#_Line.Company_Filter_(Source_Table)[30]
- type:
    name: Integer
    isExternal: true
  name: '"No. of Records"'
  uid: F:Table::System#IO#Config#_Line.No#_of_Records
- type:
    name: Integer
    isExternal: true
  name: '"No. of Records (Source Table)"'
  uid: F:Table::System#IO#Config#_Line.No#_of_Records_(Source_Table)
- type:
    name: Boolean
    isExternal: true
  name: '"Licensed Table"'
  uid: F:Table::System#IO#Config#_Line.Licensed_Table
- type:
    name: Boolean
    isExternal: true
  name: '"Promoted Table"'
  uid: F:Table::System#IO#Config#_Line.Promoted_Table
- type:
    name: Boolean
    isExternal: true
  name: '"Dimensions as Columns"'
  uid: F:Table::System#IO#Config#_Line.Dimensions_as_Columns
- type:
    name: Boolean
    isExternal: true
  name: '"Copying Available"'
  uid: F:Table::System#IO#Config#_Line.Copying_Available
- type:
    name: Integer
    isExternal: true
  name: '"Page ID"'
  uid: F:Table::System#IO#Config#_Line.Page_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Page Caption"'
  uid: F:Table::System#IO#Config#_Line.Page_Caption[250]
- type:
    name: Date
    isExternal: true
  name: '"Starting Date"'
  uid: F:Table::System#IO#Config#_Line.Starting_Date
- type:
    name: Date
    isExternal: true
  name: '"Ending Date"'
  uid: F:Table::System#IO#Config#_Line.Ending_Date
- type:
    name: Code[50]
    isExternal: true
  name: '"Responsible ID"'
  uid: F:Table::System#IO#Config#_Line.Responsible_ID[50]
- type:
    name: Option
    isExternal: true
  name: Status
  uid: F:Table::System#IO#Config#_Line.Status
- type:
    name: Integer
    isExternal: true
  name: '"Vertical Sorting"'
  uid: F:Table::System#IO#Config#_Line.Vertical_Sorting
- type:
    name: Text[50]
    isExternal: true
  name: '"Data Origin"'
  uid: F:Table::System#IO#Config#_Line.Data_Origin[50]
- type:
    name: Text[250]
    isExternal: true
  name: Reference
  uid: F:Table::System#IO#Config#_Line.Reference[250]
- type:
    name: Boolean
    isExternal: true
  name: '"Licensed Page"'
  uid: F:Table::System#IO#Config#_Line.Licensed_Page
- type:
    name: Integer
    isExternal: true
  name: '"No. of Question Groups"'
  uid: F:Table::System#IO#Config#_Line.No#_of_Question_Groups
- type:
    name: Integer
    isExternal: true
  name: '"Parent Line No."'
  uid: F:Table::System#IO#Config#_Line.Parent_Line_No#
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Line.Package_Code[20]
- type:
    name: Text[50]
    isExternal: true
  name: '"Package Caption"'
  uid: F:Table::System#IO#Config#_Line.Package_Caption[50]
- type:
    name: Boolean
    isExternal: true
  name: '"Package Exists"'
  uid: F:Table::System#IO#Config#_Line.Package_Exists
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Line.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Line.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Line.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Line.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Line.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Line.SystemRowVersion
commentId: O:Table::System#IO#Config# Line
name: '"Config. Line"'
uid: O:Table::System#IO#Config#_Line
