### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Sent Notification Entry"
alId: ID 1514
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Sent Notification Entry
  promoted: false
- name: DrillDownPageID
  value: Sent Notification Entries
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Sent_Notification_Entries
    name: System.Environment.Configuration."Sent Notification Entries"
    isExternal: false
- name: LookupPageID
  value: Sent Notification Entries
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Sent_Notification_Entries
    name: System.Environment.Configuration."Sent Notification Entries"
    isExternal: false
- name: Permissions
  value: TableData "Sent Notification Entry" = rimd
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure GetLastEntryNo(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetLastEntryNo
  uid: M:Table::System#Environment#Configuration#Sent_Notification_Entry.GetLastEntryNo:Integer
- syntax:
    content: 'procedure NewRecord(NotificationEntry: Record "Notification Entry", NotificationContent: Text, NotificationMethod: Option)'
    parameters:
    - id: NotificationEntry
      parameterType:
        name: Record "Notification Entry"
        isExternal: true
    - id: NotificationContent
      parameterType:
        name: Text
        isExternal: true
    - id: NotificationMethod
      parameterType:
        name: Option
        isExternal: true
  name: NewRecord
  uid: M:Table::System#Environment#Configuration#Sent_Notification_Entry.NewRecord(Notification_Entry,Text,Option)
fields:
- type:
    name: Integer
    isExternal: true
  name: ID
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.ID
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
    name: System.Environment.Configuration."Notification Entry Type"
    isExternal: false
  name: Type
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Type
- type:
    name: Code[50]
    isExternal: true
  name: '"Recipient User ID"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Recipient_User_ID[50]
- type:
    name: RecordId
    isExternal: true
  name: '"Triggered By Record"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Triggered_By_Record
- type:
    name: Integer
    isExternal: true
  name: '"Link Target Page"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Link_Target_Page
- type:
    name: Text[250]
    isExternal: true
  name: '"Custom Link"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Custom_Link[250]
- type:
    name: DateTime
    isExternal: true
  name: '"Created Date-Time"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Created_Date-Time
- type:
    name: Code[50]
    isExternal: true
  name: '"Created By"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Created_By[50]
- type:
    name: DateTime
    isExternal: true
  name: '"Sent Date-Time"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Sent_Date-Time
- type:
    name: Blob
    isExternal: true
  name: '"Notification Content"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Notification_Content
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Method_Type
    name: System.Environment.Configuration."Notification Method Type"
    isExternal: false
  name: '"Notification Method"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Notification_Method
- type:
    name: Integer
    isExternal: true
  name: '"Aggregated with Entry"'
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.Aggregated_with_Entry
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Sent_Notification_Entry.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Sent Notification Entry
name: '"Sent Notification Entry"'
uid: O:Table::System#Environment#Configuration#Sent_Notification_Entry
