### YamlMime:BusinessCentralApplicationObject
fqName: System.Integration.PowerBI."Power BI User Configuration"
alId: ID 6304
namespace: System.Integration.PowerBI
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Integration.PowerBI
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Power BI User Configuration
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteReason
  value: Use table Power BI Context Settings instead. The new table does not require Profile ID, and supports multiple types of embedded elements.
  promoted: false
- name: ObsoleteState
  value: Pending
  promoted: false
- name: ObsoleteTag
  value: "23.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure CreateOrReadForCurrentUser(PageId: Text[50])'
    parameters:
    - id: PageId
      parameterType:
        name: Text[50]
        isExternal: true
  name: CreateOrReadForCurrentUser
  uid: M:Table::System#Integration#PowerBI#Power_BI_User_Configuration.CreateOrReadForCurrentUser(Text[50])
fields:
- type:
    name: Text[50]
    isExternal: true
  name: '"Page ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.Page_ID[50]
- type:
    name: Guid
    isExternal: true
  name: '"User Security ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.User_Security_ID
- type:
    name: Code[30]
    isExternal: true
  name: '"Profile ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.Profile_ID[30]
- type:
    name: Boolean
    isExternal: true
  name: '"Report Visibility"'
  obsoletion:
    state: removed
    reason: The report part visibility is now handled by the standard personalization experience. Hide the page using Personalization instead of using this value.
    version: "24.0"
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.Report_Visibility
- type:
    name: Guid
    isExternal: true
  name: '"Selected Report ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.Selected_Report_ID
- type:
    name: Boolean
    isExternal: true
  name: '"Lock to first visual"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.Lock_to_first_visual
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Integration#PowerBI#Power_BI_User_Configuration.SystemRowVersion
commentId: O:Table::System#Integration#PowerBI#Power BI User Configuration
summary: Persists the first report to be displayed to a user, depending on the page and profile/role they are using.
name: '"Power BI User Configuration"'
obsoletion:
  state: pending
  reason: Use table Power BI Context Settings instead. The new table does not require Profile ID, and supports multiple types of embedded elements.
  version: "23.0"
uid: O:Table::System#Integration#PowerBI#Power_BI_User_Configuration
