### YamlMime:BusinessCentralApplicationObject
fqName: System.Automation."Flow User Environment Buffer"
alId: ID 1544
namespace: System.Automation
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Automation
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Power Automate User Environment Buffer
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Text[50]
    isExternal: true
  name: '"Environment ID"'
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.Environment_ID[50]
- type:
    name: Text[100]
    isExternal: true
  name: '"Environment Display Name"'
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.Environment_Display_Name[100]
- type:
    name: Boolean
    isExternal: true
  name: Default
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.Default
- type:
    name: Boolean
    isExternal: true
  name: Enabled
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.Enabled
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Automation#Flow_User_Environment_Buffer.SystemRowVersion
commentId: O:Table::System#Automation#Flow User Environment Buffer
name: '"Flow User Environment Buffer"'
uid: O:Table::System#Automation#Flow_User_Environment_Buffer
