### YamlMime:BusinessCentralApplicationObject
fqName: System.Integration.PowerBI."Power BI Context Settings"
alId: ID 6314
namespace: System.Integration.PowerBI
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Integration.PowerBI
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Power BI Context Settings
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: Extensible
  value: "False"
  promoted: true
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure CreateOrUpdateSelectedElement(InputPowerBIDisplayedElement: Record "Power BI Displayed Element")'
    parameters:
    - id: InputPowerBIDisplayedElement
      parameterType:
        name: Record "Power BI Displayed Element"
        isExternal: true
  name: CreateOrUpdateSelectedElement
  uid: M:Table::System#Integration#PowerBI#Power_BI_Context_Settings.CreateOrUpdateSelectedElement(Power_BI_Displayed_Element)
- syntax:
    content: 'procedure CreateOrReadForCurrentUser(InputContext: Text[50])'
    parameters:
    - id: InputContext
      parameterType:
        name: Text[50]
        isExternal: true
  name: CreateOrReadForCurrentUser
  uid: M:Table::System#Integration#PowerBI#Power_BI_Context_Settings.CreateOrReadForCurrentUser(Text[50])
fields:
- type:
    name: Guid
    isExternal: true
  name: UserSID
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.UserSID
- type:
    name: Text[50]
    isExternal: true
  name: Context
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.Context[50]
- type:
    name: Text[2048]
    isExternal: true
  name: SelectedElementId
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SelectedElementId[2048]
- type:
    internalReference: O:Enum::System#Integration#PowerBI#Power_BI_Element_Type
    name: System.Integration.PowerBI."Power BI Element Type"
    isExternal: false
  name: SelectedElementType
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SelectedElementType
- type:
    name: Boolean
    isExternal: true
  name: LockToSelectedElement
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.LockToSelectedElement
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Integration#PowerBI#Power_BI_Context_Settings.SystemRowVersion
commentId: O:Table::System#Integration#PowerBI#Power BI Context Settings
summary: Persists the user settings for a specific Power BI context (e.g. which visual to display).
name: '"Power BI Context Settings"'
uid: O:Table::System#Integration#PowerBI#Power_BI_Context_Settings
