### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Template Header"
alId: ID 8618
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Template Header
  promoted: false
- name: LookupPageID
  value: Config. Template List
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Template_List
    name: System.IO."Config. Template List"
    isExternal: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure ConfirmNewInstance(var RecRef: RecordRef)'
    parameters:
    - id: RecRef
      parameterType:
        name: RecordRef
        isExternal: true
  name: ConfirmNewInstance
  uid: M:Table::System#IO#Config#_Template_Header.ConfirmNewInstance(RecordRef@)
- syntax:
    content: 'procedure SetTemplateEnabled(IsEnabled: Boolean)'
    parameters:
    - id: IsEnabled
      parameterType:
        name: Boolean
        isExternal: true
  name: SetTemplateEnabled
  uid: M:Table::System#IO#Config#_Template_Header.SetTemplateEnabled(Boolean)
- syntax:
    content: 'procedure SetNoSeries(NoSeries: Code[20])'
    parameters:
    - id: NoSeries
      parameterType:
        name: Code[20]
        isExternal: true
  name: SetNoSeries
  uid: M:Table::System#IO#Config#_Template_Header.SetNoSeries(Code[20])
fields:
- type:
    name: Code[10]
    isExternal: true
  name: Code
  uid: F:Table::System#IO#Config#_Template_Header.Code[10]
- type:
    name: Text[100]
    isExternal: true
  name: Description
  uid: F:Table::System#IO#Config#_Template_Header.Description[100]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Template_Header.Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Name"'
  uid: F:Table::System#IO#Config#_Template_Header.Table_Name[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Caption"'
  uid: F:Table::System#IO#Config#_Template_Header.Table_Caption[250]
- type:
    name: Boolean
    isExternal: true
  name: '"Used In Hierarchy"'
  uid: F:Table::System#IO#Config#_Template_Header.Used_In_Hierarchy
- type:
    name: Boolean
    isExternal: true
  name: Enabled
  uid: F:Table::System#IO#Config#_Template_Header.Enabled
- type:
    name: Code[20]
    isExternal: true
  name: '"Instance No. Series"'
  uid: F:Table::System#IO#Config#_Template_Header.Instance_No#_Series[20]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Template_Header.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Template_Header.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Template_Header.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Template_Header.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Template_Header.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Template_Header.SystemRowVersion
commentId: O:Table::System#IO#Config# Template Header
name: '"Config. Template Header"'
uid: O:Table::System#IO#Config#_Template_Header
