### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."My Notifications"
alId: ID 1518
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: My Notifications
  promoted: false
- name: InherentEntitlements
  value: riX
  promoted: false
- name: InherentPermissions
  value: riX
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure Disable(NotificationId: Guid): Boolean'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: Disable
  uid: M:Table::System#Environment#Configuration#My_Notifications.Disable(Guid):Boolean
- syntax:
    content: 'procedure SetStatus(NotificationId: Guid, Enable: Boolean): Boolean'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    - id: Enable
      parameterType:
        name: Boolean
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: SetStatus
  uid: M:Table::System#Environment#Configuration#My_Notifications.SetStatus(Guid,Boolean):Boolean
- syntax:
    content: 'procedure InsertDefault(NotificationId: Guid, NotificationName: Text[128], DescriptionText: Text, DefaultState: Boolean)'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    - id: NotificationName
      parameterType:
        name: Text[128]
        isExternal: true
    - id: DescriptionText
      parameterType:
        name: Text
        isExternal: true
    - id: DefaultState
      parameterType:
        name: Boolean
        isExternal: true
  name: InsertDefault
  uid: M:Table::System#Environment#Configuration#My_Notifications.InsertDefault(Guid,Text[128],Text,Boolean)
- syntax:
    content: 'procedure InsertDefaultWithTableNum(NotificationId: Guid, NotificationName: Text[128], DescriptionText: Text, TableNum: Integer)'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    - id: NotificationName
      parameterType:
        name: Text[128]
        isExternal: true
    - id: DescriptionText
      parameterType:
        name: Text
        isExternal: true
    - id: TableNum
      parameterType:
        name: Integer
        isExternal: true
  name: InsertDefaultWithTableNum
  uid: M:Table::System#Environment#Configuration#My_Notifications.InsertDefaultWithTableNum(Guid,Text[128],Text,Integer)
- syntax:
    content: 'procedure InsertDefaultWithTableNumAndFilter(NotificationId: Guid, NotificationName: Text[128], DescriptionText: Text, TableNum: Integer, Filters: Text)'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    - id: NotificationName
      parameterType:
        name: Text[128]
        isExternal: true
    - id: DescriptionText
      parameterType:
        name: Text
        isExternal: true
    - id: TableNum
      parameterType:
        name: Integer
        isExternal: true
    - id: Filters
      parameterType:
        name: Text
        isExternal: true
  name: InsertDefaultWithTableNumAndFilter
  uid: M:Table::System#Environment#Configuration#My_Notifications.InsertDefaultWithTableNumAndFilter(Guid,Text[128],Text,Integer,Text)
- syntax:
    content: 'procedure GetDescription(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetDescription
  uid: M:Table::System#Environment#Configuration#My_Notifications.GetDescription:Text
- syntax:
    content: 'procedure GetFiltersAsDisplayText(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetFiltersAsDisplayText
  uid: M:Table::System#Environment#Configuration#My_Notifications.GetFiltersAsDisplayText:Text
- syntax:
    content: 'procedure GetXmlFromTableView(TableID: Integer, View: Text): Text'
    parameters:
    - id: TableID
      parameterType:
        name: Integer
        isExternal: true
    - id: View
      parameterType:
        name: Text
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetXmlFromTableView
  uid: M:Table::System#Environment#Configuration#My_Notifications.GetXmlFromTableView(Integer,Text):Text
- syntax:
    content: 'procedure OpenFilterSettings(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: OpenFilterSettings
  uid: M:Table::System#Environment#Configuration#My_Notifications.OpenFilterSettings:Boolean
- syntax:
    content: 'procedure IsEnabledForRecord(NotificationId: Guid, Record: Variant): Boolean'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    - id: Record
      parameterType:
        name: Variant
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsEnabledForRecord
  uid: M:Table::System#Environment#Configuration#My_Notifications.IsEnabledForRecord(Guid,Variant):Boolean
- syntax:
    content: 'procedure IsEnabled(NotificationId: Guid): Boolean'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: IsEnabled
  uid: M:Table::System#Environment#Configuration#My_Notifications.IsEnabled(Guid):Boolean
events:
- syntax:
    signatures:
    - '[IntegrationEvent(False,False)]'
    content: 'procedure OnStateChanged(NotificationId: Guid, NewEnabledState: Boolean)'
    parameters:
    - id: NotificationId
      parameterType:
        name: Guid
        isExternal: true
    - id: NewEnabledState
      parameterType:
        name: Boolean
        isExternal: true
  name: OnStateChanged
  uid: M:Table::System#Environment#Configuration#My_Notifications.OnStateChanged(Guid,Boolean)
fields:
- type:
    name: Code[50]
    isExternal: true
  name: '"User Id"'
  uid: F:Table::System#Environment#Configuration#My_Notifications.User_Id[50]
- type:
    name: Guid
    isExternal: true
  name: '"Notification Id"'
  uid: F:Table::System#Environment#Configuration#My_Notifications.Notification_Id
- type:
    name: Integer
    isExternal: true
  name: '"Apply to Table Id"'
  uid: F:Table::System#Environment#Configuration#My_Notifications.Apply_to_Table_Id
- type:
    name: Boolean
    isExternal: true
  name: Enabled
  uid: F:Table::System#Environment#Configuration#My_Notifications.Enabled
- type:
    name: Blob
    isExternal: true
  name: '"Apply to Table Filter"'
  uid: F:Table::System#Environment#Configuration#My_Notifications.Apply_to_Table_Filter
- type:
    name: Text[128]
    isExternal: true
  name: Name
  uid: F:Table::System#Environment#Configuration#My_Notifications.Name[128]
- type:
    name: Blob
    isExternal: true
  name: Description
  uid: F:Table::System#Environment#Configuration#My_Notifications.Description
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#My_Notifications.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#My_Notifications.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#My_Notifications.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#My_Notifications.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#My_Notifications.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#My_Notifications.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#My Notifications
name: '"My Notifications"'
uid: O:Table::System#Environment#Configuration#My_Notifications
