### YamlMime:BusinessCentralApplicationObject
fqName: System.Integration.PowerBI."Power BI Report Configuration"
alId: ID 6301
namespace: System.Integration.PowerBI
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Integration.PowerBI
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Power BI Report Configuration
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteReason
  value: Use table Power BI Selected Elements instead. The new table supports multiple types of embedded elements.
  promoted: false
- name: ObsoleteState
  value: Pending
  promoted: false
- name: ObsoleteTag
  value: "23.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"User Security ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.User_Security_ID
- type:
    name: Guid
    isExternal: true
  name: '"Report ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.Report_ID
- type:
    name: Text[30]
    isExternal: true
  name: Context
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.Context[30]
- type:
    name: Text[250]
    isExternal: true
  name: EmbedUrl
  obsoletion:
    state: removed
    reason: The field has been extended to a bigger field. Use ReportEmbedUrl field instead.
    version: "19.0"
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.EmbedUrl[250]
- type:
    name: Text[200]
    isExternal: true
  name: ReportName
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.ReportName[200]
- type:
    name: Text[2048]
    isExternal: true
  name: ReportEmbedUrl
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.ReportEmbedUrl[2048]
- type:
    name: Guid
    isExternal: true
  name: '"Workspace ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.Workspace_ID
- type:
    name: Text[200]
    isExternal: true
  name: '"Workspace Name"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.Workspace_Name[200]
- type:
    name: Text[200]
    isExternal: true
  name: '"Report Page"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.Report_Page[200]
- type:
    name: Boolean
    isExternal: true
  name: '"Show Panes"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.Show_Panes
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Integration#PowerBI#Power_BI_Report_Configuration.SystemRowVersion
commentId: O:Table::System#Integration#PowerBI#Power BI Report Configuration
summary: Saves a list of reports to be displayed for a user in each specific context.
name: '"Power BI Report Configuration"'
obsoletion:
  state: pending
  reason: Use table Power BI Selected Elements instead. The new table supports multiple types of embedded elements.
  version: "23.0"
uid: O:Table::System#Integration#PowerBI#Power_BI_Report_Configuration
