### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Data"
alId: ID 8615
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Package Data
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Package_Data.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Package_Data.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"No."'
  uid: F:Table::System#IO#Config#_Package_Data.No#
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Package_Data.Field_ID
- type:
    name: Text[2048]
    isExternal: true
  name: Value
  uid: F:Table::System#IO#Config#_Package_Data.Value[2048]
- type:
    name: Boolean
    isExternal: true
  name: Invalid
  uid: F:Table::System#IO#Config#_Package_Data.Invalid
- type:
    name: Blob
    isExternal: true
  name: '"BLOB Value"'
  uid: F:Table::System#IO#Config#_Package_Data.BLOB_Value
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Package_Data.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Package_Data.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Package_Data.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Package_Data.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Package_Data.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Package_Data.SystemRowVersion
commentId: O:Table::System#IO#Config# Package Data
name: '"Config. Package Data"'
uid: O:Table::System#IO#Config#_Package_Data
