### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Filter"
alId: ID 8626
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Package Filter
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Package_Filter.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Package_Filter.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Processing Rule No."'
  uid: F:Table::System#IO#Config#_Package_Filter.Processing_Rule_No#
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Package_Filter.Field_ID
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Package_Filter.Field_Name[30]
- type:
    name: Text[250]
    isExternal: true
  name: '"Field Caption"'
  uid: F:Table::System#IO#Config#_Package_Filter.Field_Caption[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Field Filter"'
  uid: F:Table::System#IO#Config#_Package_Filter.Field_Filter[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Package_Filter.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Package_Filter.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Package_Filter.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Package_Filter.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Package_Filter.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Package_Filter.SystemRowVersion
commentId: O:Table::System#IO#Config# Package Filter
name: '"Config. Package Filter"'
uid: O:Table::System#IO#Config#_Package_Filter
