### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Experience Tier Buffer"
alId: ID 9177
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Experience Tier Buffer
  promoted: false
- name: LookupPageID
  value: Experience Tiers
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Experience_Tiers
    name: System.Environment.Configuration."Experience Tiers"
    isExternal: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Field No."'
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.Field_No#
- type:
    name: Text[30]
    isExternal: true
  name: '"Experience Tier"'
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.Experience_Tier[30]
- type:
    name: Boolean
    isExternal: true
  name: Selected
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.Selected
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Experience_Tier_Buffer.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Experience Tier Buffer
name: '"Experience Tier Buffer"'
uid: O:Table::System#Environment#Configuration#Experience_Tier_Buffer
