### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Record"
alId: ID 8614
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Package Record
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure FitsProcessingFilter(RuleNo: Integer): Boolean'
    parameters:
    - id: RuleNo
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: FitsProcessingFilter
  uid: M:Table::System#IO#Config#_Package_Record.FitsProcessingFilter(Integer):Boolean
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Package_Record.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Package_Record.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"No."'
  uid: F:Table::System#IO#Config#_Package_Record.No#
- type:
    name: Boolean
    isExternal: true
  name: Invalid
  uid: F:Table::System#IO#Config#_Package_Record.Invalid
- type:
    name: Integer
    isExternal: true
  name: '"Parent Record No."'
  uid: F:Table::System#IO#Config#_Package_Record.Parent_Record_No#
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Package_Record.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Package_Record.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Package_Record.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Package_Record.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Package_Record.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Package_Record.SystemRowVersion
commentId: O:Table::System#IO#Config# Package Record
name: '"Config. Package Record"'
uid: O:Table::System#IO#Config#_Package_Record
