### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Entry"
alId: ID 1511
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Notification Entry
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure CreateNotificationEntry(NewType: Enum "Notification Entry Type", RecipientUserID: Code[50], NewRecord: Variant, NewLinkTargetPage: Integer, NewCustomLink: Text[250], NewSenderUserID: Code[50])'
    parameters:
    - id: NewType
      parameterType:
        internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
        name: System.Environment.Configuration."Notification Entry Type"
        isExternal: false
    - id: RecipientUserID
      parameterType:
        name: Code[50]
        isExternal: true
    - id: NewRecord
      parameterType:
        name: Variant
        isExternal: true
    - id: NewLinkTargetPage
      parameterType:
        name: Integer
        isExternal: true
    - id: NewCustomLink
      parameterType:
        name: Text[250]
        isExternal: true
    - id: NewSenderUserID
      parameterType:
        name: Code[50]
        isExternal: true
  name: CreateNotificationEntry
  uid: M:Table::System#Environment#Configuration#Notification_Entry.CreateNotificationEntry(Enum::System#Environment#Configuration#Notification_Entry_Type,Code[50],Variant,Integer,Text[250],Code[50])
- syntax:
    content: 'procedure InsertRec(NewType: Enum "Notification Entry Type", NewUserID: Code[50], NewRecordID: RecordId, NewLinkTargetPage: Integer, NewCustomLink: Text[250], NewSenderUserID: Code[50]): Boolean'
    parameters:
    - id: NewType
      parameterType:
        internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
        name: System.Environment.Configuration."Notification Entry Type"
        isExternal: false
    - id: NewUserID
      parameterType:
        name: Code[50]
        isExternal: true
    - id: NewRecordID
      parameterType:
        name: RecordId
        isExternal: true
    - id: NewLinkTargetPage
      parameterType:
        name: Integer
        isExternal: true
    - id: NewCustomLink
      parameterType:
        name: Text[250]
        isExternal: true
    - id: NewSenderUserID
      parameterType:
        name: Code[50]
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: InsertRec
  uid: M:Table::System#Environment#Configuration#Notification_Entry.InsertRec(Enum::System#Environment#Configuration#Notification_Entry_Type,Code[50],RecordId,Integer,Text[250],Code[50]):Boolean
fields:
- type:
    name: Integer
    isExternal: true
  name: ID
  uid: F:Table::System#Environment#Configuration#Notification_Entry.ID
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
    name: System.Environment.Configuration."Notification Entry Type"
    isExternal: false
  name: Type
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Type
- type:
    name: Code[50]
    isExternal: true
  name: '"Recipient User ID"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Recipient_User_ID[50]
- type:
    name: RecordId
    isExternal: true
  name: '"Triggered By Record"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Triggered_By_Record
- type:
    name: Integer
    isExternal: true
  name: '"Link Target Page"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Link_Target_Page
- type:
    name: Text[250]
    isExternal: true
  name: '"Custom Link"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Custom_Link[250]
- type:
    name: Text[2048]
    isExternal: true
  name: '"Error Message"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Error_Message[2048]
- type:
    name: DateTime
    isExternal: true
  name: '"Created Date-Time"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Created_Date-Time
- type:
    name: Code[50]
    isExternal: true
  name: '"Created By"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Created_By[50]
- type:
    name: Text[250]
    isExternal: true
  name: '"Error Message 2"'
  obsoletion:
    state: removed
    reason: 'Error Message field size has been increased '
    version: "18.0"
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Error_Message_2[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Error Message 3"'
  obsoletion:
    state: removed
    reason: 'Error Message field size has been increased '
    version: "18.0"
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Error_Message_3[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Error Message 4"'
  obsoletion:
    state: removed
    reason: 'Error Message field size has been increased '
    version: "18.0"
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Error_Message_4[250]
- type:
    name: Code[50]
    isExternal: true
  name: '"Sender User ID"'
  uid: F:Table::System#Environment#Configuration#Notification_Entry.Sender_User_ID[50]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Notification_Entry.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Notification_Entry.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Notification_Entry.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Notification_Entry.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Notification_Entry.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Notification_Entry.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Notification Entry
name: '"Notification Entry"'
uid: O:Table::System#Environment#Configuration#Notification_Entry
