### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Field Mapping"
alId: ID 8628
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Field Mapping
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteState
  value: Removed
  promoted: false
- name: ObsoleteReason
  value: Replaced by Config. Field Map table with increased length for old and new values.
  promoted: false
- name: ObsoleteTag
  value: "19.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Field_Mapping.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Field_Mapping.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Field_Mapping.Field_ID
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Field_Mapping.Field_Name[30]
- type:
    name: Text[250]
    isExternal: true
  name: '"Old Value"'
  uid: F:Table::System#IO#Config#_Field_Mapping.Old_Value[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"New Value"'
  uid: F:Table::System#IO#Config#_Field_Mapping.New_Value[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Field_Mapping.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Field_Mapping.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Field_Mapping.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Field_Mapping.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Field_Mapping.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Field_Mapping.SystemRowVersion
commentId: O:Table::System#IO#Config# Field Mapping
name: '"Config. Field Mapping"'
obsoletion:
  state: removed
  reason: Replaced by Config. Field Map table with increased length for old and new values.
  version: "19.0"
uid: O:Table::System#IO#Config#_Field_Mapping
