### YamlMime:BusinessCentralApplicationObject
fqName: System.Integration.PowerBI."Power BI Ongoing Deployments"
alId: ID 6308
namespace: System.Integration.PowerBI
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Integration.PowerBI
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Power BI Ongoing Deployments
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteReason
  value: 'Functionality has been moved to table 6325 "Power BI User Status" (notice: the new table is per company)'
  promoted: false
- name: ObsoleteState
  value: Removed
  promoted: false
- name: ObsoleteTag
  value: "21.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"User Security ID"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.User_Security_ID
- type:
    name: Boolean
    isExternal: true
  name: '"Is Deploying Reports"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.Is_Deploying_Reports
- type:
    name: Boolean
    isExternal: true
  name: '"Is Retrying Uploads"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.Is_Retrying_Uploads
- type:
    name: Boolean
    isExternal: true
  name: '"Is Deleting Reports"'
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.Is_Deleting_Reports
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments.SystemRowVersion
commentId: O:Table::System#Integration#PowerBI#Power BI Ongoing Deployments
summary: Tracks if a user has active background sessions to deploy, delete or retry deployment of Power BI reports.
name: '"Power BI Ongoing Deployments"'
obsoletion:
  state: removed
  reason: 'Functionality has been moved to table 6325 "Power BI User Status" (notice: the new table is per company)'
  version: "21.0"
uid: O:Table::System#Integration#PowerBI#Power_BI_Ongoing_Deployments
