### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Selection"
alId: ID 8621
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Selection
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Line No."'
  uid: F:Table::System#IO#Config#_Selection.Line_No#
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Selection.Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: Name
  uid: F:Table::System#IO#Config#_Selection.Name[250]
- type:
    name: Option
    isExternal: true
  name: '"Line Type"'
  uid: F:Table::System#IO#Config#_Selection.Line_Type
- type:
    name: Integer
    isExternal: true
  name: '"Parent Line No."'
  uid: F:Table::System#IO#Config#_Selection.Parent_Line_No#
- type:
    name: Boolean
    isExternal: true
  name: Selected
  uid: F:Table::System#IO#Config#_Selection.Selected
- type:
    name: Integer
    isExternal: true
  name: '"Vertical Sorting"'
  uid: F:Table::System#IO#Config#_Selection.Vertical_Sorting
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Selection.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Selection.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Selection.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Selection.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Selection.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Selection.SystemRowVersion
commentId: O:Table::System#IO#Config# Selection
name: '"Config. Selection"'
uid: O:Table::System#IO#Config#_Selection
