### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Question"
alId: ID 8612
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Question
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: procedure FieldLookup()
  name: FieldLookup
  uid: M:Table::System#IO#Config#_Question.FieldLookup
- syntax:
    content: 'procedure LookupValue(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: LookupValue
  uid: M:Table::System#IO#Config#_Question.LookupValue:Text
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Questionnaire Code"'
  uid: F:Table::System#IO#Config#_Question.Questionnaire_Code[10]
- type:
    name: Code[10]
    isExternal: true
  name: '"Question Area Code"'
  uid: F:Table::System#IO#Config#_Question.Question_Area_Code[10]
- type:
    name: Integer
    isExternal: true
  name: '"No."'
  uid: F:Table::System#IO#Config#_Question.No#
- type:
    name: Text[250]
    isExternal: true
  name: Question
  uid: F:Table::System#IO#Config#_Question.Question[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Answer Option"'
  uid: F:Table::System#IO#Config#_Question.Answer_Option[250]
- type:
    name: Text[250]
    isExternal: true
  name: Answer
  uid: F:Table::System#IO#Config#_Question.Answer[250]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Question.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Question.Field_ID
- type:
    name: Text[250]
    isExternal: true
  name: Reference
  uid: F:Table::System#IO#Config#_Question.Reference[250]
- type:
    name: Text[30]
    isExternal: true
  name: '"Question Origin"'
  uid: F:Table::System#IO#Config#_Question.Question_Origin[30]
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Question.Field_Name[30]
- type:
    name: Text[250]
    isExternal: true
  name: '"Field Caption"'
  uid: F:Table::System#IO#Config#_Question.Field_Caption[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Question.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Question.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Question.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Question.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Question.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Question.SystemRowVersion
commentId: O:Table::System#IO#Config# Question
name: '"Config. Question"'
uid: O:Table::System#IO#Config#_Question
