### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Resource Import/Export"
alId: ID 9170
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Profile Resource Import/Export
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: ObsoleteState
  value: Removed
  promoted: false
- name: ObsoleteReason
  value: Importing and exporting profile resources is no longer supported. AL profiles and customizations should be used instead.
  promoted: false
- name: ObsoleteTag
  value: "18.0"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure InsertRec(ProfileID: Code[30], PageID: Integer, PersonalizationID: Code[40], ControlGUID: Code[40], Language: Code[3], Translation: Text[250])'
    parameters:
    - id: ProfileID
      parameterType:
        name: Code[30]
        isExternal: true
    - id: PageID
      parameterType:
        name: Integer
        isExternal: true
    - id: PersonalizationID
      parameterType:
        name: Code[40]
        isExternal: true
    - id: ControlGUID
      parameterType:
        name: Code[40]
        isExternal: true
    - id: Language
      parameterType:
        name: Code[3]
        isExternal: true
    - id: Translation
      parameterType:
        name: Text[250]
        isExternal: true
  name: InsertRec
  uid: M:Table::System#Environment#Configuration#Profile_Resource_Import/Export.InsertRec(Code[30],Integer,Code[40],Code[40],Code[3],Text[250])
fields:
- type:
    name: Code[30]
    isExternal: true
  name: '"Profile ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.Profile_ID[30]
- type:
    name: Integer
    isExternal: true
  name: '"Page ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.Page_ID
- type:
    name: Code[40]
    isExternal: true
  name: '"Personalization ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.Personalization_ID[40]
- type:
    name: Code[40]
    isExternal: true
  name: '"Control GUID"'
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.Control_GUID[40]
- type:
    name: Code[3]
    isExternal: true
  name: '"Abbreviated Language Name"'
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.Abbreviated_Language_Name[3]
- type:
    name: Text[250]
    isExternal: true
  name: Value
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.Value[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Profile_Resource_Import/Export.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Profile Resource Import/Export
name: '"Profile Resource Import/Export"'
obsoletion:
  state: removed
  reason: Importing and exporting profile resources is no longer supported. AL profiles and customizations should be used instead.
  version: "18.0"
uid: O:Table::System#Environment#Configuration#Profile_Resource_Import/Export
