### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Related Field"
alId: ID 8624
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Related Field
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Related_Field.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Related_Field.Field_ID
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Related_Field.Field_Name[30]
- type:
    name: Text[250]
    isExternal: true
  name: '"Field Caption"'
  uid: F:Table::System#IO#Config#_Related_Field.Field_Caption[250]
- type:
    name: Integer
    isExternal: true
  name: '"Relation Table ID"'
  uid: F:Table::System#IO#Config#_Related_Field.Relation_Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Relation Table Name"'
  uid: F:Table::System#IO#Config#_Related_Field.Relation_Table_Name[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Related_Field.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Related_Field.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Related_Field.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Related_Field.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Related_Field.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Related_Field.SystemRowVersion
commentId: O:Table::System#IO#Config# Related Field
name: '"Config. Related Field"'
uid: O:Table::System#IO#Config#_Related_Field
