### YamlMime:BusinessCentralApplicationObject
fqName: System.Automation."Flow User Environment Config"
alId: ID 1545
namespace: System.Automation
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Automation
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Power Automate User Environment Config
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"User Security ID"'
  uid: F:Table::System#Automation#Flow_User_Environment_Config.User_Security_ID
- type:
    name: Text[50]
    isExternal: true
  name: '"Environment ID"'
  uid: F:Table::System#Automation#Flow_User_Environment_Config.Environment_ID[50]
- type:
    name: Text[100]
    isExternal: true
  name: '"Environment Display Name"'
  uid: F:Table::System#Automation#Flow_User_Environment_Config.Environment_Display_Name[100]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Automation#Flow_User_Environment_Config.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Automation#Flow_User_Environment_Config.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Automation#Flow_User_Environment_Config.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Automation#Flow_User_Environment_Config.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Automation#Flow_User_Environment_Config.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Automation#Flow_User_Environment_Config.SystemRowVersion
commentId: O:Table::System#Automation#Flow User Environment Config
name: '"Flow User Environment Config"'
uid: O:Table::System#Automation#Flow_User_Environment_Config
