### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Question Area"
alId: ID 8611
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Question Area
  promoted: false
- name: LookupPageID
  value: Config. Question Areas
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Question_Areas
    name: System.IO."Config. Question Areas"
    isExternal: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Questionnaire Code"'
  uid: F:Table::System#IO#Config#_Question_Area.Questionnaire_Code[10]
- type:
    name: Code[10]
    isExternal: true
  name: Code
  uid: F:Table::System#IO#Config#_Question_Area.Code[10]
- type:
    name: Text[100]
    isExternal: true
  name: Description
  uid: F:Table::System#IO#Config#_Question_Area.Description[100]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Question_Area.Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Name"'
  uid: F:Table::System#IO#Config#_Question_Area.Table_Name[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Caption"'
  uid: F:Table::System#IO#Config#_Question_Area.Table_Caption[250]
- type:
    name: Integer
    isExternal: true
  name: '"No. of Questions"'
  uid: F:Table::System#IO#Config#_Question_Area.No#_of_Questions
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Question_Area.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Question_Area.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Question_Area.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Question_Area.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Question_Area.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Question_Area.SystemRowVersion
commentId: O:Table::System#IO#Config# Question Area
name: '"Config. Question Area"'
uid: O:Table::System#IO#Config#_Question_Area
