### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Template Line"
alId: ID 8619
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Template Line
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: procedure SelectFieldName()
  name: SelectFieldName
  uid: M:Table::System#IO#Config#_Template_Line.SelectFieldName
- syntax:
    content: 'procedure GetLine(var ConfigTemplateLine: Record "Config. Template Line", DataTemplateCode: Code[10], FieldID: Integer): Boolean'
    parameters:
    - id: ConfigTemplateLine
      parameterType:
        name: Record "Config. Template Line"
        isExternal: true
    - id: DataTemplateCode
      parameterType:
        name: Code[10]
        isExternal: true
    - id: FieldID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: GetLine
  uid: M:Table::System#IO#Config#_Template_Line.GetLine(Config#_Template_Line@,Code[10],Integer):Boolean
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Data Template Code"'
  uid: F:Table::System#IO#Config#_Template_Line.Data_Template_Code[10]
- type:
    name: Integer
    isExternal: true
  name: '"Line No."'
  uid: F:Table::System#IO#Config#_Template_Line.Line_No#
- type:
    internalReference: O:Enum::System#IO#Config#_Template_Line_Type
    name: System.IO."Config. Template Line Type"
    isExternal: false
  name: Type
  uid: F:Table::System#IO#Config#_Template_Line.Type
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Template_Line.Field_ID
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Template_Line.Field_Name[30]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Template_Line.Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Name"'
  uid: F:Table::System#IO#Config#_Template_Line.Table_Name[250]
- type:
    name: Code[10]
    isExternal: true
  name: '"Template Code"'
  uid: F:Table::System#IO#Config#_Template_Line.Template_Code[10]
- type:
    name: Text[100]
    isExternal: true
  name: '"Template Description"'
  uid: F:Table::System#IO#Config#_Template_Line.Template_Description[100]
- type:
    name: Boolean
    isExternal: true
  name: Mandatory
  uid: F:Table::System#IO#Config#_Template_Line.Mandatory
- type:
    name: Text[250]
    isExternal: true
  name: Reference
  uid: F:Table::System#IO#Config#_Template_Line.Reference[250]
- type:
    name: Text[2048]
    isExternal: true
  name: '"Default Value"'
  uid: F:Table::System#IO#Config#_Template_Line.Default_Value[2048]
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Caption"'
  uid: F:Table::System#IO#Config#_Template_Line.Table_Caption[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Field Caption"'
  uid: F:Table::System#IO#Config#_Template_Line.Field_Caption[250]
- type:
    name: Boolean
    isExternal: true
  name: '"Skip Relation Check"'
  uid: F:Table::System#IO#Config#_Template_Line.Skip_Relation_Check
- type:
    name: Integer
    isExternal: true
  name: '"Language ID"'
  uid: F:Table::System#IO#Config#_Template_Line.Language_ID
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Template_Line.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Template_Line.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Template_Line.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Template_Line.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Template_Line.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Template_Line.SystemRowVersion
commentId: O:Table::System#IO#Config# Template Line
name: '"Config. Template Line"'
uid: O:Table::System#IO#Config#_Template_Line
