### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Designer Diagnostic"
alId: ID 9197
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"Import ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.Import_ID
- type:
    name: Integer
    isExternal: true
  name: '"Diagnostics ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.Diagnostics_ID
- type:
    name: Guid
    isExternal: true
  name: '"Profile App ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.Profile_App_ID
- type:
    name: Code[30]
    isExternal: true
  name: '"Profile ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.Profile_ID[30]
- type:
    internalReference: O:Enum::System#Tooling#Severity
    name: System.Tooling.Severity
    isExternal: false
  name: Severity
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.Severity
- type:
    name: Text[2048]
    isExternal: true
  name: Message
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.Message[2048]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Profile_Designer_Diagnostic.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Profile Designer Diagnostic
name: '"Profile Designer Diagnostic"'
uid: O:Table::System#Environment#Configuration#Profile_Designer_Diagnostic
