### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package"
alId: ID 8623
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Package
  promoted: false
- name: LookupPageID
  value: Config. Packages
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Packages
    name: System.IO."Config. Packages"
    isExternal: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[20]
    isExternal: true
  name: Code
  uid: F:Table::System#IO#Config#_Package.Code[20]
- type:
    name: Text[50]
    isExternal: true
  name: '"Package Name"'
  uid: F:Table::System#IO#Config#_Package.Package_Name[50]
- type:
    name: Integer
    isExternal: true
  name: '"Language ID"'
  uid: F:Table::System#IO#Config#_Package.Language_ID
- type:
    name: Integer
    isExternal: true
  name: '"No. of Tables"'
  uid: F:Table::System#IO#Config#_Package.No#_of_Tables
- type:
    name: Text[248]
    isExternal: true
  name: '"Product Version"'
  uid: F:Table::System#IO#Config#_Package.Product_Version[248]
- type:
    name: Boolean
    isExternal: true
  name: '"Exclude Config. Tables"'
  uid: F:Table::System#IO#Config#_Package.Exclude_Config#_Tables
- type:
    name: Integer
    isExternal: true
  name: '"Processing Order"'
  uid: F:Table::System#IO#Config#_Package.Processing_Order
- type:
    name: Integer
    isExternal: true
  name: '"No. of Records"'
  uid: F:Table::System#IO#Config#_Package.No#_of_Records
- type:
    name: Integer
    isExternal: true
  name: '"No. of Errors"'
  uid: F:Table::System#IO#Config#_Package.No#_of_Errors
- type:
    name: Option
    isExternal: true
  name: '"Import Status"'
  uid: F:Table::System#IO#Config#_Package.Import_Status
- type:
    name: Option
    isExternal: true
  name: '"Apply Status"'
  uid: F:Table::System#IO#Config#_Package.Apply_Status
- type:
    name: Integer
    isExternal: true
  name: '"Min. Count For Async Import"'
  uid: F:Table::System#IO#Config#_Package.Min#_Count_For_Async_Import
- type:
    name: Text[2048]
    isExternal: true
  name: '"Import Error"'
  uid: F:Table::System#IO#Config#_Package.Import_Error[2048]
- type:
    name: Text[2048]
    isExternal: true
  name: '"Apply Error"'
  uid: F:Table::System#IO#Config#_Package.Apply_Error[2048]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Package.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Package.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Package.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Package.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Package.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Package.SystemRowVersion
commentId: O:Table::System#IO#Config# Package
name: '"Config. Package"'
uid: O:Table::System#IO#Config#_Package
