### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Schedule"
alId: ID 1513
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Notification Schedule
  promoted: false
- name: DrillDownPageID
  value: Notification Schedule
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Notification_Schedule
    name: System.Environment.Configuration."Notification Schedule"
    isExternal: false
- name: LookupPageID
  value: Notification Schedule
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Notification_Schedule
    name: System.Environment.Configuration."Notification Schedule"
    isExternal: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure CreateNewRecord(NewUserID: Code[50], NewNotificationType: Enum "Notification Entry Type")'
    parameters:
    - id: NewUserID
      parameterType:
        name: Code[50]
        isExternal: true
    - id: NewNotificationType
      parameterType:
        internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
        name: System.Environment.Configuration."Notification Entry Type"
        isExternal: false
  name: CreateNewRecord
  uid: M:Table::System#Environment#Configuration#Notification_Schedule.CreateNewRecord(Code[50],Enum::System#Environment#Configuration#Notification_Entry_Type)
- syntax:
    content: 'procedure CalculateExecutionTime(DateTime: DateTime): DateTime'
    parameters:
    - id: DateTime
      parameterType:
        name: DateTime
        isExternal: true
    return:
      returnType:
        name: DateTime
        isExternal: true
  name: CalculateExecutionTime
  uid: M:Table::System#Environment#Configuration#Notification_Schedule.CalculateExecutionTime(DateTime):DateTime
- syntax:
    content: 'procedure ScheduleNotification(NotificationEntry: Record "Notification Entry")'
    parameters:
    - id: NotificationEntry
      parameterType:
        name: Record "Notification Entry"
        isExternal: true
  name: ScheduleNotification
  uid: M:Table::System#Environment#Configuration#Notification_Schedule.ScheduleNotification(Notification_Entry)
fields:
- type:
    name: Code[50]
    isExternal: true
  name: '"User ID"'
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.User_ID[50]
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
    name: System.Environment.Configuration."Notification Entry Type"
    isExternal: false
  name: '"Notification Type"'
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Notification_Type
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Schedule_Type
    name: System.Environment.Configuration."Notification Schedule Type"
    isExternal: false
  name: Recurrence
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Recurrence
- type:
    name: Time
    isExternal: true
  name: Time
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Time
- type:
    name: Option
    isExternal: true
  name: '"Daily Frequency"'
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Daily_Frequency
- type:
    name: Boolean
    isExternal: true
  name: Monday
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Monday
- type:
    name: Boolean
    isExternal: true
  name: Tuesday
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Tuesday
- type:
    name: Boolean
    isExternal: true
  name: Wednesday
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Wednesday
- type:
    name: Boolean
    isExternal: true
  name: Thursday
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Thursday
- type:
    name: Boolean
    isExternal: true
  name: Friday
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Friday
- type:
    name: Boolean
    isExternal: true
  name: Saturday
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Saturday
- type:
    name: Boolean
    isExternal: true
  name: Sunday
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Sunday
- type:
    name: Integer
    isExternal: true
  name: '"Date of Month"'
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Date_of_Month
- type:
    name: Option
    isExternal: true
  name: '"Monthly Notification Date"'
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Monthly_Notification_Date
- type:
    name: Guid
    isExternal: true
  name: '"Last Scheduled Job"'
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.Last_Scheduled_Job
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Notification_Schedule.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Notification Schedule
name: '"Notification Schedule"'
uid: O:Table::System#Environment#Configuration#Notification_Schedule
