### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Setup"
alId: ID 1512
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Notification Setup
  promoted: false
- name: DrillDownPageID
  value: Notification Setup
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Notification_Setup
    name: System.Environment.Configuration."Notification Setup"
    isExternal: false
- name: LookupPageID
  value: Notification Setup
  promoted: false
  xrefType:
    internalReference: O:Page::System#Environment#Configuration#Notification_Setup
    name: System.Environment.Configuration."Notification Setup"
    isExternal: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure GetNotificationTypeSetup(NotificationType: Enum "Notification Entry Type")'
    parameters:
    - id: NotificationType
      parameterType:
        internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
        name: System.Environment.Configuration."Notification Entry Type"
        isExternal: false
  name: GetNotificationTypeSetup
  uid: M:Table::System#Environment#Configuration#Notification_Setup.GetNotificationTypeSetup(Enum::System#Environment#Configuration#Notification_Entry_Type)
- syntax:
    content: 'procedure GetNotificationTypeSetupForUser(NotificationType: Enum "Notification Entry Type", RecipientUserID: Code[50])'
    parameters:
    - id: NotificationType
      parameterType:
        internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
        name: System.Environment.Configuration."Notification Entry Type"
        isExternal: false
    - id: RecipientUserID
      parameterType:
        name: Code[50]
        isExternal: true
  name: GetNotificationTypeSetupForUser
  uid: M:Table::System#Environment#Configuration#Notification_Setup.GetNotificationTypeSetupForUser(Enum::System#Environment#Configuration#Notification_Entry_Type,Code[50])
fields:
- type:
    name: Code[50]
    isExternal: true
  name: '"User ID"'
  uid: F:Table::System#Environment#Configuration#Notification_Setup.User_ID[50]
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Entry_Type
    name: System.Environment.Configuration."Notification Entry Type"
    isExternal: false
  name: '"Notification Type"'
  uid: F:Table::System#Environment#Configuration#Notification_Setup.Notification_Type
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Method_Type
    name: System.Environment.Configuration."Notification Method Type"
    isExternal: false
  name: '"Notification Method"'
  uid: F:Table::System#Environment#Configuration#Notification_Setup.Notification_Method
- type:
    internalReference: O:Enum::System#Environment#Configuration#Notification_Schedule_Type
    name: System.Environment.Configuration."Notification Schedule Type"
    isExternal: false
  name: Schedule
  uid: F:Table::System#Environment#Configuration#Notification_Setup.Schedule
- type:
    name: Option
    isExternal: true
  name: '"Display Target"'
  obsoletion:
    state: removed
    reason: The Windows client is discontinued.
    version: "15.0"
  uid: F:Table::System#Environment#Configuration#Notification_Setup.Display_Target
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Notification_Setup.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Notification_Setup.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Notification_Setup.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Notification_Setup.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Notification_Setup.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Notification_Setup.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Notification Setup
name: '"Notification Setup"'
uid: O:Table::System#Environment#Configuration#Notification_Setup
