### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Application Area Buffer"
alId: ID 9179
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Application Area Buffer
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Field No."'
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.Field_No#
- type:
    name: Text[80]
    isExternal: true
  name: '"Application Area"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.Application_Area[80]
- type:
    name: Boolean
    isExternal: true
  name: Selected
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.Selected
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Application_Area_Buffer.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Application Area Buffer
name: '"Application Area Buffer"'
uid: O:Table::System#Environment#Configuration#Application_Area_Buffer
