### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Profile Import"
alId: ID 9171
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"App ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Import.App_ID
- type:
    name: Code[30]
    isExternal: true
  name: '"Profile ID"'
  uid: F:Table::System#Environment#Configuration#Profile_Import.Profile_ID[30]
- type:
    name: Boolean
    isExternal: true
  name: Exists
  uid: F:Table::System#Environment#Configuration#Profile_Import.Exists
- type:
    name: Boolean
    isExternal: true
  name: Selected
  uid: F:Table::System#Environment#Configuration#Profile_Import.Selected
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Profile_Import.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Profile_Import.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Profile_Import.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Profile_Import.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Profile_Import.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Profile_Import.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Profile Import
name: '"Profile Import"'
uid: O:Table::System#Environment#Configuration#Profile_Import
