### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Media Buffer"
alId: ID 8630
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Media Buffer
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure GetNextNo(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetNextNo
  uid: M:Table::System#IO#Config#_Media_Buffer.GetNextNo:Integer
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Media_Buffer.Package_Code[20]
- type:
    name: Guid
    isExternal: true
  name: '"Media Set ID"'
  uid: F:Table::System#IO#Config#_Media_Buffer.Media_Set_ID
- type:
    name: Guid
    isExternal: true
  name: '"Media ID"'
  uid: F:Table::System#IO#Config#_Media_Buffer.Media_ID
- type:
    name: Integer
    isExternal: true
  name: '"No."'
  uid: F:Table::System#IO#Config#_Media_Buffer.No#
- type:
    name: Blob
    isExternal: true
  name: '"Media Blob"'
  uid: F:Table::System#IO#Config#_Media_Buffer.Media_Blob
- type:
    name: MediaSet
    isExternal: true
  name: '"Media Set"'
  uid: F:Table::System#IO#Config#_Media_Buffer.Media_Set
- type:
    name: Media
    isExternal: true
  name: Media
  uid: F:Table::System#IO#Config#_Media_Buffer.Media
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Media_Buffer.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Media_Buffer.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Media_Buffer.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Media_Buffer.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Media_Buffer.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Media_Buffer.SystemRowVersion
commentId: O:Table::System#IO#Config# Media Buffer
name: '"Config. Media Buffer"'
uid: O:Table::System#IO#Config#_Media_Buffer
