### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Context"
alId: ID 1519
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Notification Context
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Guid
    isExternal: true
  name: '"Notification ID"'
  uid: F:Table::System#Environment#Configuration#Notification_Context.Notification_ID
- type:
    name: RecordId
    isExternal: true
  name: '"Record ID"'
  uid: F:Table::System#Environment#Configuration#Notification_Context.Record_ID
- type:
    name: Guid
    isExternal: true
  name: '"Additional Context ID"'
  uid: F:Table::System#Environment#Configuration#Notification_Context.Additional_Context_ID
- type:
    name: DateTime
    isExternal: true
  name: Created
  uid: F:Table::System#Environment#Configuration#Notification_Context.Created
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Notification_Context.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Notification_Context.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Notification_Context.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Notification_Context.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Notification_Context.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Notification_Context.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Notification Context
name: '"Notification Context"'
uid: O:Table::System#Environment#Configuration#Notification_Context
