### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Field Map"
alId: ID 8629
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Field Mapping
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Field_Map.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Field_Map.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Field_Map.Field_ID
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Field_Map.Field_Name[30]
- type:
    name: Text[2048]
    isExternal: true
  name: '"Old Value"'
  uid: F:Table::System#IO#Config#_Field_Map.Old_Value[2048]
- type:
    name: Text[2048]
    isExternal: true
  name: '"New Value"'
  uid: F:Table::System#IO#Config#_Field_Map.New_Value[2048]
- type:
    name: BigInteger
    isExternal: true
  name: ID
  uid: F:Table::System#IO#Config#_Field_Map.ID
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Field_Map.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Field_Map.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Field_Map.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Field_Map.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Field_Map.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Field_Map.SystemRowVersion
commentId: O:Table::System#IO#Config# Field Map
name: '"Config. Field Map"'
uid: O:Table::System#IO#Config#_Field_Map
