### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Error"
alId: ID 8617
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Package Error
  promoted: false
- name: DrillDownPageID
  value: Config. Package Errors
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Package_Errors
    name: System.IO."Config. Package Errors"
    isExternal: false
- name: LookupPageID
  value: Config. Package Errors
  promoted: false
  xrefType:
    internalReference: O:Page::System#IO#Config#_Package_Errors
    name: System.IO."Config. Package Errors"
    isExternal: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: procedure ShowRecord()
  name: ShowRecord
  uid: M:Table::System#IO#Config#_Package_Error.ShowRecord
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Package_Error.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Package_Error.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Record No."'
  uid: F:Table::System#IO#Config#_Package_Error.Record_No#
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Package_Error.Field_ID
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Package_Error.Field_Name[30]
- type:
    name: Text[250]
    isExternal: true
  name: '"Error Text"'
  uid: F:Table::System#IO#Config#_Package_Error.Error_Text[250]
- type:
    name: Text[250]
    isExternal: true
  name: '"Field Caption"'
  uid: F:Table::System#IO#Config#_Package_Error.Field_Caption[250]
- type:
    name: Option
    isExternal: true
  name: '"Error Type"'
  uid: F:Table::System#IO#Config#_Package_Error.Error_Type
- type:
    name: RecordId
    isExternal: true
  name: '"Record ID"'
  uid: F:Table::System#IO#Config#_Package_Error.Record_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Caption"'
  uid: F:Table::System#IO#Config#_Package_Error.Table_Caption[250]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Package_Error.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Package_Error.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Package_Error.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Package_Error.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Package_Error.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Package_Error.SystemRowVersion
commentId: O:Table::System#IO#Config# Package Error
name: '"Config. Package Error"'
uid: O:Table::System#IO#Config#_Package_Error
