### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."User Tours"
alId: ID 1314
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: User Tours
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure AlreadyCompleted(TourID: Integer): Boolean'
    parameters:
    - id: TourID
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: AlreadyCompleted
  uid: M:Table::System#Environment#Configuration#User_Tours.AlreadyCompleted(Integer):Boolean
- syntax:
    content: 'procedure MarkAsCompleted(TourID: Integer)'
    parameters:
    - id: TourID
      parameterType:
        name: Integer
        isExternal: true
  name: MarkAsCompleted
  uid: M:Table::System#Environment#Configuration#User_Tours.MarkAsCompleted(Integer)
fields:
- type:
    name: Text[132]
    isExternal: true
  name: '"User ID"'
  uid: F:Table::System#Environment#Configuration#User_Tours.User_ID[132]
- type:
    name: Integer
    isExternal: true
  name: '"Tour ID"'
  uid: F:Table::System#Environment#Configuration#User_Tours.Tour_ID
- type:
    name: Option
    isExternal: true
  name: Status
  uid: F:Table::System#Environment#Configuration#User_Tours.Status
- type:
    name: Text[163]
    isExternal: true
  name: Version
  uid: F:Table::System#Environment#Configuration#User_Tours.Version[163]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#User_Tours.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#User_Tours.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#User_Tours.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#User_Tours.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#User_Tours.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#User_Tours.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#User Tours
name: '"User Tours"'
uid: O:Table::System#Environment#Configuration#User_Tours
