### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Field"
alId: ID 8616
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Package Field
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure GetRelationTablesID(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetRelationTablesID
  uid: M:Table::System#IO#Config#_Package_Field.GetRelationTablesID:Text
- syntax:
    content: 'procedure GetElementName(): Text[250]'
    return:
      returnType:
        name: Text[250]
        isExternal: true
  name: GetElementName
  uid: M:Table::System#IO#Config#_Package_Field.GetElementName:Text[250]
- syntax:
    content: 'procedure GetValidatedElementName(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetValidatedElementName
  uid: M:Table::System#IO#Config#_Package_Field.GetValidatedElementName:Text
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Package_Field.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Package_Field.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Field ID"'
  uid: F:Table::System#IO#Config#_Package_Field.Field_ID
- type:
    name: Text[30]
    isExternal: true
  name: '"Field Name"'
  uid: F:Table::System#IO#Config#_Package_Field.Field_Name[30]
- type:
    name: Text[250]
    isExternal: true
  name: '"Field Caption"'
  uid: F:Table::System#IO#Config#_Package_Field.Field_Caption[250]
- type:
    name: Boolean
    isExternal: true
  name: '"Validate Field"'
  uid: F:Table::System#IO#Config#_Package_Field.Validate_Field
- type:
    name: Boolean
    isExternal: true
  name: '"Include Field"'
  uid: F:Table::System#IO#Config#_Package_Field.Include_Field
- type:
    name: Boolean
    isExternal: true
  name: '"Localize Field"'
  uid: F:Table::System#IO#Config#_Package_Field.Localize_Field
- type:
    name: Integer
    isExternal: true
  name: '"Relation Table ID"'
  uid: F:Table::System#IO#Config#_Package_Field.Relation_Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Relation Table Caption"'
  uid: F:Table::System#IO#Config#_Package_Field.Relation_Table_Caption[250]
- type:
    name: Boolean
    isExternal: true
  name: Dimension
  uid: F:Table::System#IO#Config#_Package_Field.Dimension
- type:
    name: Boolean
    isExternal: true
  name: '"Primary Key"'
  uid: F:Table::System#IO#Config#_Package_Field.Primary_Key
- type:
    name: Integer
    isExternal: true
  name: '"Processing Order"'
  uid: F:Table::System#IO#Config#_Package_Field.Processing_Order
- type:
    name: Boolean
    isExternal: true
  name: '"Create Missing Codes"'
  uid: F:Table::System#IO#Config#_Package_Field.Create_Missing_Codes
- type:
    name: Boolean
    isExternal: true
  name: '"Mapping Exists"'
  uid: F:Table::System#IO#Config#_Package_Field.Mapping_Exists
- type:
    name: Boolean
    isExternal: true
  name: AutoIncrement
  uid: F:Table::System#IO#Config#_Package_Field.AutoIncrement
- type:
    name: Text[30]
    isExternal: true
  name: '"XML Field Name"'
  uid: F:Table::System#IO#Config#_Package_Field.XML_Field_Name[30]
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Package_Field.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Package_Field.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Package_Field.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Package_Field.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Package_Field.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Package_Field.SystemRowVersion
commentId: O:Table::System#IO#Config# Package Field
name: '"Config. Package Field"'
uid: O:Table::System#IO#Config#_Package_Field
