### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Related Table"
alId: ID 8625
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Related Table
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Related_Table.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Relation Table ID"'
  uid: F:Table::System#IO#Config#_Related_Table.Relation_Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Relation Table Name"'
  uid: F:Table::System#IO#Config#_Related_Table.Relation_Table_Name[250]
- type:
    name: Integer
    isExternal: true
  name: '"Related Fields"'
  uid: F:Table::System#IO#Config#_Related_Table.Related_Fields
- type:
    name: Boolean
    isExternal: true
  name: '"In Worksheet"'
  uid: F:Table::System#IO#Config#_Related_Table.In_Worksheet
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Related_Table.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Related_Table.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Related_Table.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Related_Table.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Related_Table.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Related_Table.SystemRowVersion
commentId: O:Table::System#IO#Config# Related Table
name: '"Config. Related Table"'
uid: O:Table::System#IO#Config#_Related_Table
