### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Application Area Setup"
alId: ID 9178
namespace: System.Environment.Configuration
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Application Area Setup
  promoted: false
- name: DataPerCompany
  value: "False"
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: InherentEntitlements
  value: rX
  promoted: false
- name: InherentPermissions
  value: rX
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Text[30]
    isExternal: true
  name: '"Company Name"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Company_Name[30]
- type:
    name: Code[30]
    isExternal: true
  name: '"Profile ID"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Profile_ID[30]
- type:
    name: Code[50]
    isExternal: true
  name: '"User ID"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.User_ID[50]
- type:
    name: Boolean
    isExternal: true
  name: Invoicing
  obsoletion:
    state: removed
    reason: Microsoft Invoicing is not supported on Business Central
    version: "18.0"
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Invoicing
- type:
    name: Boolean
    isExternal: true
  name: Basic
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic
- type:
    name: Boolean
    isExternal: true
  name: Suite
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Suite
- type:
    name: Boolean
    isExternal: true
  name: '"Relationship Mgmt"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Relationship_Mgmt
- type:
    name: Boolean
    isExternal: true
  name: Jobs
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Jobs
- type:
    name: Boolean
    isExternal: true
  name: '"Fixed Assets"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Fixed_Assets
- type:
    name: Boolean
    isExternal: true
  name: Location
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Location
- type:
    name: Boolean
    isExternal: true
  name: BasicHR
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.BasicHR
- type:
    name: Boolean
    isExternal: true
  name: Assembly
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Assembly
- type:
    name: Boolean
    isExternal: true
  name: '"Item Charges"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Item_Charges
- type:
    name: Boolean
    isExternal: true
  name: Advanced
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Advanced
- type:
    name: Boolean
    isExternal: true
  name: Warehouse
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Warehouse
- type:
    name: Boolean
    isExternal: true
  name: Service
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Service
- type:
    name: Boolean
    isExternal: true
  name: Manufacturing
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Manufacturing
- type:
    name: Boolean
    isExternal: true
  name: Planning
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Planning
- type:
    name: Boolean
    isExternal: true
  name: Dimensions
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Dimensions
- type:
    name: Boolean
    isExternal: true
  name: '"Item Tracking"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Item_Tracking
- type:
    name: Boolean
    isExternal: true
  name: Intercompany
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Intercompany
- type:
    name: Boolean
    isExternal: true
  name: '"Sales Return Order"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Sales_Return_Order
- type:
    name: Boolean
    isExternal: true
  name: '"Purch Return Order"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Purch_Return_Order
- type:
    name: Boolean
    isExternal: true
  name: Prepayments
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Prepayments
- type:
    name: Boolean
    isExternal: true
  name: '"Cost Accounting"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Cost_Accounting
- type:
    name: Boolean
    isExternal: true
  name: '"Sales Budget"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Sales_Budget
- type:
    name: Boolean
    isExternal: true
  name: '"Purchase Budget"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Purchase_Budget
- type:
    name: Boolean
    isExternal: true
  name: '"Item Budget"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Item_Budget
- type:
    name: Boolean
    isExternal: true
  name: '"Sales Analysis"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Sales_Analysis
- type:
    name: Boolean
    isExternal: true
  name: '"Purchase Analysis"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Purchase_Analysis
- type:
    name: Boolean
    isExternal: true
  name: '"Inventory Analysis"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Inventory_Analysis
- type:
    name: Boolean
    isExternal: true
  name: XBRL
  obsoletion:
    state: removed
    reason: XBRL feature will be discontinued
    version: "23.0"
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.XBRL
- type:
    name: Boolean
    isExternal: true
  name: Reservation
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Reservation
- type:
    name: Boolean
    isExternal: true
  name: '"Order Promising"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Order_Promising
- type:
    name: Boolean
    isExternal: true
  name: ADCS
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.ADCS
- type:
    name: Boolean
    isExternal: true
  name: Comments
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Comments
- type:
    name: Boolean
    isExternal: true
  name: '"Record Links"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Record_Links
- type:
    name: Boolean
    isExternal: true
  name: Notes
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Notes
- type:
    name: Boolean
    isExternal: true
  name: VAT
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.VAT
- type:
    name: Boolean
    isExternal: true
  name: '"Sales Tax"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Sales_Tax
- type:
    name: Boolean
    isExternal: true
  name: '"Item References"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Item_References
- type:
    name: Boolean
    isExternal: true
  name: '"Basic EU"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_EU
- type:
    name: Boolean
    isExternal: true
  name: '"Basic CA"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_CA
- type:
    name: Boolean
    isExternal: true
  name: '"Basic US"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_US
- type:
    name: Boolean
    isExternal: true
  name: '"Basic MX"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_MX
- type:
    name: Boolean
    isExternal: true
  name: '"Basic AU"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_AU
- type:
    name: Boolean
    isExternal: true
  name: '"Basic NZ"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_NZ
- type:
    name: Boolean
    isExternal: true
  name: '"Basic AT"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_AT
- type:
    name: Boolean
    isExternal: true
  name: '"Basic CH"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_CH
- type:
    name: Boolean
    isExternal: true
  name: '"Basic DE"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_DE
- type:
    name: Boolean
    isExternal: true
  name: '"Basic BE"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_BE
- type:
    name: Boolean
    isExternal: true
  name: '"Basic CZ"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_CZ
- type:
    name: Boolean
    isExternal: true
  name: '"Basic DK"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_DK
- type:
    name: Boolean
    isExternal: true
  name: '"Basic ES"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_ES
- type:
    name: Boolean
    isExternal: true
  name: '"Basic FI"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_FI
- type:
    name: Boolean
    isExternal: true
  name: '"Basic FR"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_FR
- type:
    name: Boolean
    isExternal: true
  name: '"Basic GB"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_GB
- type:
    name: Boolean
    isExternal: true
  name: '"Basic IS"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_IS
- type:
    name: Boolean
    isExternal: true
  name: '"Basic IT"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_IT
- type:
    name: Boolean
    isExternal: true
  name: '"Basic NL"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_NL
- type:
    name: Boolean
    isExternal: true
  name: '"Basic NO"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_NO
- type:
    name: Boolean
    isExternal: true
  name: '"Basic RU"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_RU
- type:
    name: Boolean
    isExternal: true
  name: '"Basic SE"'
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.Basic_SE
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#Environment#Configuration#Application_Area_Setup.SystemRowVersion
commentId: O:Table::System#Environment#Configuration#Application Area Setup
name: '"Application Area Setup"'
uid: O:Table::System#Environment#Configuration#Application_Area_Setup
