### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Tmpl. Selection Rules"
alId: ID 8620
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Tmpl. Selection Rules
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
fields:
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.Table_ID
- type:
    name: Code[10]
    isExternal: true
  name: '"Template Code"'
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.Template_Code[10]
- type:
    name: Blob
    isExternal: true
  name: '"Selection Criteria"'
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.Selection_Criteria
- type:
    name: Text[250]
    isExternal: true
  name: Description
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.Description[250]
- type:
    name: Integer
    isExternal: true
  name: Order
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.Order
- type:
    name: Integer
    isExternal: true
  name: '"Page ID"'
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.Page_ID
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Tmpl#_Selection_Rules.SystemRowVersion
commentId: O:Table::System#IO#Config# Tmpl# Selection Rules
name: '"Config. Tmpl. Selection Rules"'
uid: O:Table::System#IO#Config#_Tmpl#_Selection_Rules
