### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Setup"
alId: ID 8627
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Setup
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure SelectDefaultRoleCenter(ProfileID: Code[30], AppID: Guid, Scope: Option)'
    parameters:
    - id: ProfileID
      parameterType:
        name: Code[30]
        isExternal: true
    - id: AppID
      parameterType:
        name: Guid
        isExternal: true
    - id: Scope
      parameterType:
        name: Option
        isExternal: true
  name: SelectDefaultRoleCenter
  uid: M:Table::System#IO#Config#_Setup.SelectDefaultRoleCenter(Code[30],Guid,Option)
- syntax:
    content: 'procedure ReadPackageHeaderFromStream(InStream: InStream)'
    parameters:
    - id: InStream
      parameterType:
        name: InStream
        isExternal: true
  name: ReadPackageHeaderFromStream
  uid: M:Table::System#IO#Config#_Setup.ReadPackageHeaderFromStream(InStream)
- syntax:
    content: 'procedure ImportPackageFromStream(InStream: InStream)'
    parameters:
    - id: InStream
      parameterType:
        name: InStream
        isExternal: true
  name: ImportPackageFromStream
  uid: M:Table::System#IO#Config#_Setup.ImportPackageFromStream(InStream)
- syntax:
    content: 'procedure ApplyPackages(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: ApplyPackages
  uid: M:Table::System#IO#Config#_Setup.ApplyPackages:Integer
- syntax:
    content: procedure ApplyAnswers()
  name: ApplyAnswers
  uid: M:Table::System#IO#Config#_Setup.ApplyAnswers
- syntax:
    content: procedure CopyCompInfo()
  name: CopyCompInfo
  uid: M:Table::System#IO#Config#_Setup.CopyCompInfo
- syntax:
    content: 'procedure SetHideDialog(NewHideDialog: Boolean)'
    parameters:
    - id: NewHideDialog
      parameterType:
        name: Boolean
        isExternal: true
  name: SetHideDialog
  uid: M:Table::System#IO#Config#_Setup.SetHideDialog(Boolean)
- syntax:
    content: 'procedure DecompressPackageToBlob(TempBlob: __MissingTypeSymbol__, TempBlobUncompressed: __MissingTypeSymbol__)'
    parameters:
    - id: TempBlob
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    - id: TempBlobUncompressed
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
  name: DecompressPackageToBlob
  uid: M:Table::System#IO#Config#_Setup.DecompressPackageToBlob(__MissingSymbol__@,__MissingSymbol__@)
fields:
- type:
    name: Code[10]
    isExternal: true
  name: '"Primary Key"'
  uid: F:Table::System#IO#Config#_Setup.Primary_Key[10]
- type:
    name: Text[100]
    isExternal: true
  name: Name
  uid: F:Table::System#IO#Config#_Setup.Name[100]
- type:
    name: Text[50]
    isExternal: true
  name: '"Name 2"'
  uid: F:Table::System#IO#Config#_Setup.Name_2[50]
- type:
    name: Text[100]
    isExternal: true
  name: Address
  uid: F:Table::System#IO#Config#_Setup.Address[100]
- type:
    name: Text[50]
    isExternal: true
  name: '"Address 2"'
  uid: F:Table::System#IO#Config#_Setup.Address_2[50]
- type:
    name: Text[30]
    isExternal: true
  name: City
  uid: F:Table::System#IO#Config#_Setup.City[30]
- type:
    name: Text[30]
    isExternal: true
  name: '"Phone No."'
  uid: F:Table::System#IO#Config#_Setup.Phone_No#[30]
- type:
    name: Text[30]
    isExternal: true
  name: '"Phone No. 2"'
  uid: F:Table::System#IO#Config#_Setup.Phone_No#_2[30]
- type:
    name: Text[30]
    isExternal: true
  name: '"Telex No."'
  uid: F:Table::System#IO#Config#_Setup.Telex_No#[30]
- type:
    name: Text[30]
    isExternal: true
  name: '"Fax No."'
  uid: F:Table::System#IO#Config#_Setup.Fax_No#[30]
- type:
    name: Text[20]
    isExternal: true
  name: '"Giro No."'
  uid: F:Table::System#IO#Config#_Setup.Giro_No#[20]
- type:
    name: Text[100]
    isExternal: true
  name: '"Bank Name"'
  uid: F:Table::System#IO#Config#_Setup.Bank_Name[100]
- type:
    name: Text[20]
    isExternal: true
  name: '"Bank Branch No."'
  uid: F:Table::System#IO#Config#_Setup.Bank_Branch_No#[20]
- type:
    name: Text[30]
    isExternal: true
  name: '"Bank Account No."'
  uid: F:Table::System#IO#Config#_Setup.Bank_Account_No#[30]
- type:
    name: Text[20]
    isExternal: true
  name: '"Payment Routing No."'
  uid: F:Table::System#IO#Config#_Setup.Payment_Routing_No#[20]
- type:
    name: Text[10]
    isExternal: true
  name: '"Customs Permit No."'
  uid: F:Table::System#IO#Config#_Setup.Customs_Permit_No#[10]
- type:
    name: Date
    isExternal: true
  name: '"Customs Permit Date"'
  uid: F:Table::System#IO#Config#_Setup.Customs_Permit_Date
- type:
    name: Text[20]
    isExternal: true
  name: '"VAT Registration No."'
  uid: F:Table::System#IO#Config#_Setup.VAT_Registration_No#[20]
- type:
    name: Text[20]
    isExternal: true
  name: '"Registration No."'
  uid: F:Table::System#IO#Config#_Setup.Registration_No#[20]
- type:
    name: Text[20]
    isExternal: true
  name: '"Telex Answer Back"'
  uid: F:Table::System#IO#Config#_Setup.Telex_Answer_Back[20]
- type:
    name: Text[100]
    isExternal: true
  name: '"Ship-to Name"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_Name[100]
- type:
    name: Text[50]
    isExternal: true
  name: '"Ship-to Name 2"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_Name_2[50]
- type:
    name: Text[100]
    isExternal: true
  name: '"Ship-to Address"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_Address[100]
- type:
    name: Text[50]
    isExternal: true
  name: '"Ship-to Address 2"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_Address_2[50]
- type:
    name: Text[30]
    isExternal: true
  name: '"Ship-to City"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_City[30]
- type:
    name: Text[100]
    isExternal: true
  name: '"Ship-to Contact"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_Contact[100]
- type:
    name: Code[10]
    isExternal: true
  name: '"Location Code"'
  uid: F:Table::System#IO#Config#_Setup.Location_Code[10]
- type:
    name: Blob
    isExternal: true
  name: Picture
  uid: F:Table::System#IO#Config#_Setup.Picture
- type:
    name: Code[20]
    isExternal: true
  name: '"Post Code"'
  uid: F:Table::System#IO#Config#_Setup.Post_Code[20]
- type:
    name: Text[30]
    isExternal: true
  name: County
  uid: F:Table::System#IO#Config#_Setup.County[30]
- type:
    name: Code[20]
    isExternal: true
  name: '"Ship-to Post Code"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_Post_Code[20]
- type:
    name: Text[30]
    isExternal: true
  name: '"Ship-to County"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_County[30]
- type:
    name: Text[80]
    isExternal: true
  name: '"E-Mail"'
  uid: F:Table::System#IO#Config#_Setup.E-Mail[80]
- type:
    name: Text[80]
    isExternal: true
  name: '"Home Page"'
  obsoletion:
    state: pending
    reason: Field length will be increased to 255.
    version: "24.0"
  uid: F:Table::System#IO#Config#_Setup.Home_Page[80]
- type:
    name: Code[10]
    isExternal: true
  name: '"Country/Region Code"'
  uid: F:Table::System#IO#Config#_Setup.Country/Region_Code[10]
- type:
    name: Code[10]
    isExternal: true
  name: '"Ship-to Country/Region Code"'
  uid: F:Table::System#IO#Config#_Setup.Ship-to_Country/Region_Code[10]
- type:
    name: Code[50]
    isExternal: true
  name: IBAN
  uid: F:Table::System#IO#Config#_Setup.IBAN[50]
- type:
    name: Code[20]
    isExternal: true
  name: '"SWIFT Code"'
  uid: F:Table::System#IO#Config#_Setup.SWIFT_Code[20]
- type:
    name: Text[30]
    isExternal: true
  name: '"Industrial Classification"'
  uid: F:Table::System#IO#Config#_Setup.Industrial_Classification[30]
- type:
    name: Option
    isExternal: true
  name: '"Logo Position on Documents"'
  uid: F:Table::System#IO#Config#_Setup.Logo_Position_on_Documents
- type:
    name: Code[10]
    isExternal: true
  name: '"Responsibility Center"'
  uid: F:Table::System#IO#Config#_Setup.Responsibility_Center[10]
- type:
    name: DateFormula
    isExternal: true
  name: '"Check-Avail. Period Calc."'
  uid: F:Table::System#IO#Config#_Setup.Check-Avail#_Period_Calc#
- type:
    name: Option
    isExternal: true
  name: '"Check-Avail. Time Bucket"'
  uid: F:Table::System#IO#Config#_Setup.Check-Avail#_Time_Bucket
- type:
    name: Code[10]
    isExternal: true
  name: '"Base Calendar Code"'
  uid: F:Table::System#IO#Config#_Setup.Base_Calendar_Code[10]
- type:
    name: DateFormula
    isExternal: true
  name: '"Cal. Convergence Time Frame"'
  uid: F:Table::System#IO#Config#_Setup.Cal#_Convergence_Time_Frame
- type:
    name: Text[250]
    isExternal: true
  name: '"Package File Name"'
  uid: F:Table::System#IO#Config#_Setup.Package_File_Name[250]
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Setup.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Language ID"'
  uid: F:Table::System#IO#Config#_Setup.Language_ID
- type:
    name: Text[80]
    isExternal: true
  name: '"Product Version"'
  uid: F:Table::System#IO#Config#_Setup.Product_Version[80]
- type:
    name: Text[50]
    isExternal: true
  name: '"Package Name"'
  uid: F:Table::System#IO#Config#_Setup.Package_Name[50]
- type:
    name: Code[30]
    isExternal: true
  name: '"Your Profile Code"'
  uid: F:Table::System#IO#Config#_Setup.Your_Profile_Code[30]
- type:
    name: Guid
    isExternal: true
  name: '"Your Profile App ID"'
  uid: F:Table::System#IO#Config#_Setup.Your_Profile_App_ID
- type:
    name: Option
    isExternal: true
  name: '"Your Profile Scope"'
  uid: F:Table::System#IO#Config#_Setup.Your_Profile_Scope
- type:
    name: Blob
    isExternal: true
  name: '"Package File"'
  uid: F:Table::System#IO#Config#_Setup.Package_File
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Setup.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Setup.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Setup.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Setup.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Setup.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Setup.SystemRowVersion
commentId: O:Table::System#IO#Config# Setup
name: '"Config. Setup"'
uid: O:Table::System#IO#Config#_Setup
