### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Record For Processing"
alId: ID 8632
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Record For Processing
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure AddRecord(ConfigPackageRecord: Record "Config. Package Record", ProcessingRuleNo: Integer)'
    parameters:
    - id: ConfigPackageRecord
      parameterType:
        name: Record "Config. Package Record"
        isExternal: true
    - id: ProcessingRuleNo
      parameterType:
        name: Integer
        isExternal: true
  name: AddRecord
  uid: M:Table::System#IO#Config#_Record_For_Processing.AddRecord(Config#_Package_Record,Integer)
- syntax:
    content: 'procedure FindConfigRecord(var ConfigPackageRecord: Record "Config. Package Record"): Boolean'
    parameters:
    - id: ConfigPackageRecord
      parameterType:
        name: Record "Config. Package Record"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: FindConfigRecord
  uid: M:Table::System#IO#Config#_Record_For_Processing.FindConfigRecord(Config#_Package_Record@):Boolean
- syntax:
    content: 'procedure FindConfigRule(var ConfigTableProcessingRule: Record "Config. Table Processing Rule"): Boolean'
    parameters:
    - id: ConfigTableProcessingRule
      parameterType:
        name: Record "Config. Table Processing Rule"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: FindConfigRule
  uid: M:Table::System#IO#Config#_Record_For_Processing.FindConfigRule(Config#_Table_Processing_Rule@):Boolean
- syntax:
    content: 'procedure FindInsertedRecord(var RecRef: RecordRef): Boolean'
    parameters:
    - id: RecRef
      parameterType:
        name: RecordRef
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: FindInsertedRecord
  uid: M:Table::System#IO#Config#_Record_For_Processing.FindInsertedRecord(RecordRef@):Boolean
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Record_For_Processing.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Record_For_Processing.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Rule No."'
  uid: F:Table::System#IO#Config#_Record_For_Processing.Rule_No#
- type:
    name: Integer
    isExternal: true
  name: '"Record No."'
  uid: F:Table::System#IO#Config#_Record_For_Processing.Record_No#
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Record_For_Processing.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Record_For_Processing.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Record_For_Processing.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Record_For_Processing.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Record_For_Processing.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Record_For_Processing.SystemRowVersion
commentId: O:Table::System#IO#Config# Record For Processing
name: '"Config. Record For Processing"'
uid: O:Table::System#IO#Config#_Record_For_Processing
