### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Table Processing Rule"
alId: ID 8631
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Table Processing Rule
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: 'procedure FindTableRules(ConfigPackageTable: Record "Config. Package Table"): Boolean'
    parameters:
    - id: ConfigPackageTable
      parameterType:
        name: Record "Config. Package Table"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: FindTableRules
  uid: M:Table::System#IO#Config#_Table_Processing_Rule.FindTableRules(Config#_Package_Table):Boolean
- syntax:
    content: 'procedure GetFilterInfo(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetFilterInfo
  uid: M:Table::System#IO#Config#_Table_Processing_Rule.GetFilterInfo:Text
- syntax:
    content: 'procedure Process(ConfigRecordForProcessing: Record "Config. Record For Processing"): Boolean'
    parameters:
    - id: ConfigRecordForProcessing
      parameterType:
        name: Record "Config. Record For Processing"
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: Process
  uid: M:Table::System#IO#Config#_Table_Processing_Rule.Process(Config#_Record_For_Processing):Boolean
- syntax:
    content: 'procedure RunActionOnInsertedRecord(RecRef: RecordRef): Boolean'
    parameters:
    - id: RecRef
      parameterType:
        name: RecordRef
        isExternal: true
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: RunActionOnInsertedRecord
  uid: M:Table::System#IO#Config#_Table_Processing_Rule.RunActionOnInsertedRecord(RecordRef):Boolean
- syntax:
    content: procedure ShowFilters()
  name: ShowFilters
  uid: M:Table::System#IO#Config#_Table_Processing_Rule.ShowFilters
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.Table_ID
- type:
    name: Integer
    isExternal: true
  name: '"Rule No."'
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.Rule_No#
- type:
    name: Option
    isExternal: true
  name: Action
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.Action
- type:
    name: Integer
    isExternal: true
  name: '"Custom Processing Codeunit ID"'
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.Custom_Processing_Codeunit_ID
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Table_Processing_Rule.SystemRowVersion
commentId: O:Table::System#IO#Config# Table Processing Rule
name: '"Config. Table Processing Rule"'
uid: O:Table::System#IO#Config#_Table_Processing_Rule
