### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package Table"
alId: ID 8613
namespace: System.IO
baseKind: Table
kind: Table
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Table](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-table-object)'
objectProperties:
- name: Caption
  value: Config. Package Table
  promoted: false
- name: ReplicateData
  value: "False"
  promoted: false
- name: DataClassification
  value: CustomerContent
  promoted: false
methods:
- syntax:
    content: procedure InitDimensionFields()
  name: InitDimensionFields
  uid: M:Table::System#IO#Config#_Package_Table.InitDimensionFields
- syntax:
    content: procedure DeletePackageData()
  name: DeletePackageData
  uid: M:Table::System#IO#Config#_Package_Table.DeletePackageData
- syntax:
    content: 'procedure DeletePackageDataForPackage(PackageCode: Code[20], TableId: Integer)'
    parameters:
    - id: PackageCode
      parameterType:
        name: Code[20]
        isExternal: true
    - id: TableId
      parameterType:
        name: Integer
        isExternal: true
  name: DeletePackageDataForPackage
  uid: M:Table::System#IO#Config#_Package_Table.DeletePackageDataForPackage(Code[20],Integer)
- syntax:
    content: 'procedure DimensionFieldsCount(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: DimensionFieldsCount
  uid: M:Table::System#IO#Config#_Package_Table.DimensionFieldsCount:Integer
- syntax:
    content: 'procedure DimensionPackageDataExist(): Boolean'
    return:
      returnType:
        name: Boolean
        isExternal: true
  name: DimensionPackageDataExist
  uid: M:Table::System#IO#Config#_Package_Table.DimensionPackageDataExist:Boolean
- syntax:
    content: 'procedure ShowPackageRecords(Show: Option, ShowDim: Boolean)'
    parameters:
    - id: Show
      parameterType:
        name: Option
        isExternal: true
    - id: ShowDim
      parameterType:
        name: Boolean
        isExternal: true
  name: ShowPackageRecords
  uid: M:Table::System#IO#Config#_Package_Table.ShowPackageRecords(Option,Boolean)
- syntax:
    content: procedure ShowDatabaseRecords()
  name: ShowDatabaseRecords
  uid: M:Table::System#IO#Config#_Package_Table.ShowDatabaseRecords
- syntax:
    content: procedure ShowPackageFields()
  name: ShowPackageFields
  uid: M:Table::System#IO#Config#_Package_Table.ShowPackageFields
- syntax:
    content: 'procedure ShowFilteredPackageFields(FilterValue: Text)'
    parameters:
    - id: FilterValue
      parameterType:
        name: Text
        isExternal: true
  name: ShowFilteredPackageFields
  uid: M:Table::System#IO#Config#_Package_Table.ShowFilteredPackageFields(Text)
- syntax:
    content: 'procedure ShowPackageCard(PackageCode: Code[20])'
    parameters:
    - id: PackageCode
      parameterType:
        name: Code[20]
        isExternal: true
  name: ShowPackageCard
  uid: M:Table::System#IO#Config#_Package_Table.ShowPackageCard(Code[20])
- syntax:
    content: 'procedure SetFieldStyle(FieldNumber: Integer): Text'
    parameters:
    - id: FieldNumber
      parameterType:
        name: Integer
        isExternal: true
    return:
      returnType:
        name: Text
        isExternal: true
  name: SetFieldStyle
  uid: M:Table::System#IO#Config#_Package_Table.SetFieldStyle(Integer):Text
- syntax:
    content: procedure ShowFilters()
  name: ShowFilters
  uid: M:Table::System#IO#Config#_Package_Table.ShowFilters
- syntax:
    content: procedure ShowProcessingRules()
  name: ShowProcessingRules
  uid: M:Table::System#IO#Config#_Package_Table.ShowProcessingRules
- syntax:
    content: 'procedure SetHideValidationDialog(NewHideValidationDialog: Boolean)'
    parameters:
    - id: NewHideValidationDialog
      parameterType:
        name: Boolean
        isExternal: true
  name: SetHideValidationDialog
  uid: M:Table::System#IO#Config#_Package_Table.SetHideValidationDialog(Boolean)
- syntax:
    content: 'procedure GetNoOfDatabaseRecords(): Integer'
    return:
      returnType:
        name: Integer
        isExternal: true
  name: GetNoOfDatabaseRecords
  uid: M:Table::System#IO#Config#_Package_Table.GetNoOfDatabaseRecords:Integer
- syntax:
    content: 'procedure GetNoOfDatabaseRecordsText(): Text'
    return:
      returnType:
        name: Text
        isExternal: true
  name: GetNoOfDatabaseRecordsText
  uid: M:Table::System#IO#Config#_Package_Table.GetNoOfDatabaseRecordsText:Text
fields:
- type:
    name: Code[20]
    isExternal: true
  name: '"Package Code"'
  uid: F:Table::System#IO#Config#_Package_Table.Package_Code[20]
- type:
    name: Integer
    isExternal: true
  name: '"Table ID"'
  uid: F:Table::System#IO#Config#_Package_Table.Table_ID
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Name"'
  uid: F:Table::System#IO#Config#_Package_Table.Table_Name[250]
- type:
    name: Integer
    isExternal: true
  name: '"No. of Package Records"'
  uid: F:Table::System#IO#Config#_Package_Table.No#_of_Package_Records
- type:
    name: Integer
    isExternal: true
  name: '"No. of Package Errors"'
  uid: F:Table::System#IO#Config#_Package_Table.No#_of_Package_Errors
- type:
    name: DateTime
    isExternal: true
  name: '"Imported Date and Time"'
  uid: F:Table::System#IO#Config#_Package_Table.Imported_Date_and_Time
- type:
    name: DateTime
    isExternal: true
  name: '"Exported Date and Time"'
  uid: F:Table::System#IO#Config#_Package_Table.Exported_Date_and_Time
- type:
    name: Text[250]
    isExternal: true
  name: Comments
  uid: F:Table::System#IO#Config#_Package_Table.Comments[250]
- type:
    name: DateTime
    isExternal: true
  name: '"Created Date and Time"'
  uid: F:Table::System#IO#Config#_Package_Table.Created_Date_and_Time
- type:
    name: Text[30]
    isExternal: true
  name: '"Company Filter (Source Table)"'
  uid: F:Table::System#IO#Config#_Package_Table.Company_Filter_(Source_Table)[30]
- type:
    name: Text[250]
    isExternal: true
  name: '"Table Caption"'
  uid: F:Table::System#IO#Config#_Package_Table.Table_Caption[250]
- type:
    name: Code[10]
    isExternal: true
  name: '"Data Template"'
  uid: F:Table::System#IO#Config#_Package_Table.Data_Template[10]
- type:
    name: Integer
    isExternal: true
  name: '"Package Processing Order"'
  uid: F:Table::System#IO#Config#_Package_Table.Package_Processing_Order
- type:
    name: Integer
    isExternal: true
  name: '"Page ID"'
  uid: F:Table::System#IO#Config#_Package_Table.Page_ID
- type:
    name: Integer
    isExternal: true
  name: '"Processing Order"'
  uid: F:Table::System#IO#Config#_Package_Table.Processing_Order
- type:
    name: Integer
    isExternal: true
  name: '"No. of Fields Included"'
  uid: F:Table::System#IO#Config#_Package_Table.No#_of_Fields_Included
- type:
    name: Integer
    isExternal: true
  name: '"No. of Fields Available"'
  uid: F:Table::System#IO#Config#_Package_Table.No#_of_Fields_Available
- type:
    name: Integer
    isExternal: true
  name: '"No. of Fields to Validate"'
  uid: F:Table::System#IO#Config#_Package_Table.No#_of_Fields_to_Validate
- type:
    name: Text[50]
    isExternal: true
  name: '"Package Caption"'
  uid: F:Table::System#IO#Config#_Package_Table.Package_Caption[50]
- type:
    name: Code[50]
    isExternal: true
  name: '"Imported by User ID"'
  uid: F:Table::System#IO#Config#_Package_Table.Imported_by_User_ID[50]
- type:
    name: Code[50]
    isExternal: true
  name: '"Created by User ID"'
  uid: F:Table::System#IO#Config#_Package_Table.Created_by_User_ID[50]
- type:
    name: Boolean
    isExternal: true
  name: '"Dimensions as Columns"'
  uid: F:Table::System#IO#Config#_Package_Table.Dimensions_as_Columns
- type:
    name: Boolean
    isExternal: true
  name: Filtered
  uid: F:Table::System#IO#Config#_Package_Table.Filtered
- type:
    name: Boolean
    isExternal: true
  name: '"Skip Table Triggers"'
  uid: F:Table::System#IO#Config#_Package_Table.Skip_Table_Triggers
- type:
    name: Boolean
    isExternal: true
  name: '"Delete Recs Before Processing"'
  uid: F:Table::System#IO#Config#_Package_Table.Delete_Recs_Before_Processing
- type:
    name: Integer
    isExternal: true
  name: '"Processing Report ID"'
  uid: F:Table::System#IO#Config#_Package_Table.Processing_Report_ID
- type:
    name: Integer
    isExternal: true
  name: '"Parent Table ID"'
  uid: F:Table::System#IO#Config#_Package_Table.Parent_Table_ID
- type:
    name: Boolean
    isExternal: true
  name: Validated
  uid: F:Table::System#IO#Config#_Package_Table.Validated
- type:
    name: Boolean
    isExternal: true
  name: '"Delayed Insert"'
  uid: F:Table::System#IO#Config#_Package_Table.Delayed_Insert
- type:
    name: Boolean
    isExternal: true
  name: '"Cross-Column Filter"'
  uid: F:Table::System#IO#Config#_Package_Table.Cross-Column_Filter
- type:
    name: Guid
    isExternal: true
  name: SystemId
  uid: F:Table::System#IO#Config#_Package_Table.SystemId
- type:
    name: DateTime
    isExternal: true
  name: SystemCreatedAt
  uid: F:Table::System#IO#Config#_Package_Table.SystemCreatedAt
- type:
    name: Guid
    isExternal: true
  name: SystemCreatedBy
  uid: F:Table::System#IO#Config#_Package_Table.SystemCreatedBy
- type:
    name: DateTime
    isExternal: true
  name: SystemModifiedAt
  uid: F:Table::System#IO#Config#_Package_Table.SystemModifiedAt
- type:
    name: Guid
    isExternal: true
  name: SystemModifiedBy
  uid: F:Table::System#IO#Config#_Package_Table.SystemModifiedBy
- type:
    name: BigInteger
    isExternal: true
  name: SystemRowVersion
  uid: F:Table::System#IO#Config#_Package_Table.SystemRowVersion
commentId: O:Table::System#IO#Config# Package Table
name: '"Config. Package Table"'
uid: O:Table::System#IO#Config#_Package_Table
