### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Copy Company"
alId: ID 357
namespace: System.Environment.Configuration
baseKind: Report
kind: Report
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Report](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-report-object)'
objectProperties:
- name: Caption
  value: Copy Company
  promoted: false
- name: Permissions
  value: tabledata "Feature Data Update Status" = ri
  promoted: false
- name: ProcessingOnly
  value: "True"
  promoted: false
- name: Caption
  value: Copy Company
  promoted: false
- name: Permissions
  value: tabledata "Feature Data Update Status" = ri
  promoted: false
- name: ProcessingOnly
  value: "True"
  promoted: false
methods:
- syntax:
    content: 'procedure GetCompanyName(): Text[30]'
    return:
      returnType:
        name: Text[30]
        isExternal: true
  name: GetCompanyName
  uid: M:Report::System#Environment#Configuration#Copy_Company.GetCompanyName:Text[30]
commentId: O:Report::System#Environment#Configuration#Copy Company
name: '"Copy Company"'
uid: O:Report::System#Environment#Configuration#Copy_Company
