### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Get Config. Tables"
alId: ID 8614
namespace: System.IO
baseKind: Report
kind: Report
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Report](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-report-object)'
objectProperties:
- name: Caption
  value: Get Config. Tables
  promoted: false
- name: ProcessingOnly
  value: "True"
  promoted: false
- name: Caption
  value: Get Config. Tables
  promoted: false
- name: ProcessingOnly
  value: "True"
  promoted: false
methods:
- syntax:
    content: 'procedure InitializeRequest(NewIncludeWithDataOnly: Boolean, NewIncludeRelatedTables: Boolean, NewIncludeDimensionTables: Boolean, NewIncludeLicensedTablesOnly: Boolean)'
    parameters:
    - id: NewIncludeWithDataOnly
      parameterType:
        name: Boolean
        isExternal: true
    - id: NewIncludeRelatedTables
      parameterType:
        name: Boolean
        isExternal: true
    - id: NewIncludeDimensionTables
      parameterType:
        name: Boolean
        isExternal: true
    - id: NewIncludeLicensedTablesOnly
      parameterType:
        name: Boolean
        isExternal: true
  name: InitializeRequest
  uid: M:Report::System#IO#Get_Config#_Tables.InitializeRequest(Boolean,Boolean,Boolean,Boolean)
commentId: O:Report::System#IO#Get Config# Tables
name: '"Get Config. Tables"'
uid: O:Report::System#IO#Get_Config#_Tables
