### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Notification Email"
alId: ID 1320
namespace: System.Environment.Configuration
baseKind: Report
kind: Report
parent: N:Module::Base_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Report](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-report-object)'
objectProperties:
- name: WordLayout
  value: ./System/Notifications/NotificationEmail.docx
  promoted: false
- name: Caption
  value: Notification Email
  promoted: false
- name: DefaultLayout
  value: Word
  promoted: false
- name: WordLayout
  value: ./System/Notifications/NotificationEmail.docx
  promoted: false
- name: Caption
  value: Notification Email
  promoted: false
- name: DefaultLayout
  value: Word
  promoted: false
commentId: O:Report::System#Environment#Configuration#Notification Email
name: '"Notification Email"'
uid: O:Report::System#Environment#Configuration#Notification_Email
