### YamlMime:BusinessCentralApplicationObject
fqName: System.IO."Config. Package - Process"
alId: ID 8621
namespace: System.IO
baseKind: Report
kind: Report
parent: N:Module::Base_Application::Namespace::System.IO
langs:
- al
seeAlso:
- '[Report](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-report-object)'
objectProperties:
- name: Caption
  value: Config. Package - Process
  promoted: false
- name: ProcessingOnly
  value: "True"
  promoted: false
- name: TransactionType
  value: UpdateNoLocks
  promoted: false
- name: Caption
  value: Config. Package - Process
  promoted: false
- name: ProcessingOnly
  value: "True"
  promoted: false
- name: TransactionType
  value: UpdateNoLocks
  promoted: false
methods:
- syntax:
    content: 'procedure AddRuleForField(TableNo: Integer, FieldNo: Integer, TransformationType: Option, TempField: __MissingTypeSymbol__, var TempTransformationRule: Record "Transformation Rule" temporary)'
    parameters:
    - id: TableNo
      parameterType:
        name: Integer
        isExternal: true
    - id: FieldNo
      parameterType:
        name: Integer
        isExternal: true
    - id: TransformationType
      parameterType:
        name: Option
        isExternal: true
    - id: TempField
      parameterType:
        name: __MissingTypeSymbol__
        isExternal: true
    - id: TempTransformationRule
      parameterType:
        name: Record "Transformation Rule" temporary
        isExternal: true
  name: AddRuleForField
  uid: M:Report::System#IO#Config#_Package_-_Process.AddRuleForField(Integer,Integer,Option,__MissingSymbol__@,Transformation_Rule@)
commentId: O:Report::System#IO#Config# Package - Process
name: '"Config. Package - Process"'
uid: O:Report::System#IO#Config#_Package_-_Process
